/*
Copyright (c) 2005-2014 Choe Hwanjin
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
3. Neither the name of the author nor the names of its contributors
   may be used to endorse or promote products derived from this software
   without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
*/
// Character groups adapted from libhangul data/hanja/mssymbol.txt.
// Source: https://github.com/libhangul/libhangul/blob/main/data/hanja/mssymbol.txt
export const IME_SYMBOL_GROUPS = [
    { key: "ㄱ", category: "punctuation", keywords: "기역 문장 부호 punctuation", characters: [
        ["\u3000", "전각 공백 ideographic space"],
        ["！", "fullwidth exclamation mark"],
        ["＇", "fullwidth apostrophe"],
        ["，", "fullwidth comma"],
        ["．", "fullwidth full stop"],
        ["／", "fullwidth solidus"],
        ["：", "fullwidth colon"],
        ["；", "fullwidth semicolon"],
        ["？", "fullwidth question mark"],
        ["＾", "fullwidth circumflex accent"],
        ["＿", "fullwidth low line"],
        ["｀", "fullwidth grave accent"],
        ["｜", "fullwidth vertical line"],
        ["￣", "fullwidth macron"],
        ["、", "ideographic comma"],
        ["。", "ideographic full stop"],
        ["·", "middle dot"],
        ["‥", "two dot leader"],
        ["…", "horizontal ellipsis"],
        ["¨", "diaeresis"],
        ["〃", "ditto mark"],
        ["\u00ad", "소프트 하이픈 선택적 줄바꿈 soft hyphen"],
        ["―", "horizontal bar"],
        ["∥", "parallel to"],
        ["＼", "fullwidth reverse solidus"],
        ["∼", "tilde operator"],
        ["´", "acute accent"],
        ["～", "fullwidth tilde"],
        ["ˇ", "caron"],
        ["˘", "breve"],
        ["˝", "double acute accent"],
        ["˚", "ring above"],
        ["˙", "dot above"],
        ["¸", "cedilla"],
        ["˛", "ogonek"],
        ["¡", "inverted exclamation mark"],
        ["¿", "inverted question mark"],
        ["ː", "modifier letter triangular colon"],
    ] },
    { key: "ㄴ", category: "brackets", keywords: "니은 괄호 따옴표 brackets quotes", characters: [
        ["＂", "fullwidth quotation mark"],
        ["（", "fullwidth left parenthesis"],
        ["）", "fullwidth right parenthesis"],
        ["［", "fullwidth left square bracket"],
        ["］", "fullwidth right square bracket"],
        ["｛", "fullwidth left curly bracket"],
        ["｝", "fullwidth right curly bracket"],
        ["‘", "left single quotation mark"],
        ["’", "right single quotation mark"],
        ["“", "left double quotation mark"],
        ["”", "right double quotation mark"],
        ["〔", "left tortoise shell bracket"],
        ["〕", "right tortoise shell bracket"],
        ["〈", "left angle bracket"],
        ["〉", "right angle bracket"],
        ["《", "left double angle bracket"],
        ["》", "right double angle bracket"],
        ["「", "left corner bracket"],
        ["」", "right corner bracket"],
        ["『", "left white corner bracket"],
        ["』", "right white corner bracket"],
        ["【", "left black lenticular bracket"],
        ["】", "right black lenticular bracket"],
    ] },
    { key: "ㄷ", category: "math", keywords: "디귿 수학 연산 math operators", characters: [
        ["＋", "fullwidth plus sign"],
        ["－", "fullwidth hyphen-minus"],
        ["＜", "fullwidth less-than sign"],
        ["＝", "fullwidth equals sign"],
        ["＞", "fullwidth greater-than sign"],
        ["±", "plus-minus sign"],
        ["×", "multiplication sign"],
        ["÷", "division sign"],
        ["≠", "not equal to"],
        ["≤", "less-than or equal to"],
        ["≥", "greater-than or equal to"],
        ["∞", "infinity"],
        ["∴", "그러므로 therefore"],
        ["♂", "male sign"],
        ["♀", "female sign"],
        ["∠", "각도 angle"],
        ["⊥", "수직 up tack"],
        ["⌒", "arc"],
        ["∂", "partial differential"],
        ["∇", "nabla"],
        ["≡", "identical to"],
        ["≒", "approximately equal to or the image of"],
        ["≪", "much less-than"],
        ["≫", "much greater-than"],
        ["√", "square root"],
        ["∽", "reversed tilde"],
        ["∝", "비례 proportional to"],
        ["∵", "왜냐하면 because"],
        ["∫", "integral"],
        ["∬", "double integral"],
        ["∈", "원소 element of"],
        ["∋", "contains as member"],
        ["⊆", "subset of or equal to"],
        ["⊇", "superset of or equal to"],
        ["⊂", "subset of"],
        ["⊃", "superset of"],
        ["∪", "합집합 union"],
        ["∩", "교집합 intersection"],
        ["∧", "logical and"],
        ["∨", "logical or"],
        ["￢", "fullwidth not sign"],
        ["⇒", "rightwards double arrow"],
        ["⇔", "left right double arrow"],
        ["∀", "for all"],
        ["∃", "there exists"],
        ["∮", "contour integral"],
        ["∑", "n-ary summation"],
        ["∏", "n-ary product"],
    ] },
    { key: "ㄹ", category: "units", keywords: "리을 단위 통화 units currency", characters: [
        ["＄", "fullwidth dollar sign"],
        ["％", "fullwidth percent sign"],
        ["￦", "fullwidth won sign"],
        ["Ｆ", "fullwidth latin capital letter f"],
        ["′", "prime"],
        ["″", "double prime"],
        ["℃", "섭씨 degree celsius"],
        ["Å", "옹스트롬 angstrom sign"],
        ["￠", "fullwidth cent sign"],
        ["￡", "fullwidth pound sign"],
        ["￥", "fullwidth yen sign"],
        ["¤", "currency sign"],
        ["℉", "화씨 degree fahrenheit"],
        ["‰", "per mille sign"],
        ["€", "euro sign"],
        ["㎕", "square mu l"],
        ["㎖", "밀리리터 square ml"],
        ["㎗", "square dl"],
        ["ℓ", "리터 script small l"],
        ["㎘", "square kl"],
        ["㏄", "square cc"],
        ["㎣", "square mm cubed"],
        ["㎤", "square cm cubed"],
        ["㎥", "세제곱미터 square m cubed"],
        ["㎦", "square km cubed"],
        ["㎙", "square fm"],
        ["㎚", "square nm"],
        ["㎛", "square mu m"],
        ["㎜", "밀리미터 square mm"],
        ["㎝", "센티미터 square cm"],
        ["㎞", "킬로미터 square km"],
        ["㎟", "square mm squared"],
        ["㎠", "제곱센티미터 square cm squared"],
        ["㎡", "제곱미터 square m squared"],
        ["㎢", "제곱킬로미터 square km squared"],
        ["㏊", "square ha"],
        ["㎍", "square mu g"],
        ["㎎", "밀리그램 square mg"],
        ["㎏", "킬로그램 square kg"],
        ["㏏", "square kt"],
        ["㎈", "square cal"],
        ["㎉", "square kcal"],
        ["㏈", "square db"],
        ["㎧", "square m over s"],
        ["㎨", "square m over s squared"],
        ["㎰", "square ps"],
        ["㎱", "square ns"],
        ["㎲", "square mu s"],
        ["㎳", "square ms"],
        ["㎴", "square pv"],
        ["㎵", "square nv"],
        ["㎶", "square mu v"],
        ["㎷", "square mv"],
        ["㎸", "square kv"],
        ["㎹", "square mv mega"],
        ["㎀", "square pa amps"],
        ["㎁", "square na"],
        ["㎂", "square mu a"],
        ["㎃", "square ma"],
        ["㎄", "square ka"],
        ["㎺", "square pw"],
        ["㎻", "square nw"],
        ["㎼", "square mu w"],
        ["㎽", "square mw"],
        ["㎾", "square kw"],
        ["㎿", "square mw mega"],
        ["㎐", "square hz"],
        ["㎑", "square khz"],
        ["㎒", "square mhz"],
        ["㎓", "square ghz"],
        ["㎔", "square thz"],
        ["Ω", "옴 ohm sign"],
        ["㏀", "square k ohm"],
        ["㏁", "square m ohm"],
        ["㎊", "square pf"],
        ["㎋", "square nf"],
        ["㎌", "square mu f"],
        ["㏖", "square mol"],
        ["㏅", "square cd"],
        ["㎭", "square rad"],
        ["㎮", "square rad over s"],
        ["㎯", "square rad over s squared"],
        ["㏛", "square sr"],
        ["㎩", "square pa"],
        ["㎪", "square kpa"],
        ["㎫", "square mpa"],
        ["㎬", "square gpa"],
        ["㏝", "square wb"],
        ["㏐", "square lm"],
        ["㏓", "square lx"],
        ["㏃", "square bq"],
        ["㏉", "square gy"],
        ["㏜", "square sv"],
        ["㏆", "square c over kg"],
    ] },
    { key: "ㅁ", category: "symbols", keywords: "미음 도형 기호 화살표 symbols shapes arrows", characters: [
        ["＃", "fullwidth number sign"],
        ["＆", "fullwidth ampersand"],
        ["＊", "fullwidth asterisk"],
        ["＠", "fullwidth commercial at"],
        ["§", "section sign"],
        ["※", "reference mark"],
        ["☆", "white star"],
        ["★", "black star"],
        ["○", "white circle"],
        ["●", "black circle"],
        ["◎", "bullseye"],
        ["◇", "white diamond"],
        ["◆", "black diamond"],
        ["□", "white square"],
        ["■", "black square"],
        ["△", "white up-pointing triangle"],
        ["▲", "black up-pointing triangle"],
        ["▽", "white down-pointing triangle"],
        ["▼", "black down-pointing triangle"],
        ["→", "rightwards arrow"],
        ["←", "leftwards arrow"],
        ["↑", "upwards arrow"],
        ["↓", "downwards arrow"],
        ["↔", "left right arrow"],
        ["〓", "geta mark"],
        ["◁", "white left-pointing triangle"],
        ["◀", "black left-pointing triangle"],
        ["▷", "white right-pointing triangle"],
        ["▶", "black right-pointing triangle"],
        ["♤", "빈 스페이드 white spade suit"],
        ["♠", "black spade suit"],
        ["♡", "빈 하트 white heart suit"],
        ["♥", "black heart suit"],
        ["♧", "빈 클로버 white club suit"],
        ["♣", "black club suit"],
        ["⊙", "circled dot operator"],
        ["◈", "white diamond containing black small diamond"],
        ["▣", "white square containing black small square"],
        ["◐", "circle with left half black"],
        ["◑", "circle with right half black"],
        ["▒", "medium shade"],
        ["▤", "square with horizontal fill"],
        ["▥", "square with vertical fill"],
        ["▨", "square with upper right to lower left fill"],
        ["▧", "square with upper left to lower right fill"],
        ["▦", "square with orthogonal crosshatch fill"],
        ["▩", "square with diagonal crosshatch fill"],
        ["♨", "온천 hot springs"],
        ["☏", "전화 white telephone"],
        ["☎", "전화 black telephone"],
        ["☜", "왼쪽 손가락 white left pointing index"],
        ["☞", "오른쪽 손가락 white right pointing index"],
        ["¶", "pilcrow sign"],
        ["†", "dagger"],
        ["‡", "double dagger"],
        ["↕", "up down arrow"],
        ["↗", "north east arrow"],
        ["↙", "south west arrow"],
        ["↖", "north west arrow"],
        ["↘", "south east arrow"],
        ["♭", "내림표 플랫 music flat sign"],
        ["♩", "사분음표 quarter note"],
        ["♪", "eighth note"],
        ["♬", "연결된 십육분음표 beamed sixteenth notes"],
        ["㉿", "한국 산업 규격 korean standard symbol"],
        ["㈜", "주식회사 parenthesized hangul cieuc u"],
        ["№", "번호 numero sign"],
        ["㏇", "square co"],
        ["™", "trade mark sign"],
        ["㏂", "square am"],
        ["㏘", "square pm"],
        ["℡", "telephone sign"],
        ["®", "registered sign"],
        ["ª", "feminine ordinal indicator"],
        ["º", "masculine ordinal indicator"],
        ["㉾", "우편번호 circled hangul ieung u"],
    ] },
    { key: "ㅂ", category: "boxDrawing", keywords: "비읍 선 테두리 box drawing", characters: [
        ["─", "box drawings light horizontal"],
        ["│", "box drawings light vertical"],
        ["┌", "box drawings light down and right"],
        ["┐", "box drawings light down and left"],
        ["┘", "box drawings light up and left"],
        ["└", "box drawings light up and right"],
        ["├", "box drawings light vertical and right"],
        ["┬", "box drawings light down and horizontal"],
        ["┤", "box drawings light vertical and left"],
        ["┴", "box drawings light up and horizontal"],
        ["┼", "box drawings light vertical and horizontal"],
        ["━", "box drawings heavy horizontal"],
        ["┃", "box drawings heavy vertical"],
        ["┏", "box drawings heavy down and right"],
        ["┓", "box drawings heavy down and left"],
        ["┛", "box drawings heavy up and left"],
        ["┗", "box drawings heavy up and right"],
        ["┣", "box drawings heavy vertical and right"],
        ["┳", "box drawings heavy down and horizontal"],
        ["┫", "box drawings heavy vertical and left"],
        ["┻", "box drawings heavy up and horizontal"],
        ["╋", "box drawings heavy vertical and horizontal"],
        ["┠", "box drawings vertical heavy and right light"],
        ["┯", "box drawings down light and horizontal heavy"],
        ["┨", "box drawings vertical heavy and left light"],
        ["┷", "box drawings up light and horizontal heavy"],
        ["┿", "box drawings vertical light and horizontal heavy"],
        ["┝", "box drawings vertical light and right heavy"],
        ["┰", "box drawings down heavy and horizontal light"],
        ["┥", "box drawings vertical light and left heavy"],
        ["┸", "box drawings up heavy and horizontal light"],
        ["╂", "box drawings vertical heavy and horizontal light"],
        ["┒", "box drawings down heavy and left light"],
        ["┑", "box drawings down light and left heavy"],
        ["┚", "box drawings up heavy and left light"],
        ["┙", "box drawings up light and left heavy"],
        ["┖", "box drawings up heavy and right light"],
        ["┕", "box drawings up light and right heavy"],
        ["┎", "box drawings down heavy and right light"],
        ["┍", "box drawings down light and right heavy"],
        ["┞", "box drawings up heavy and right down light"],
        ["┟", "box drawings down heavy and right up light"],
        ["┡", "box drawings down light and right up heavy"],
        ["┢", "box drawings up light and right down heavy"],
        ["┦", "box drawings up heavy and left down light"],
        ["┧", "box drawings down heavy and left up light"],
        ["┩", "box drawings down light and left up heavy"],
        ["┪", "box drawings up light and left down heavy"],
        ["┭", "box drawings left heavy and right down light"],
        ["┮", "box drawings right heavy and left down light"],
        ["┱", "box drawings right light and left down heavy"],
        ["┲", "box drawings left light and right down heavy"],
        ["┵", "box drawings left heavy and right up light"],
        ["┶", "box drawings right heavy and left up light"],
        ["┹", "box drawings right light and left up heavy"],
        ["┺", "box drawings left light and right up heavy"],
        ["┽", "box drawings left heavy and right vertical light"],
        ["┾", "box drawings right heavy and left vertical light"],
        ["╀", "box drawings up heavy and down horizontal light"],
        ["╁", "box drawings down heavy and up horizontal light"],
        ["╃", "box drawings left up heavy and right down light"],
        ["╄", "box drawings right up heavy and left down light"],
        ["╅", "box drawings left down heavy and right up light"],
        ["╆", "box drawings right down heavy and left up light"],
        ["╇", "box drawings down light and up horizontal heavy"],
        ["╈", "box drawings up light and down horizontal heavy"],
        ["╉", "box drawings right light and left vertical heavy"],
        ["╊", "box drawings left light and right vertical heavy"],
    ] },
    { key: "ㅅ", category: "enclosedHangul", keywords: "시옷 원문자 괄호 한글 enclosed hangul", characters: [
        ["㉠", "circled hangul kiyeok"],
        ["㉡", "circled hangul nieun"],
        ["㉢", "circled hangul tikeut"],
        ["㉣", "circled hangul rieul"],
        ["㉤", "circled hangul mieum"],
        ["㉥", "circled hangul pieup"],
        ["㉦", "circled hangul sios"],
        ["㉧", "circled hangul ieung"],
        ["㉨", "circled hangul cieuc"],
        ["㉩", "circled hangul chieuch"],
        ["㉪", "circled hangul khieukh"],
        ["㉫", "circled hangul thieuth"],
        ["㉬", "circled hangul phieuph"],
        ["㉭", "circled hangul hieuh"],
        ["㉮", "circled hangul kiyeok a"],
        ["㉯", "circled hangul nieun a"],
        ["㉰", "circled hangul tikeut a"],
        ["㉱", "circled hangul rieul a"],
        ["㉲", "circled hangul mieum a"],
        ["㉳", "circled hangul pieup a"],
        ["㉴", "circled hangul sios a"],
        ["㉵", "circled hangul ieung a"],
        ["㉶", "circled hangul cieuc a"],
        ["㉷", "circled hangul chieuch a"],
        ["㉸", "circled hangul khieukh a"],
        ["㉹", "circled hangul thieuth a"],
        ["㉺", "circled hangul phieuph a"],
        ["㉻", "circled hangul hieuh a"],
        ["㈀", "parenthesized hangul kiyeok"],
        ["㈁", "parenthesized hangul nieun"],
        ["㈂", "parenthesized hangul tikeut"],
        ["㈃", "parenthesized hangul rieul"],
        ["㈄", "parenthesized hangul mieum"],
        ["㈅", "parenthesized hangul pieup"],
        ["㈆", "parenthesized hangul sios"],
        ["㈇", "parenthesized hangul ieung"],
        ["㈈", "parenthesized hangul cieuc"],
        ["㈉", "parenthesized hangul chieuch"],
        ["㈊", "parenthesized hangul khieukh"],
        ["㈋", "parenthesized hangul thieuth"],
        ["㈌", "parenthesized hangul phieuph"],
        ["㈍", "parenthesized hangul hieuh"],
        ["㈎", "parenthesized hangul kiyeok a"],
        ["㈏", "parenthesized hangul nieun a"],
        ["㈐", "parenthesized hangul tikeut a"],
        ["㈑", "parenthesized hangul rieul a"],
        ["㈒", "parenthesized hangul mieum a"],
        ["㈓", "parenthesized hangul pieup a"],
        ["㈔", "parenthesized hangul sios a"],
        ["㈕", "parenthesized hangul ieung a"],
        ["㈖", "parenthesized hangul cieuc a"],
        ["㈗", "parenthesized hangul chieuch a"],
        ["㈘", "parenthesized hangul khieukh a"],
        ["㈙", "parenthesized hangul thieuth a"],
        ["㈚", "parenthesized hangul phieuph a"],
        ["㈛", "parenthesized hangul hieuh a"],
    ] },
    { key: "ㅇ", category: "enclosedAlphanumeric", keywords: "이응 원문자 괄호 숫자 영문 enclosed alphanumeric", characters: [
        ["ⓐ", "circled latin small letter a"],
        ["ⓑ", "circled latin small letter b"],
        ["ⓒ", "circled latin small letter c"],
        ["ⓓ", "circled latin small letter d"],
        ["ⓔ", "circled latin small letter e"],
        ["ⓕ", "circled latin small letter f"],
        ["ⓖ", "circled latin small letter g"],
        ["ⓗ", "circled latin small letter h"],
        ["ⓘ", "circled latin small letter i"],
        ["ⓙ", "circled latin small letter j"],
        ["ⓚ", "circled latin small letter k"],
        ["ⓛ", "circled latin small letter l"],
        ["ⓜ", "circled latin small letter m"],
        ["ⓝ", "circled latin small letter n"],
        ["ⓞ", "circled latin small letter o"],
        ["ⓟ", "circled latin small letter p"],
        ["ⓠ", "circled latin small letter q"],
        ["ⓡ", "circled latin small letter r"],
        ["ⓢ", "circled latin small letter s"],
        ["ⓣ", "circled latin small letter t"],
        ["ⓤ", "circled latin small letter u"],
        ["ⓥ", "circled latin small letter v"],
        ["ⓦ", "circled latin small letter w"],
        ["ⓧ", "circled latin small letter x"],
        ["ⓨ", "circled latin small letter y"],
        ["ⓩ", "circled latin small letter z"],
        ["①", "원문자 1 circled digit one"],
        ["②", "원문자 2 circled digit two"],
        ["③", "원문자 3 circled digit three"],
        ["④", "원문자 4 circled digit four"],
        ["⑤", "원문자 5 circled digit five"],
        ["⑥", "원문자 6 circled digit six"],
        ["⑦", "원문자 7 circled digit seven"],
        ["⑧", "원문자 8 circled digit eight"],
        ["⑨", "원문자 9 circled digit nine"],
        ["⑩", "원문자 10 circled number ten"],
        ["⑪", "원문자 11 circled number eleven"],
        ["⑫", "원문자 12 circled number twelve"],
        ["⑬", "원문자 13 circled number thirteen"],
        ["⑭", "원문자 14 circled number fourteen"],
        ["⑮", "원문자 15 circled number fifteen"],
        ["⒜", "parenthesized latin small letter a"],
        ["⒝", "parenthesized latin small letter b"],
        ["⒞", "parenthesized latin small letter c"],
        ["⒟", "parenthesized latin small letter d"],
        ["⒠", "parenthesized latin small letter e"],
        ["⒡", "parenthesized latin small letter f"],
        ["⒢", "parenthesized latin small letter g"],
        ["⒣", "parenthesized latin small letter h"],
        ["⒤", "parenthesized latin small letter i"],
        ["⒥", "parenthesized latin small letter j"],
        ["⒦", "parenthesized latin small letter k"],
        ["⒧", "parenthesized latin small letter l"],
        ["⒨", "parenthesized latin small letter m"],
        ["⒩", "parenthesized latin small letter n"],
        ["⒪", "parenthesized latin small letter o"],
        ["⒫", "parenthesized latin small letter p"],
        ["⒬", "parenthesized latin small letter q"],
        ["⒭", "parenthesized latin small letter r"],
        ["⒮", "parenthesized latin small letter s"],
        ["⒯", "parenthesized latin small letter t"],
        ["⒰", "parenthesized latin small letter u"],
        ["⒱", "parenthesized latin small letter v"],
        ["⒲", "parenthesized latin small letter w"],
        ["⒳", "parenthesized latin small letter x"],
        ["⒴", "parenthesized latin small letter y"],
        ["⒵", "parenthesized latin small letter z"],
        ["⑴", "괄호 숫자 1 parenthesized digit one"],
        ["⑵", "괄호 숫자 2 parenthesized digit two"],
        ["⑶", "괄호 숫자 3 parenthesized digit three"],
        ["⑷", "괄호 숫자 4 parenthesized digit four"],
        ["⑸", "괄호 숫자 5 parenthesized digit five"],
        ["⑹", "괄호 숫자 6 parenthesized digit six"],
        ["⑺", "괄호 숫자 7 parenthesized digit seven"],
        ["⑻", "괄호 숫자 8 parenthesized digit eight"],
        ["⑼", "괄호 숫자 9 parenthesized digit nine"],
        ["⑽", "괄호 숫자 10 parenthesized number ten"],
        ["⑾", "괄호 숫자 11 parenthesized number eleven"],
        ["⑿", "괄호 숫자 12 parenthesized number twelve"],
        ["⒀", "괄호 숫자 13 parenthesized number thirteen"],
        ["⒁", "괄호 숫자 14 parenthesized number fourteen"],
        ["⒂", "괄호 숫자 15 parenthesized number fifteen"],
    ] },
    { key: "ㅈ", category: "numbers", keywords: "지읒 전각 숫자 로마 숫자 roman numbers", characters: [
        ["０", "fullwidth digit zero"],
        ["１", "fullwidth digit one"],
        ["２", "fullwidth digit two"],
        ["３", "fullwidth digit three"],
        ["４", "fullwidth digit four"],
        ["５", "fullwidth digit five"],
        ["６", "fullwidth digit six"],
        ["７", "fullwidth digit seven"],
        ["８", "fullwidth digit eight"],
        ["９", "fullwidth digit nine"],
        ["ⅰ", "small roman numeral one"],
        ["ⅱ", "small roman numeral two"],
        ["ⅲ", "small roman numeral three"],
        ["ⅳ", "small roman numeral four"],
        ["ⅴ", "small roman numeral five"],
        ["ⅵ", "small roman numeral six"],
        ["ⅶ", "small roman numeral seven"],
        ["ⅷ", "small roman numeral eight"],
        ["ⅸ", "small roman numeral nine"],
        ["ⅹ", "small roman numeral ten"],
        ["Ⅰ", "roman numeral one"],
        ["Ⅱ", "roman numeral two"],
        ["Ⅲ", "roman numeral three"],
        ["Ⅳ", "roman numeral four"],
        ["Ⅴ", "roman numeral five"],
        ["Ⅵ", "roman numeral six"],
        ["Ⅶ", "roman numeral seven"],
        ["Ⅷ", "roman numeral eight"],
        ["Ⅸ", "roman numeral nine"],
        ["Ⅹ", "roman numeral ten"],
    ] },
    { key: "ㅊ", category: "fractions", keywords: "치읓 분수 위첨자 아래첨자 fractions superscript subscript", characters: [
        ["½", "vulgar fraction one half"],
        ["⅓", "vulgar fraction one third"],
        ["⅔", "vulgar fraction two thirds"],
        ["¼", "vulgar fraction one quarter"],
        ["¾", "vulgar fraction three quarters"],
        ["⅛", "vulgar fraction one eighth"],
        ["⅜", "vulgar fraction three eighths"],
        ["⅝", "vulgar fraction five eighths"],
        ["⅞", "vulgar fraction seven eighths"],
        ["¹", "superscript one"],
        ["²", "superscript two"],
        ["³", "superscript three"],
        ["⁴", "superscript four"],
        ["ⁿ", "superscript latin small letter n"],
        ["₁", "subscript one"],
        ["₂", "subscript two"],
        ["₃", "subscript three"],
        ["₄", "subscript four"],
    ] },
    { key: "ㅋ", category: "hangul", keywords: "키읔 한글 자음 모음 hangul jamo", characters: [
        ["ㄱ", "hangul letter kiyeok"],
        ["ㄲ", "hangul letter ssangkiyeok"],
        ["ㄳ", "hangul letter kiyeok-sios"],
        ["ㄴ", "hangul letter nieun"],
        ["ㄵ", "hangul letter nieun-cieuc"],
        ["ㄶ", "hangul letter nieun-hieuh"],
        ["ㄷ", "hangul letter tikeut"],
        ["ㄸ", "hangul letter ssangtikeut"],
        ["ㄹ", "hangul letter rieul"],
        ["ㄺ", "hangul letter rieul-kiyeok"],
        ["ㄻ", "hangul letter rieul-mieum"],
        ["ㄼ", "hangul letter rieul-pieup"],
        ["ㄽ", "hangul letter rieul-sios"],
        ["ㄾ", "hangul letter rieul-thieuth"],
        ["ㄿ", "hangul letter rieul-phieuph"],
        ["ㅀ", "hangul letter rieul-hieuh"],
        ["ㅁ", "hangul letter mieum"],
        ["ㅂ", "hangul letter pieup"],
        ["ㅃ", "hangul letter ssangpieup"],
        ["ㅄ", "hangul letter pieup-sios"],
        ["ㅅ", "hangul letter sios"],
        ["ㅆ", "hangul letter ssangsios"],
        ["ㅇ", "hangul letter ieung"],
        ["ㅈ", "hangul letter cieuc"],
        ["ㅉ", "hangul letter ssangcieuc"],
        ["ㅊ", "hangul letter chieuch"],
        ["ㅋ", "hangul letter khieukh"],
        ["ㅌ", "hangul letter thieuth"],
        ["ㅍ", "hangul letter phieuph"],
        ["ㅎ", "hangul letter hieuh"],
        ["ㅏ", "hangul letter a"],
        ["ㅐ", "hangul letter ae"],
        ["ㅑ", "hangul letter ya"],
        ["ㅒ", "hangul letter yae"],
        ["ㅓ", "hangul letter eo"],
        ["ㅔ", "hangul letter e"],
        ["ㅕ", "hangul letter yeo"],
        ["ㅖ", "hangul letter ye"],
        ["ㅗ", "hangul letter o"],
        ["ㅘ", "hangul letter wa"],
        ["ㅙ", "hangul letter wae"],
        ["ㅚ", "hangul letter oe"],
        ["ㅛ", "hangul letter yo"],
        ["ㅜ", "hangul letter u"],
        ["ㅝ", "hangul letter weo"],
        ["ㅞ", "hangul letter we"],
        ["ㅟ", "hangul letter wi"],
        ["ㅠ", "hangul letter yu"],
        ["ㅡ", "hangul letter eu"],
        ["ㅢ", "hangul letter yi"],
        ["ㅣ", "hangul letter i"],
    ] },
    { key: "ㅌ", category: "oldHangul", keywords: "티읕 옛한글 고어 old hangul", characters: [
        ["ㅥ", "hangul letter ssangnieun"],
        ["ㅦ", "hangul letter nieun-tikeut"],
        ["ㅧ", "hangul letter nieun-sios"],
        ["ㅨ", "hangul letter nieun-pansios"],
        ["ㅩ", "hangul letter rieul-kiyeok-sios"],
        ["ㅪ", "hangul letter rieul-tikeut"],
        ["ㅫ", "hangul letter rieul-pieup-sios"],
        ["ㅬ", "hangul letter rieul-pansios"],
        ["ㅭ", "hangul letter rieul-yeorinhieuh"],
        ["ㅮ", "hangul letter mieum-pieup"],
        ["ㅯ", "hangul letter mieum-sios"],
        ["ㅰ", "hangul letter mieum-pansios"],
        ["ㅱ", "hangul letter kapyeounmieum"],
        ["ㅲ", "hangul letter pieup-kiyeok"],
        ["ㅳ", "hangul letter pieup-tikeut"],
        ["ㅴ", "hangul letter pieup-sios-kiyeok"],
        ["ㅵ", "hangul letter pieup-sios-tikeut"],
        ["ㅶ", "hangul letter pieup-cieuc"],
        ["ㅷ", "hangul letter pieup-thieuth"],
        ["ㅸ", "hangul letter kapyeounpieup"],
        ["ㅹ", "hangul letter kapyeounssangpieup"],
        ["ㅺ", "hangul letter sios-kiyeok"],
        ["ㅻ", "hangul letter sios-nieun"],
        ["ㅼ", "hangul letter sios-tikeut"],
        ["ㅽ", "hangul letter sios-pieup"],
        ["ㅾ", "hangul letter sios-cieuc"],
        ["ㅿ", "반시옷 hangul letter pansios"],
        ["ㆀ", "hangul letter ssangieung"],
        ["ㆁ", "옛이응 hangul letter yesieung"],
        ["ㆂ", "hangul letter yesieung-sios"],
        ["ㆃ", "hangul letter yesieung-pansios"],
        ["ㆄ", "hangul letter kapyeounphieuph"],
        ["ㆅ", "hangul letter ssanghieuh"],
        ["ㆆ", "여린히읗 hangul letter yeorinhieuh"],
        ["ㆇ", "hangul letter yo-ya"],
        ["ㆈ", "hangul letter yo-yae"],
        ["ㆉ", "hangul letter yo-i"],
        ["ㆊ", "hangul letter yu-yeo"],
        ["ㆋ", "hangul letter yu-ye"],
        ["ㆌ", "hangul letter yu-i"],
        ["ㆍ", "아래아 hangul letter araea"],
        ["ㆎ", "hangul letter araeae"],
    ] },
    { key: "ㅍ", category: "fullwidthLatin", keywords: "피읖 전각 영문 fullwidth latin", characters: [
        ["Ａ", "fullwidth latin capital letter a"],
        ["Ｂ", "fullwidth latin capital letter b"],
        ["Ｃ", "fullwidth latin capital letter c"],
        ["Ｄ", "fullwidth latin capital letter d"],
        ["Ｅ", "fullwidth latin capital letter e"],
        ["Ｆ", "fullwidth latin capital letter f"],
        ["Ｇ", "fullwidth latin capital letter g"],
        ["Ｈ", "fullwidth latin capital letter h"],
        ["Ｉ", "fullwidth latin capital letter i"],
        ["Ｊ", "fullwidth latin capital letter j"],
        ["Ｋ", "fullwidth latin capital letter k"],
        ["Ｌ", "fullwidth latin capital letter l"],
        ["Ｍ", "fullwidth latin capital letter m"],
        ["Ｎ", "fullwidth latin capital letter n"],
        ["Ｏ", "fullwidth latin capital letter o"],
        ["Ｐ", "fullwidth latin capital letter p"],
        ["Ｑ", "fullwidth latin capital letter q"],
        ["Ｒ", "fullwidth latin capital letter r"],
        ["Ｓ", "fullwidth latin capital letter s"],
        ["Ｔ", "fullwidth latin capital letter t"],
        ["Ｕ", "fullwidth latin capital letter u"],
        ["Ｖ", "fullwidth latin capital letter v"],
        ["Ｗ", "fullwidth latin capital letter w"],
        ["Ｘ", "fullwidth latin capital letter x"],
        ["Ｙ", "fullwidth latin capital letter y"],
        ["Ｚ", "fullwidth latin capital letter z"],
        ["ａ", "fullwidth latin small letter a"],
        ["ｂ", "fullwidth latin small letter b"],
        ["ｃ", "fullwidth latin small letter c"],
        ["ｄ", "fullwidth latin small letter d"],
        ["ｅ", "fullwidth latin small letter e"],
        ["ｆ", "fullwidth latin small letter f"],
        ["ｇ", "fullwidth latin small letter g"],
        ["ｈ", "fullwidth latin small letter h"],
        ["ｉ", "fullwidth latin small letter i"],
        ["ｊ", "fullwidth latin small letter j"],
        ["ｋ", "fullwidth latin small letter k"],
        ["ｌ", "fullwidth latin small letter l"],
        ["ｍ", "fullwidth latin small letter m"],
        ["ｎ", "fullwidth latin small letter n"],
        ["ｏ", "fullwidth latin small letter o"],
        ["ｐ", "fullwidth latin small letter p"],
        ["ｑ", "fullwidth latin small letter q"],
        ["ｒ", "fullwidth latin small letter r"],
        ["ｓ", "fullwidth latin small letter s"],
        ["ｔ", "fullwidth latin small letter t"],
        ["ｕ", "fullwidth latin small letter u"],
        ["ｖ", "fullwidth latin small letter v"],
        ["ｗ", "fullwidth latin small letter w"],
        ["ｘ", "fullwidth latin small letter x"],
        ["ｙ", "fullwidth latin small letter y"],
        ["ｚ", "fullwidth latin small letter z"],
    ] },
    { key: "ㅎ", category: "greek", keywords: "히읗 그리스 문자 greek", characters: [
        ["Α", "greek capital letter alpha"],
        ["Β", "greek capital letter beta"],
        ["Γ", "greek capital letter gamma"],
        ["Δ", "greek capital letter delta"],
        ["Ε", "greek capital letter epsilon"],
        ["Ζ", "greek capital letter zeta"],
        ["Η", "greek capital letter eta"],
        ["Θ", "greek capital letter theta"],
        ["Ι", "greek capital letter iota"],
        ["Κ", "greek capital letter kappa"],
        ["Λ", "greek capital letter lamda"],
        ["Μ", "greek capital letter mu"],
        ["Ν", "greek capital letter nu"],
        ["Ξ", "greek capital letter xi"],
        ["Ο", "greek capital letter omicron"],
        ["Π", "greek capital letter pi"],
        ["Ρ", "greek capital letter rho"],
        ["Σ", "greek capital letter sigma"],
        ["Τ", "greek capital letter tau"],
        ["Υ", "greek capital letter upsilon"],
        ["Φ", "greek capital letter phi"],
        ["Χ", "greek capital letter chi"],
        ["Ψ", "greek capital letter psi"],
        ["Ω", "greek capital letter omega"],
        ["α", "greek small letter alpha"],
        ["β", "greek small letter beta"],
        ["γ", "greek small letter gamma"],
        ["δ", "greek small letter delta"],
        ["ε", "greek small letter epsilon"],
        ["ζ", "greek small letter zeta"],
        ["η", "greek small letter eta"],
        ["θ", "greek small letter theta"],
        ["ι", "greek small letter iota"],
        ["κ", "greek small letter kappa"],
        ["λ", "greek small letter lamda"],
        ["μ", "greek small letter mu"],
        ["ν", "greek small letter nu"],
        ["ξ", "greek small letter xi"],
        ["ο", "greek small letter omicron"],
        ["π", "greek small letter pi"],
        ["ρ", "greek small letter rho"],
        ["σ", "greek small letter sigma"],
        ["τ", "greek small letter tau"],
        ["υ", "greek small letter upsilon"],
        ["φ", "greek small letter phi"],
        ["χ", "greek small letter chi"],
        ["ψ", "greek small letter psi"],
        ["ω", "greek small letter omega"],
    ] },
    { key: "ㄲ", category: "letters", keywords: "쌍기역 라틴 확장 문자 latin letters", characters: [
        ["Æ", "latin capital letter ae"],
        ["Ð", "latin capital letter eth"],
        ["Ħ", "latin capital letter h with stroke"],
        ["Ĳ", "latin capital ligature ij"],
        ["Ŀ", "latin capital letter l with middle dot"],
        ["Ł", "latin capital letter l with stroke"],
        ["Ø", "latin capital letter o with stroke"],
        ["Œ", "latin capital ligature oe"],
        ["Þ", "latin capital letter thorn"],
        ["Ŧ", "latin capital letter t with stroke"],
        ["Ŋ", "latin capital letter eng"],
        ["æ", "latin small letter ae"],
        ["đ", "latin small letter d with stroke"],
        ["ð", "latin small letter eth"],
        ["ħ", "latin small letter h with stroke"],
        ["ı", "latin small letter dotless i"],
        ["ĳ", "latin small ligature ij"],
        ["ĸ", "latin small letter kra"],
        ["ŀ", "latin small letter l with middle dot"],
        ["ł", "latin small letter l with stroke"],
        ["ø", "latin small letter o with stroke"],
        ["œ", "latin small ligature oe"],
        ["ß", "latin small letter sharp s"],
        ["þ", "latin small letter thorn"],
        ["ŧ", "latin small letter t with stroke"],
        ["ŋ", "latin small letter eng"],
        ["ŉ", "latin small letter n preceded by apostrophe"],
    ] },
    { key: "ㄸ", category: "hiragana", keywords: "쌍디귿 일본어 히라가나 japanese hiragana", characters: [
        ["ぁ", "hiragana letter small a"],
        ["あ", "hiragana letter a"],
        ["ぃ", "hiragana letter small i"],
        ["い", "hiragana letter i"],
        ["ぅ", "hiragana letter small u"],
        ["う", "hiragana letter u"],
        ["ぇ", "hiragana letter small e"],
        ["え", "hiragana letter e"],
        ["ぉ", "hiragana letter small o"],
        ["お", "hiragana letter o"],
        ["か", "hiragana letter ka"],
        ["が", "hiragana letter ga"],
        ["き", "hiragana letter ki"],
        ["ぎ", "hiragana letter gi"],
        ["く", "hiragana letter ku"],
        ["ぐ", "hiragana letter gu"],
        ["け", "hiragana letter ke"],
        ["げ", "hiragana letter ge"],
        ["こ", "hiragana letter ko"],
        ["ご", "hiragana letter go"],
        ["さ", "hiragana letter sa"],
        ["ざ", "hiragana letter za"],
        ["し", "hiragana letter si"],
        ["じ", "hiragana letter zi"],
        ["す", "hiragana letter su"],
        ["ず", "hiragana letter zu"],
        ["せ", "hiragana letter se"],
        ["ぜ", "hiragana letter ze"],
        ["そ", "hiragana letter so"],
        ["ぞ", "hiragana letter zo"],
        ["た", "hiragana letter ta"],
        ["だ", "hiragana letter da"],
        ["ち", "hiragana letter ti"],
        ["ぢ", "hiragana letter di"],
        ["っ", "hiragana letter small tu"],
        ["つ", "hiragana letter tu"],
        ["づ", "hiragana letter du"],
        ["て", "hiragana letter te"],
        ["で", "hiragana letter de"],
        ["と", "hiragana letter to"],
        ["ど", "hiragana letter do"],
        ["な", "hiragana letter na"],
        ["に", "hiragana letter ni"],
        ["ぬ", "hiragana letter nu"],
        ["ね", "hiragana letter ne"],
        ["の", "hiragana letter no"],
        ["は", "hiragana letter ha"],
        ["ば", "hiragana letter ba"],
        ["ぱ", "hiragana letter pa"],
        ["ひ", "hiragana letter hi"],
        ["び", "hiragana letter bi"],
        ["ぴ", "hiragana letter pi"],
        ["ふ", "hiragana letter hu"],
        ["ぶ", "hiragana letter bu"],
        ["ぷ", "hiragana letter pu"],
        ["へ", "hiragana letter he"],
        ["べ", "hiragana letter be"],
        ["ぺ", "hiragana letter pe"],
        ["ほ", "hiragana letter ho"],
        ["ぼ", "hiragana letter bo"],
        ["ぽ", "hiragana letter po"],
        ["ま", "hiragana letter ma"],
        ["み", "hiragana letter mi"],
        ["む", "hiragana letter mu"],
        ["め", "hiragana letter me"],
        ["も", "hiragana letter mo"],
        ["ゃ", "hiragana letter small ya"],
        ["や", "hiragana letter ya"],
        ["ゅ", "hiragana letter small yu"],
        ["ゆ", "hiragana letter yu"],
        ["ょ", "hiragana letter small yo"],
        ["よ", "hiragana letter yo"],
        ["ら", "hiragana letter ra"],
        ["り", "hiragana letter ri"],
        ["る", "hiragana letter ru"],
        ["れ", "hiragana letter re"],
        ["ろ", "hiragana letter ro"],
        ["ゎ", "hiragana letter small wa"],
        ["わ", "hiragana letter wa"],
        ["ゐ", "hiragana letter wi"],
        ["ゑ", "hiragana letter we"],
        ["を", "hiragana letter wo"],
        ["ん", "hiragana letter n"],
    ] },
    { key: "ㅃ", category: "katakana", keywords: "쌍비읍 일본어 가타카나 japanese katakana", characters: [
        ["ァ", "katakana letter small a"],
        ["ア", "katakana letter a"],
        ["ィ", "katakana letter small i"],
        ["イ", "katakana letter i"],
        ["ゥ", "katakana letter small u"],
        ["ウ", "katakana letter u"],
        ["ェ", "katakana letter small e"],
        ["エ", "katakana letter e"],
        ["ォ", "katakana letter small o"],
        ["オ", "katakana letter o"],
        ["カ", "katakana letter ka"],
        ["ガ", "katakana letter ga"],
        ["キ", "katakana letter ki"],
        ["ギ", "katakana letter gi"],
        ["ク", "katakana letter ku"],
        ["グ", "katakana letter gu"],
        ["ケ", "katakana letter ke"],
        ["ゲ", "katakana letter ge"],
        ["コ", "katakana letter ko"],
        ["ゴ", "katakana letter go"],
        ["サ", "katakana letter sa"],
        ["ザ", "katakana letter za"],
        ["シ", "katakana letter si"],
        ["ジ", "katakana letter zi"],
        ["ス", "katakana letter su"],
        ["ズ", "katakana letter zu"],
        ["セ", "katakana letter se"],
        ["ゼ", "katakana letter ze"],
        ["ソ", "katakana letter so"],
        ["ゾ", "katakana letter zo"],
        ["タ", "katakana letter ta"],
        ["ダ", "katakana letter da"],
        ["チ", "katakana letter ti"],
        ["ヂ", "katakana letter di"],
        ["ッ", "katakana letter small tu"],
        ["ツ", "katakana letter tu"],
        ["ヅ", "katakana letter du"],
        ["テ", "katakana letter te"],
        ["デ", "katakana letter de"],
        ["ト", "katakana letter to"],
        ["ド", "katakana letter do"],
        ["ナ", "katakana letter na"],
        ["ニ", "katakana letter ni"],
        ["ヌ", "katakana letter nu"],
        ["ネ", "katakana letter ne"],
        ["ノ", "katakana letter no"],
        ["ハ", "katakana letter ha"],
        ["バ", "katakana letter ba"],
        ["パ", "katakana letter pa"],
        ["ヒ", "katakana letter hi"],
        ["ビ", "katakana letter bi"],
        ["ピ", "katakana letter pi"],
        ["フ", "katakana letter hu"],
        ["ブ", "katakana letter bu"],
        ["プ", "katakana letter pu"],
        ["ヘ", "katakana letter he"],
        ["ベ", "katakana letter be"],
        ["ペ", "katakana letter pe"],
        ["ホ", "katakana letter ho"],
        ["ボ", "katakana letter bo"],
        ["ポ", "katakana letter po"],
        ["マ", "katakana letter ma"],
        ["ミ", "katakana letter mi"],
        ["ム", "katakana letter mu"],
        ["メ", "katakana letter me"],
        ["モ", "katakana letter mo"],
        ["ャ", "katakana letter small ya"],
        ["ヤ", "katakana letter ya"],
        ["ュ", "katakana letter small yu"],
        ["ユ", "katakana letter yu"],
        ["ョ", "katakana letter small yo"],
        ["ヨ", "katakana letter yo"],
        ["ラ", "katakana letter ra"],
        ["リ", "katakana letter ri"],
        ["ル", "katakana letter ru"],
        ["レ", "katakana letter re"],
        ["ロ", "katakana letter ro"],
        ["ヮ", "katakana letter small wa"],
        ["ワ", "katakana letter wa"],
        ["ヰ", "katakana letter wi"],
        ["ヱ", "katakana letter we"],
        ["ヲ", "katakana letter wo"],
        ["ン", "katakana letter n"],
        ["ヴ", "katakana letter vu"],
        ["ヵ", "katakana letter small ka"],
        ["ヶ", "katakana letter small ke"],
    ] },
    { key: "ㅆ", category: "cyrillic", keywords: "쌍시옷 러시아어 키릴 문자 russian cyrillic", characters: [
        ["А", "cyrillic capital letter a"],
        ["Б", "cyrillic capital letter be"],
        ["В", "cyrillic capital letter ve"],
        ["Г", "cyrillic capital letter ghe"],
        ["Д", "cyrillic capital letter de"],
        ["Е", "cyrillic capital letter ie"],
        ["Ё", "cyrillic capital letter io"],
        ["Ж", "cyrillic capital letter zhe"],
        ["З", "cyrillic capital letter ze"],
        ["И", "cyrillic capital letter i"],
        ["Й", "cyrillic capital letter short i"],
        ["К", "cyrillic capital letter ka"],
        ["Л", "cyrillic capital letter el"],
        ["М", "cyrillic capital letter em"],
        ["Н", "cyrillic capital letter en"],
        ["О", "cyrillic capital letter o"],
        ["П", "cyrillic capital letter pe"],
        ["Р", "cyrillic capital letter er"],
        ["С", "cyrillic capital letter es"],
        ["Т", "cyrillic capital letter te"],
        ["У", "cyrillic capital letter u"],
        ["Ф", "cyrillic capital letter ef"],
        ["Х", "cyrillic capital letter ha"],
        ["Ц", "cyrillic capital letter tse"],
        ["Ч", "cyrillic capital letter che"],
        ["Ш", "cyrillic capital letter sha"],
        ["Щ", "cyrillic capital letter shcha"],
        ["Ъ", "cyrillic capital letter hard sign"],
        ["Ы", "cyrillic capital letter yeru"],
        ["Ь", "cyrillic capital letter soft sign"],
        ["Э", "cyrillic capital letter e"],
        ["Ю", "cyrillic capital letter yu"],
        ["Я", "cyrillic capital letter ya"],
        ["а", "cyrillic small letter a"],
        ["б", "cyrillic small letter be"],
        ["в", "cyrillic small letter ve"],
        ["г", "cyrillic small letter ghe"],
        ["д", "cyrillic small letter de"],
        ["е", "cyrillic small letter ie"],
        ["ё", "cyrillic small letter io"],
        ["ж", "cyrillic small letter zhe"],
        ["з", "cyrillic small letter ze"],
        ["и", "cyrillic small letter i"],
        ["й", "cyrillic small letter short i"],
        ["к", "cyrillic small letter ka"],
        ["л", "cyrillic small letter el"],
        ["м", "cyrillic small letter em"],
        ["н", "cyrillic small letter en"],
        ["о", "cyrillic small letter o"],
        ["п", "cyrillic small letter pe"],
        ["р", "cyrillic small letter er"],
        ["с", "cyrillic small letter es"],
        ["т", "cyrillic small letter te"],
        ["у", "cyrillic small letter u"],
        ["ф", "cyrillic small letter ef"],
        ["х", "cyrillic small letter ha"],
        ["ц", "cyrillic small letter tse"],
        ["ч", "cyrillic small letter che"],
        ["ш", "cyrillic small letter sha"],
        ["щ", "cyrillic small letter shcha"],
        ["ъ", "cyrillic small letter hard sign"],
        ["ы", "cyrillic small letter yeru"],
        ["ь", "cyrillic small letter soft sign"],
        ["э", "cyrillic small letter e"],
        ["ю", "cyrillic small letter yu"],
        ["я", "cyrillic small letter ya"],
    ] },
];
