import { getCurrentLanguage } from '../../../utils/i18n';

const messages = {
    templates: ['템플릿', 'Templates', 'テンプレート'],
    templateLibraryHint: ['자주 쓰는 전자책 구성을 커서 위치에 삽입하세요. 내 템플릿은 이 컴퓨터에 저장되어 다른 책에서도 사용할 수 있습니다.', 'Insert reusable ebook layouts at the cursor. Your templates are saved on this computer for use in other books.', 'よく使う電子書籍の構成をカーソル位置に挿入できます。自分のテンプレートはこのパソコンに保存され、他の本でも使えます。'],
    templateNew: ['새 사용자 템플릿', 'New custom template', '新規ユーザーテンプレート'],
    templateFromSelection: ['선택한 본문으로 등록', 'Create from selection', '選択した本文から作成'],
    templateFromChapter: ['현재 장으로 등록', 'Create from this chapter', '現在の章から作成'],
    templateSearch: ['템플릿 검색', 'Search templates', 'テンプレートを検索'],
    templateFilter: ['템플릿 분류', 'Template filter', 'テンプレートの種類'],
    templateFilter_all: ['전체', 'All', 'すべて'], templateFilter_builtin: ['기본 제공', 'Built-in', '標準'], templateFilter_custom: ['내 템플릿', 'My templates', '自分のテンプレート'],
    templateList: ['템플릿 목록', 'Template list', 'テンプレート一覧'], templateNoResults: ['해당하는 템플릿이 없습니다.', 'No matching templates.', '該当するテンプレートはありません。'],
    templateDetails: ['템플릿 편집과 미리보기', 'Template editor and preview', 'テンプレートの編集とプレビュー'],
    templateName: ['템플릿 이름', 'Template name', 'テンプレート名'], templateBody: ['템플릿 본문', 'Template content', 'テンプレート本文'], templateFormat: ['템플릿 본문 서식', 'Template formatting', 'テンプレート本文の書式'],
    templateSave: ['템플릿 저장', 'Save template', 'テンプレートを保存'], templateSaved: ['템플릿을 저장했습니다.', 'Template saved.', 'テンプレートを保存しました。'],
    templateDelete: ['템플릿 삭제', 'Delete template', 'テンプレートを削除'], templateDeleted: ['템플릿을 삭제했습니다.', 'Template deleted.', 'テンプレートを削除しました。'],
    templateDeleteConfirm: ['이 템플릿을 삭제할까요? 이미 책에 삽입한 본문과 자료는 유지됩니다.', 'Delete this template? Content and assets already inserted into books are kept.', 'このテンプレートを削除しますか？本に挿入済みの本文と素材は残ります。'],
    templateDiscardConfirm: ['저장하지 않은 템플릿 변경이 있습니다. 변경을 버리고 이동할까요?', 'This template has unsaved changes. Discard them and continue?', 'テンプレートに未保存の変更があります。破棄して続行しますか？'],
    templateBuiltinHint: ['기본 템플릿은 복제하여 수정할 수 있습니다. 안내 문구는 삽입 후 책에 맞게 바꾸세요.', 'Duplicate a built-in template to customize it. Replace its placeholder text after insertion.', '標準テンプレートは複製して編集できます。挿入後、案内文を本の内容に合わせて変更してください。'],
    templateEditHint: ['이름·설명·본문을 편집한 뒤 저장하세요. 수정한 템플릿은 다음 삽입부터 적용됩니다.', 'Edit the name, description and content, then save. Changes apply to future insertions.', '名前・説明・本文を編集して保存してください。変更は次回の挿入から反映されます。'],
    templateInsert: ['본문에 삽입', 'Insert into manuscript', '本文に挿入'],
    templateInsertHint: ['본문의 커서 위치에 삽입합니다. 실행 취소로 되돌릴 수 있습니다.', 'Inserts at the manuscript cursor. You can undo the insertion.', '本文のカーソル位置に挿入します。元に戻す操作で取り消せます。'],
    templateReplaceHint: ['선택한 본문을 이 템플릿으로 바꿉니다. 실행 취소로 되돌릴 수 있습니다.', 'Replaces the selected manuscript content. You can undo the insertion.', '選択した本文をこのテンプレートに置き換えます。元に戻す操作で取り消せます。'],
    templateCssHint: ['본문 서식과 이미지·오디오·개별 지정 글꼴을 함께 저장합니다. 책의 기본 서식과 공통·페이지 CSS는 삽입 대상 책의 설정을 따릅니다.', 'Includes content formatting, images, audio and explicitly applied fonts. Book defaults and common/chapter CSS follow the destination book.', '本文の書式・画像・音声・個別指定フォントを保存します。本の基本書式と共通・章CSSは挿入先の設定に従います。'],
    templateLinksRemoved: ['함께 저장되지 않는 장·위치로 이동하는 링크는 일반 텍스트로 바꿨습니다. 외부 링크와 템플릿 안의 위치 링크는 유지됩니다.', 'Links to chapters or positions outside this template were converted to plain text. External links and anchors inside the template are kept.', 'テンプレート外の章・位置へのリンクは通常のテキストに変更しました。外部リンクとテンプレート内の位置リンクは保持されます。'],
    templateSaveFirst: ['저장한 뒤 삽입할 수 있습니다.', 'Save before inserting.', '保存してから挿入できます。'],
    TEMPLATE_INVALID: ['템플릿 이름과 본문을 확인하세요. 이름은 80자, 설명은 240자까지 입력할 수 있습니다.', 'Check the template name and content. Names allow 80 characters and descriptions 240.', 'テンプレート名と本文を確認してください。名前は80文字、説明は240文字までです。'],
    TEMPLATE_TOO_LARGE: ['템플릿 본문은 서식 포함 1MB까지 저장할 수 있습니다. 더 작은 영역을 선택하세요.', 'Template content supports up to 1 MB including formatting. Select a smaller section.', '書式を含むテンプレート本文は1MBまで保存できます。範囲を小さくしてください。'],
    TEMPLATE_ASSET_LIMIT: ['템플릿 하나에 포함된 자료는 총 32MB까지 저장할 수 있습니다.', 'Assets in one template may total up to 32 MB.', '1つのテンプレートに含める素材は合計32MBまでです。'],
    TEMPLATE_LIMIT: ['템플릿 보관함의 한도에 도달했습니다. 사용하지 않는 템플릿을 삭제하세요. 최대 100개, 본문 16MB, 자료 256MB입니다.', 'The template library is full. Delete unused templates. Limits: 100 templates, 16 MB content and 256 MB assets.', 'テンプレートの保存上限に達しました。不要なものを削除してください。上限は100件、本文16MB、素材256MBです。'],
    TEMPLATE_LIBRARY_INVALID: ['저장된 템플릿 보관함을 읽을 수 없습니다. 기존 파일을 보존했습니다.', 'The saved template library cannot be read. The existing file was preserved.', '保存済みテンプレートを読み込めません。既存ファイルは保持されています。'],
    TEMPLATE_CONFLICT: ['다른 창에서 템플릿이 변경되었습니다. 변경 내용을 확인한 뒤 목록을 새로고침하세요.', 'Templates changed in another window. Review your changes, then reload the list.', '別のウィンドウでテンプレートが変更されました。変更内容を確認して一覧を再読み込みしてください。'],
    TEMPLATE_MISSING: ['템플릿을 찾을 수 없습니다. 목록을 새로고침하세요.', 'Template not found. Reload the list.', 'テンプレートが見つかりません。一覧を再読み込みしてください。'],
    TEMPLATE_NAME_EXISTS: ['같은 이름의 사용자 템플릿이 있습니다. 다른 이름을 입력하세요.', 'A custom template with this name already exists. Choose another name.', '同名のユーザーテンプレートがあります。別の名前を入力してください。'],
    TEMPLATE_SELECTION_REQUIRED: ['템플릿으로 저장할 본문을 먼저 선택하세요.', 'Select manuscript content to save as a template.', 'テンプレートに保存する本文を先に選択してください。'],
    TEMPLATE_INSERT_FAILED: ['이 위치에는 템플릿을 삽입할 수 없습니다. 본문 문단에 커서를 놓고 다시 시도하세요.', 'Cannot insert a template here. Place the cursor in a manuscript paragraph and try again.', 'この位置には挿入できません。本文の段落にカーソルを置いて再試行してください。'],
    zoom: ['화면 확대·축소', 'View zoom', '表示倍率'],
    zoomHint: ['원고·책 편집·미리보기에서 ⌘(Mac) 또는 Ctrl 키를 누르고 위로 스크롤하면 확대, 아래로 스크롤하면 축소합니다. 범위: 50~200%.', 'In Write, Design and Preview, hold ⌘ (Mac) or Ctrl and scroll up to zoom in, down to zoom out. Range: 50–200%.', '原稿・本の編集・プレビューで⌘（Mac）またはCtrlを押しながら上へスクロールすると拡大、下へスクロールすると縮小します。範囲：50〜200%。'],
    previousChapter: ['이전 장', 'Previous chapter', '前の章'], nextChapter: ['다음 장', 'Next chapter', '次の章'],
    scrollPreviousChapter: ['맨 위에서 잠깐 멈춘 뒤 다시 위로 스크롤하면 이전 장으로 이동합니다', 'Pause at the top, then scroll up again for the previous chapter', '先頭でいったん止めてから、もう一度上へスクロールすると前の章に移動します'],
    scrollNextChapter: ['맨 아래에서 잠깐 멈춘 뒤 다시 아래로 스크롤하면 다음 장으로 이동합니다', 'Pause at the bottom, then scroll down again for the next chapter', '末尾でいったん止めてから、もう一度下へスクロールすると次の章に移動します'],
    paragraphIndent: ['문단 들여쓰기', 'Paragraph indentation', '段落のインデント'],
    increaseIndent: ['문단 들여쓰기 늘리기', 'Increase paragraph indent', '段落のインデントを増やす'], decreaseIndent: ['문단 들여쓰기 줄이기', 'Decrease paragraph indent', '段落のインデントを減らす'],
    firstLine: ['첫 줄 들여쓰기·내어쓰기', 'First-line indentation', '最初の行のインデント'],
    firstLineIndent: ['첫 줄 들여쓰기', 'First-line indent', '最初の行を字下げ'], hangingIndent: ['첫 줄 내어쓰기', 'Hanging indent', 'ぶら下げインデント'],
    noFirstLineIndent: ['첫 줄 들여쓰기 없음', 'No first-line indent', '最初の行の字下げなし'], inheritFirstLineIndent: ['첫 줄: 책 스타일 따르기', 'First line: book style', '最初の行：本のスタイル'],
    mixedIndent: ['첫 줄: 여러 설정', 'First line: mixed', '最初の行：複数の設定'],
    paragraphIndentHint: ['선택한 문단에 적용합니다. 문단 들여쓰기는 2em씩 조절하며, 첫 줄 들여쓰기·내어쓰기는 1em입니다. 내어쓰기는 둘째 줄부터 안쪽으로 맞춥니다.', 'Applies to selected paragraphs. Paragraph indentation changes by 2em; first-line and hanging indents use 1em. Hanging indents move subsequent lines inward.', '選択した段落に適用します。段落は2em単位、字下げ・ぶら下げは1emです。ぶら下げは2行目以降を内側に揃えます。'],
    mergeChapters: ['장 합치기', 'Merge chapters', '章を結合'], mergeApply: ['선택한 장 합치기', 'Merge selected chapters', '選択した章を結合'],
    mergeChaptersHint: ['시작 장부터 끝 장까지 책 순서대로 하나의 장으로 합칩니다. 본문·이미지·표·각주·오디오를 유지하며 책 구성 되돌리기로 취소할 수 있습니다.', 'Combine the range into one chapter in book order. Text, images, tables, footnotes and audio are kept. Use Undo book structure to revert.', '開始章から終了章までを本の順序で1つの章に結合します。本文・画像・表・脚注・音声を保持します。本の構成を元に戻す操作で取り消せます。'],
    mergeStart: ['시작 장', 'First chapter', '開始章'], mergeEnd: ['끝 장', 'Last chapter', '終了章'], mergeTitle: ['합친 장 제목', 'Merged chapter title', '結合後の章のタイトル'],
    mergeSelection: ['합칠 장 · 책 순서', 'Chapters to merge · book order', '結合する章・本の順序'],
    mergeKeepTitles: ['두 번째 장부터 기존 장 제목을 본문 제목으로 남기기', 'Keep subsequent chapter titles as body headings', '2番目以降の章のタイトルを本文の見出しとして残す'],
    mergeTocHint: ['목차 포함 여부와 목차 표시 이름은 첫 장의 설정을 사용합니다. 사라지는 장으로 향하는 내부 링크는 합친 본문의 해당 위치로 연결합니다.', 'The first chapter supplies the contents settings. Internal links to removed chapters are redirected to their position in the merged text.', '目次の設定は最初の章を使用します。削除される章への内部リンクは結合した本文内の該当位置に接続します。'],
    mergeCssHint: ['장별 CSS도 순서대로 합칩니다. 합친 CSS는 전체 본문에 적용되어 기존과 모양이 달라질 수 있으며, 우선순위가 같으면 뒤쪽 규칙이 적용됩니다. 합친 뒤 미리보기를 확인하세요.', 'Chapter CSS is combined in order and applies to the entire merged chapter. Appearance may change; later rules win at equal priority. Check the preview after merging.', '章CSSも順序どおり結合され、結合した章全体に適用されます。外観が変わる場合があり、同じ優先順位では後の規則が適用されます。結合後にプレビューを確認してください。'],
    chaptersMerged: ['장을 합쳤습니다. 책 구성 되돌리기로 취소할 수 있습니다.', 'Chapters merged. Use Undo book structure to revert.', '章を結合しました。本の構成を元に戻す操作で取り消せます。'],
    MERGE_RANGE_REQUIRED: ['책 순서대로 두 개 이상의 장을 선택하세요.', 'Choose a range of at least two chapters in book order.', '本の順序で2つ以上の章を選択してください。'],
    MERGE_CSS_TOO_LARGE: ['합친 장 CSS가 10만 자를 초과합니다. 합칠 범위를 줄이거나 CSS를 정리하세요.', 'The merged chapter CSS exceeds 100,000 characters. Merge fewer chapters or simplify the CSS.', '結合した章CSSが10万文字を超えます。章の範囲を減らすかCSSを整理してください。'],
    MERGE_CSS_INVALID: ['중복 요소 ID에 맞춰 CSS를 갱신할 수 없습니다. 장 CSS 오류를 먼저 수정하세요.', 'Cannot update CSS for duplicate element IDs. Fix chapter CSS errors first.', '重複する要素IDに合わせてCSSを更新できません。章CSSのエラーを先に修正してください。'],
    importText: ['TXT 파일 불러오기', 'Import text file', 'テキストを読み込む'], splitChapter: ['커서 위치에서 장 나누기', 'Split chapter at cursor', 'カーソル位置で章を分割'],
    textImportHint: ['TXT 파일의 줄바꿈과 빈 줄을 문단으로 가져옵니다. 최대 50MB, 3,000만 자, 30만 문단까지 지원합니다. 큰 파일은 여러 장으로 나누어 가져옵니다. 글자가 깨지면 인코딩을 변경하세요.', 'Import TXT line breaks and blank lines as paragraphs. Up to 50 MB, 30 million characters and 300,000 paragraphs. Large files are imported as multiple chapters. Change encoding if the text looks garbled.', 'TXTの改行と空行を段落として読み込みます。最大50MB、3,000万文字、30万段落。大きなファイルは複数の章に分けて読み込みます。文字化けする場合は文字コードを変更してください。'],
    textImportSplitHint: ['편집 속도를 위해 문단 경계에서 {count}개의 새 장으로 나눕니다. 줄과 빈 줄은 유지하며, 큰 파일은 커서 위치에 직접 삽입하지 않습니다.', 'The text will be divided at paragraph boundaries into {count} new chapters for responsive editing. Lines and blank lines are kept. Large files cannot be inserted directly at the cursor.', '編集速度を保つため、段落の境界で{count}章に分けます。改行と空行は保持します。大きなファイルはカーソル位置に直接挿入できません。'],
    textNewChapters: ['여러 장으로 나누어 가져오기', 'Import as multiple chapters', '複数の章に分けて読み込む'],
    chooseTextFile: ['TXT 파일 선택', 'Choose TXT file', 'TXTファイルを選択'], textEncoding: ['문자 인코딩', 'Text encoding', '文字コード'], encodingAuto: ['자동 감지', 'Auto detect', '自動判定'],
    textParagraphs: ['문단', 'paragraphs', '段落'], textPreview: ['내용 미리보기 · 처음 4,000자', 'Preview · first 4,000 characters', 'プレビュー・先頭4,000文字'],
    textPlacement: ['불러올 위치', 'Import destination', '読み込み先'], textNewChapter: ['새 장으로 가져오기 · 빈 책은 첫 장에', 'New chapter · use the first chapter in an empty book', '新しい章・空の本は最初の章に'],
    textAtCursor: ['현재 커서 위치에 삽입', 'Insert at current cursor', '現在のカーソル位置に挿入'], importTextApply: ['본문으로 가져오기', 'Import into book', '本文に取り込む'],
    textImported: ['TXT 파일을 가져왔습니다. 책 구성 되돌리기로 취소할 수 있습니다.', 'Text imported. Use Undo book structure to revert.', 'テキストを取り込みました。本の構成を元に戻す操作で取り消せます。'],
    chapterSplit: ['커서 뒤의 본문을 새 장으로 옮겼습니다. 책 구성 되돌리기로 취소할 수 있습니다.', 'Content after the cursor moved to a new chapter. Use Undo book structure to revert.', 'カーソル以降の本文を新しい章に移動しました。本の構成を元に戻す操作で取り消せます。'],
    TEXT_FILE_REQUIRED: ['TXT 파일을 선택하세요.', 'Choose a TXT file.', 'TXTファイルを選択してください。'], TEXT_EMPTY: ['파일에 가져올 본문이 없습니다.', 'The file has no text to import.', '取り込む本文がありません。'],
    TEXT_TOO_LARGE: ['50MB, 3,000만 자 또는 30만 문단 제한을 초과했습니다. 파일을 나누어 가져오세요.', 'The file exceeds 50 MB, 30 million characters or 300,000 paragraphs. Import smaller files.', '50MB、3,000万文字または30万段落を超えています。ファイルを分割して読み込んでください。'],
    TEXT_PARAGRAPH_TOO_LARGE: ['한 줄이 200만 자를 초과합니다. 줄바꿈을 넣어 문단을 나눈 뒤 가져오세요.', 'A single line exceeds 2 million characters. Add line breaks before importing.', '1行が200万文字を超えています。改行を入れてから読み込んでください。'],
    TEXT_IMPORT_CHAPTERS_REQUIRED: ['큰 TXT 파일은 여러 장으로 나누어 가져오세요.', 'Import this large TXT file as multiple chapters.', '大きなTXTファイルは複数の章に分けて読み込んでください。'],
    TEXT_NOT_PLAIN: ['일반 텍스트가 아니거나 지원하지 않는 제어 문자가 있습니다. 파일과 인코딩을 확인하세요.', 'Unsupported control characters or non-text content. Check the file and encoding.', '未対応の制御文字またはテキスト以外の内容です。ファイルと文字コードを確認してください。'],
    TEXT_ENCODING: ['이 인코딩으로 읽을 수 없습니다. 다른 인코딩을 선택하세요.', 'Cannot decode with this encoding. Choose another encoding.', 'この文字コードでは読み込めません。別の文字コードを選択してください。'],
    TEXT_SOURCE_MISSING: ['TXT 파일을 다시 선택하세요.', 'Choose the TXT file again.', 'TXTファイルを選び直してください。'],
    SPLIT_CURSOR_REQUIRED: ['본문의 선택 영역을 해제하고 나눌 위치에 커서를 놓으세요.', 'Clear the selection and place the cursor where the chapter should split.', '選択を解除し、章を分割する位置にカーソルを置いてください。'],
    SPLIT_CONTAINER: ['표·단 내부에서는 장을 나눌 수 없습니다. 앞이나 뒤의 문단에 커서를 놓으세요.', 'Place the cursor in a paragraph before or after the table or columns to split the chapter.', '表・段組みの前後の段落にカーソルを置いて章を分割してください。'],
    SPLIT_EMPTY: ['나눈 양쪽 장에 본문이 남는 위치를 선택하세요.', 'Choose a position that leaves content in both chapters.', '分割後の両方の章に本文が残る位置を選択してください。'],
    CHAPTER_LIMIT: ['책에는 최대 1,000개의 장을 넣을 수 있습니다.', 'A book can contain up to 1,000 chapters.', '1冊に最大1,000章まで作成できます。'],
    CHAPTER_HISTORY_CHANGED: ['이후 변경한 본문이나 장 CSS가 있습니다. 해당 편집을 먼저 되돌린 뒤 책 구성 되돌리기를 실행하세요.', 'Content or chapter CSS has changed since this operation. Undo those edits before restoring the book structure.', 'この操作後に本文または章CSSが変更されています。その編集を元に戻してから本の構成を戻してください。'],
    cssPresets: ['CSS 프리셋', 'CSS presets', 'CSSプリセット'], cssPreset: ['CSS 프리셋', 'CSS preset', 'CSSプリセット'],
    presetLibraryHint: ['내 프리셋은 이 컴퓨터의 앱에 저장되어 다른 책에서도 사용할 수 있습니다. 적용된 CSS는 책에 함께 저장됩니다.', 'Your presets are saved in this app on this computer for use in other books. Applied CSS is saved with the book.', '自分のプリセットはこのパソコンのアプリに保存され、他の本でも使えます。適用したCSSは本に保存されます。'],
    presetRegister: ['프리셋으로 저장', 'Save as preset', 'プリセットとして保存'],
    presetRegisterHint: ['선택한 코드가 있으면 선택 부분만 저장합니다.', 'Saves the selected code, or all CSS if nothing is selected.', 'コードを選択している場合は選択部分だけを保存します。'],
    presetSearch: ['프리셋 검색', 'Search presets', 'プリセットを検索'], presetFilter: ['프리셋 분류', 'Preset filter', 'プリセットの種類'],
    presetFilter_all: ['전체', 'All', 'すべて'], presetFilter_custom: ['내 프리셋', 'My presets', '自分のプリセット'], presetFilter_builtin: ['기본 제공', 'Built-in', '標準'],
    presetBuiltin: ['기본 제공', 'Built-in', '標準'], presetCustom: ['내 프리셋', 'My preset', '自分のプリセット'],
    presetNew: ['새 프리셋', 'New preset', '新規プリセット'], presetList: ['프리셋 목록', 'Preset list', 'プリセット一覧'],
    presetNoResults: ['해당하는 프리셋이 없습니다.', 'No matching presets.', '該当するプリセットはありません。'],
    presetReload: ['목록 새로고침', 'Reload presets', '一覧を再読み込み'], presetDetails: ['프리셋 편집', 'Preset editor', 'プリセットの編集'],
    presetName: ['프리셋 이름', 'Preset name', 'プリセット名'], presetDescription: ['설명', 'Description', '説明'], presetCode: ['프리셋 CSS', 'Preset CSS', 'プリセットのCSS'],
    presetSave: ['프리셋 저장', 'Save preset', 'プリセットを保存'], presetSaved: ['프리셋을 저장했습니다.', 'Preset saved.', 'プリセットを保存しました。'],
    presetDuplicate: ['복제하여 편집', 'Duplicate and edit', '複製して編集'], presetCopy: ['복사', 'copy', 'コピー'],
    presetDelete: ['프리셋 삭제', 'Delete preset', 'プリセットを削除'], presetDeleted: ['프리셋을 삭제했습니다.', 'Preset deleted.', 'プリセットを削除しました。'],
    presetDeleteConfirm: ['이 프리셋을 삭제할까요? 책에 적용한 CSS는 유지됩니다.', 'Delete this preset? CSS already applied to books is kept.', 'このプリセットを削除しますか？本に適用したCSSは残ります。'],
    presetBuiltinHint: ['기본 프리셋은 복제한 뒤 수정할 수 있습니다.', 'Duplicate a built-in preset to customize it.', '標準プリセットは複製して編集できます。'],
    presetDiscard: ['변경 버리기', 'Discard changes', '変更を破棄'],
    presetDiscardConfirm: ['저장하지 않은 프리셋 변경이 있습니다. 변경을 버리고 이동할까요?', 'This preset has unsaved changes. Discard them and continue?', 'プリセットに未保存の変更があります。破棄して続行しますか？'],
    presetTarget: ['적용 대상', 'Apply to', '適用先'], presetApplyMode: ['적용 방식', 'Apply mode', '適用方法'],
    presetAppend: ['기존 CSS 뒤에 추가', 'Append to existing CSS', '既存CSSの末尾に追加'], presetReplace: ['전체 CSS 교체', 'Replace all CSS', 'CSS全体を置換'],
    presetReplaceConfirm: ['적용 대상의 기존 CSS 전체를 이 프리셋으로 교체합니다. 계속할까요? 적용 후 코드 편집기에서 실행 취소할 수 있습니다.', 'Replace all CSS in the selected target with this preset? You can undo in the code editor afterward.', '適用先のCSS全体をこのプリセットに置き換えますか？コードエディターで元に戻せます。'],
    presetApplyHint: ['미리보기와 EPUB에 반영됩니다. 기존 프리셋을 수정해도 책의 CSS는 자동으로 바뀌지 않습니다.', 'Used in preview and EPUB. Editing a saved preset does not automatically change the book.', 'プレビューとEPUBに反映されます。プリセットを編集しても本のCSSは自動更新されません。'],
    presetSaveFirst: ['이름과 CSS를 저장한 뒤 적용하세요.', 'Save the name and CSS before applying.', '名前とCSSを保存してから適用してください。'],
    presetApplied: ['프리셋을 적용했습니다. 코드 편집기에서 실행 취소하거나 미리보기로 확인할 수 있습니다.', 'Preset applied. Undo in the code editor or check the preview.', 'プリセットを適用しました。コードエディターで元に戻すか、プレビューで確認できます。'],
    presetReading: ['본문 · 읽기 간격', 'Body · reading spacing', '本文・読みやすい間隔'], presetReadingHint: ['문단 간격, 첫 줄 들여쓰기, 줄 간격을 설정합니다.', 'Paragraph spacing, first-line indentation and line height.', '段落間隔、字下げ、行間を設定します。'],
    presetHeadings: ['제목 · 구분선', 'Headings · divider', '見出し・区切り線'], presetHeadingsHint: ['제목 간격과 제목 바로 뒤의 페이지 나눔을 조정합니다.', 'Heading spacing and page breaks after headings.', '見出しの間隔と直後の改ページを調整します。'],
    presetQuote: ['인용 · 강조 상자', 'Quote · highlight box', '引用・強調ボックス'], presetQuoteHint: ['인용에 배경색과 왼쪽 테두리를 적용합니다.', 'Background color and a left border for quotations.', '引用に背景色と左の罫線を適用します。'],
    presetTable: ['표 · 기본 테두리', 'Table · simple borders', '表・基本の罫線'], presetTableHint: ['표 테두리, 셀 간격과 머리글 배경을 설정합니다.', 'Table borders, cell padding and header background.', '表の罫線、セルの余白、見出し背景を設定します。'],
    presetFigure: ['이미지 · 캡션', 'Images · captions', '画像・キャプション'], presetFigureHint: ['이미지 크기와 캡션 정렬을 조정합니다.', 'Image sizing and caption alignment.', '画像の大きさとキャプションの配置を調整します。'],
    presetNotes: ['각주 · 구분선', 'Footnotes · separator', '脚注・区切り線'], presetNotesHint: ['각주 영역의 구분선과 글자 간격을 설정합니다.', 'A separator and text spacing for footnotes.', '脚注の区切り線と文字の間隔を設定します。'],
    PRESET_INVALID: ['이름(1~80자), 설명(240자 이하), CSS 내용을 확인하세요.', 'Check the name (1–80 characters), description (up to 240) and CSS.', '名前（1〜80文字）、説明（240文字まで）、CSSを確認してください。'],
    PRESET_LIBRARY_INVALID: ['저장된 프리셋 목록을 읽을 수 없습니다. 기존 파일은 변경하지 않았습니다.', 'The saved preset library cannot be read. The existing file has not been changed.', '保存済みの一覧を読み取れません。既存ファイルは変更していません。'],
    PRESET_CONFLICT: ['다른 창에서 프리셋이 변경되었습니다. 목록을 새로고침한 뒤 다시 편집하세요.', 'Presets changed in another window. Reload the list before editing again.', '別のウィンドウで変更されました。一覧を再読み込みして編集してください。'],
    PRESET_MISSING: ['프리셋을 찾을 수 없습니다. 목록을 새로고침하세요.', 'Preset not found. Reload the list.', 'プリセットが見つかりません。一覧を再読み込みしてください。'],
    PRESET_NAME_EXISTS: ['같은 이름의 프리셋이 있습니다. 다른 이름을 입력하세요.', 'A preset with this name already exists. Choose another name.', '同じ名前のプリセットがあります。別の名前にしてください。'],
    PRESET_LIMIT: ['프리셋은 최대 100개, 전체 4MB까지 저장할 수 있습니다.', 'Save up to 100 presets and 4 MB in total.', 'プリセットは100件、合計4MBまで保存できます。'],
    CSS_TOO_LARGE: ['CSS는 100,000자 이하로 작성하세요.', 'CSS must be at most 100,000 characters.', 'CSSは100,000文字以内で入力してください。'],
    quickInsert: ['문단 도구·빠른 삽입', 'Block tools and quick insert', '段落ツール・クイック挿入'],
    textTools: ['선택한 텍스트 도구', 'Selected text tools', '選択したテキストのツール'],
    linkTools: ['링크 도구', 'Link tools', 'リンクツール'],
    imageTools: ['이미지 도구', 'Image tools', '画像ツール'],
    audioTools: ['오디오 도구', 'Audio tools', '音声ツール'],
    tableTools: ['표 도구', 'Table tools', '表ツール'],
    footnoteTools: ['각주 도구', 'Footnote tools', '脚注ツール'],
    blockTools: ['문단 도구', 'Block tools', '段落ツール'],
    editLink: ['링크 수정', 'Edit link', 'リンクを編集'],
    imageleft: ['이미지 왼쪽 정렬', 'Align image left', '画像を左揃え'],
    imagecenter: ['이미지 가운데 정렬', 'Center image', '画像を中央揃え'],
    imageright: ['이미지 오른쪽 정렬', 'Align image right', '画像を右揃え'],
    imageProperties: ['이미지 크기·설명', 'Image size and description', '画像のサイズ・説明'],
    audioProperties: ['오디오 제목·설정', 'Audio title and settings', '音声タイトル・設定'],
    cellProperties: ['셀 속성', 'Cell properties', 'セルの属性'],
    tableRows: ['행 편집', 'Edit rows', '行を編集'],
    tableColumns: ['열 편집', 'Edit columns', '列を編集'],
    paragraphBefore: ['앞에 문단 삽입', 'Insert paragraph before', '前に段落を挿入'],
    paragraphAfter: ['뒤에 문단 삽입', 'Insert paragraph after', '後ろに段落を挿入'],
    cellBackground: ['셀 배경색', 'Cell background', 'セルの背景色'], clearCellBackground: ['셀 배경색 지우기', 'Clear cell background', 'セル背景をクリア'],
    verticalAlign: ['셀 세로 정렬', 'Cell vertical alignment', 'セルの縦配置'], cellPadding: ['셀 안쪽 여백', 'Cell padding', 'セルの余白'],
    top: ['위', 'Top', '上'], middle: ['가운데', 'Middle', '中央'], bottom: ['아래', 'Bottom', '下'],
    insert: ["삽입", "Insert", "挿入"],
    commonCss: ["공통 CSS", "Common CSS", "共通CSS"],
    chapterCss: ["현재 장 CSS", "Chapter CSS", "現在の章のCSS"],
    cssHint: ["기본 스타일 → 공통 CSS → 현재 장 CSS 순서로 적용됩니다. 변경은 미리보기와 EPUB에 반영됩니다.", "Applied in order: base styles → common CSS → chapter CSS. Changes appear in Preview and EPUB.", "基本スタイル → 共通CSS → 章のCSSの順にプレビューとEPUBに適用します。"],
    cssReady: ["CSS 적용 준비됨 · 입력 내용은 자동 저장됩니다.", "CSS ready · Your edits are saved automatically.", "CSS適用可能 · 入力内容は自動保存されます。"],
    CSS_INVALID: ["CSS 문법을 확인하세요. 오류가 있는 CSS는 적용되지 않습니다.", "Check CSS syntax. Invalid CSS is not applied.", "CSS構文を確認してください。不正なCSSは適用されません。"],
    CSS_RESOURCE: ["외부 자원, @import, 지원하지 않는 규칙은 사용할 수 없습니다.", "External resources, @import and unsupported rules are not allowed.", "外部リソース、@import、未対応のルールは利用できません。"],
    footnote: ["각주", "Footnote", "脚注"],
    footnoteText: ["각주 내용", "Footnote text", "脚注の内容"],
    footnoteHint: ["본문 위치에 번호가 붙고 장 끝에 각주가 모입니다. 번호를 선택하면 수정할 수 있습니다.", "References are numbered automatically; notes appear at the end of the chapter. Select a number to edit.", "本文の参照番号は自動更新され、脚注は章末に表示されます。番号を選択して編集できます。"],
    FOOTNOTE_EMPTY: ["각주 내용이 비어 있습니다.", "A footnote is empty.", "脚注の内容が空です。"],
    audio: ["오디오", "Audio", "オーディオ"],
    addAudio: ["오디오 삽입", "Insert audio", "音声を挿入"],
    audioTitle: ["오디오 설명", "Audio label", "音声の説明"],
    audioKind: ["오디오 용도", "Audio purpose", "音声の用途"],
    effect: ["효과음", "Sound effect", "効果音"],
    backgroundAudio: ["배경음", "Background music", "BGM"],
    loop: ["반복 재생", "Loop playback", "繰り返し再生"],
    audioHint: ["MP3·M4A(AAC)를 현재 위치에 삽입합니다. 독자가 재생 버튼으로 시작하며 반복 설정은 EPUB에도 저장됩니다. 뷰어에 따라 재생 지원이 다릅니다.", "Insert MP3/M4A (AAC) at the cursor. Readers start playback with the player; looping is preserved in EPUB. Playback support varies by reader.", "カーソル位置にMP3・M4A（AAC）を挿入します。読者が再生を開始し、リピート設定はEPUBに保存されます。ビューアーにより再生対応が異なります。"],
    AUDIO_MISSING: ["본문 오디오 파일이 없습니다.", "An audio asset is missing.", "音声ファイルがありません。"],
    tablePickerHint: ["격자에서 크기를 고르거나 아래에 행·열 수를 입력하세요. 방향키로 이동하고 Enter로 삽입합니다.", "Choose a grid size or enter rows and columns. Use arrow keys and Enter in the grid.", "グリッドでサイズを選ぶか、行・列の数を入力します。矢印キーで移動、Enterで挿入できます。"],
    tableSize: ["표 크기", "Table size", "表のサイズ"],
    rows: ["행", "rows", "行"],
    columnsCount: ["열", "columns", "列"],
    headerRow: ["첫 행을 머리글로 사용", "Use first row as header", "先頭行を見出しにする"],
    selectCells: ["셀 범위 선택", "Select cell range", "セル範囲を選択"],
    fromRow: ["시작 행", "Start row", "開始行"],
    fromColumn: ["시작 열", "Start column", "開始列"],
    toRow: ["끝 행", "End row", "終了行"],
    toColumn: ["끝 열", "End column", "終了列"],
    tableSelectionHint: ["셀을 드래그하거나 범위 선택 후 병합하세요. 열 경계는 드래그로 조절할 수 있습니다.", "Drag across cells or select a range to merge. Drag column boundaries to resize.", "セルをドラッグするか範囲を選んで結合します。列の境界をドラッグして幅を変更できます。"],
    addRowBefore: ["위에 행 추가", "Row above", "上に行を追加"],
    addRowAfter: ["아래에 행 추가", "Row below", "下に行を追加"],
    addColumnBefore: ["왼쪽에 열 추가", "Column left", "左に列を追加"],
    addColumnAfter: ["오른쪽에 열 추가", "Column right", "右に列を追加"],
    toggleHeaderRow: ["머리글 행 전환", "Toggle header row", "見出し行を切替"],
    toggleHeaderColumn: ["머리글 열 전환", "Toggle header column", "見出し列を切替"],
    shortcuts: ["단축키·명령", "Shortcuts & commands", "ショートカット・コマンド"],
    toolbar: ["도구 모음으로 이동", "Focus toolbar", "ツールバーに移動"],
    findCommand: ["기능 찾기", "Find a command", "コマンドを検索"],
    shortcutHint: ["본문 편집에서 사용하는 단축키입니다. 목록의 기능을 눌러 실행할 수도 있습니다. 표 명령은 표 안에서 사용하세요.", "Shortcuts work in the document. Click a command to run it. Table commands require a table selection.", "本文編集で使うショートカットです。項目を押して実行することもできます。表のコマンドは表内で利用してください。"],
    tabHelp: ['Tab · Shift+Tab — 커서 위치별 동작', 'Tab · Shift+Tab — actions by context', 'Tab · Shift+Tab — カーソル位置ごとの動作'],
    tabBodyHint: ['본문·제목: Tab으로 문단 들여쓰기를 늘리고 Shift+Tab으로 줄입니다. 여러 문단을 선택해 함께 적용할 수 있습니다. 편집기 밖으로 이동하려면 Esc 다음 Tab 또는 Shift+Tab을 누르세요. 입력창에서는 다음/이전 입력 요소로 이동합니다.', 'Paragraphs and headings: Tab increases paragraph indentation; Shift+Tab decreases it, including multiple selected paragraphs. Press Esc, then Tab or Shift+Tab to leave the editor. Form fields retain normal focus navigation.', '本文・見出し: Tabで段落の字下げを増やし、Shift+Tabで減らします。複数段落の選択にも適用できます。Escの後にTabまたはShift+Tabでエディターの外へ移動。入力欄では次/前の入力要素へ移動します。'],
    tabListHint: ['목록: Tab으로 하위 단계, Shift+Tab으로 상위 단계로 이동합니다. 최상위에서 내어쓰면 일반 문단이 됩니다. 하위 단계로 옮길 수 없으면 포커스를 이동합니다.', 'Lists: Tab nests items, Shift+Tab lifts them. Lifting a top-level item turns it into a paragraph. If nesting is unavailable, focus moves on.', 'リスト: Tabで下位、Shift+Tabで上位へ移動。最上位では通常の段落になります。下位へ移動できない場合はフォーカスを移動します。'],
    tabTableHint: ['표: 다음/이전 셀로 이동합니다. 마지막 셀에서 Tab을 누르면 행이 추가됩니다. 첫 셀의 Shift+Tab은 이전 입력 요소로 이동합니다. 셀 안의 목록·코드는 해당 편집 동작이 우선합니다.', 'Tables: next/previous cell; Tab in the last cell adds a row. Shift+Tab in the first cell moves focus out. Available list/code actions inside a cell take precedence.', '表: 次/前のセルへ移動。最後のセルのTabで行を追加、最初のセルのShift+Tabで前の入力要素へ移動。セル内のリスト・コード操作を優先します。'],
    tabCodeHint: ['코드 블록: 현재 줄 또는 선택한 줄을 4칸 들여쓰기/내어쓰기합니다. 본문 편집 중 도구 모음으로 이동하려면 Alt+F10을 누르세요.', 'Code blocks: indent/outdent the current or selected lines by four spaces. Press Alt+F10 while editing the document to move to the toolbar.', 'コードブロック: 現在行または選択行を4スペース字下げ/戻します。本文編集中にAlt+F10でツールバーへ移動します。'],
    tabSourceHint: ['공통 CSS·현재 장 CSS: Tab으로 들여쓰기, Shift+Tab으로 내어쓰기합니다. Esc 다음 Tab으로 편집기 밖으로 이동합니다. 읽기 전용 소스 보기에서는 다음/이전 입력 요소로 이동합니다.', 'Common CSS and chapter CSS: Tab indents, Shift+Tab outdents. Press Esc, then Tab to leave the editor. Read-only source view moves focus forward/backward.', '共通CSS・現在の章のCSS: Tabで字下げ、Shift+Tabで戻します。Escの後にTabでエディターの外へ移動。読み取り専用ソース表示では次/前の入力要素へ移動します。'],
    keyboardNavigation: ["Alt+F10: 선택 도구 모음 · ←/→: 도구 이동 · Esc: 메뉴 닫기·본문으로 · Alt+0: 도움말", "Alt+F10: contextual toolbar · ←/→: move between tools · Esc: close menu / document · Alt+0: help", "Alt+F10: 選択ツールバー · ←/→: ツール移動 · Esc: 閉じる・本文 · Alt+0: ヘルプ"],
    autoformatHint: ["문단 시작에서 # + 공백: 제목, > + 공백: 인용, - + 공백: 목록. 본문과 CSS의 실행 취소는 각각 유지됩니다.", "At paragraph start: # + space for heading, > + space for quote, - + space for list. Document and CSS have separate undo histories.", "段落先頭で # + 空白: 見出し、> + 空白: 引用、- + 空白: リスト。本文とCSSの履歴は個別です。"],
    editor: ['EPUB 에디터', 'EPUB Studio', 'EPUBエディター'],
    welcome: ['한 권의 책, 여기서 시작하세요.', 'Your next book starts here.', 'ここから、一冊の本を。'],
    introduction: ['목차를 구성하고, 글과 이미지를 배치하고, 나만의 전자책을 완성하세요.', 'Shape the chapters, compose the pages, and publish your own ebook.', '章を構成し、文章と画像を配置して、自分の電子書籍を仕上げましょう。'],
    newBook: ['새 책', 'New book', '新しい本'], open: ['프로젝트 열기', 'Open project', 'プロジェクトを開く'],
    blank: ['빈 책', 'Blank book', '白紙の本'], essay: ['에세이', 'Essay', 'エッセイ'], guide: ['가이드북', 'Guidebook', 'ガイドブック'],
    blankHint: ['첫 문장부터 자유롭게', 'A fresh page for your ideas', '最初の一文から自由に'],
    essayHint: ['프롤로그부터 에필로그까지', 'From prologue to epilogue', 'プロローグからエピローグまで'],
    guideHint: ['개념과 실전을 차근차근', 'Structure ideas and practical advice', '基本から実践まで'],
    local: ['내 컴퓨터에 저장되는 제작 공간', 'A local workspace for your book', 'パソコンに保存する制作スペース'],
    recent: ['작업 이어하기', 'Continue a project', '作業を続ける'], back: ['도구 목록', 'All tools', 'ツール一覧'],
    save: ['저장', 'Save', '保存'], saveAs: ['다른 이름으로 저장', 'Save as', '名前を付けて保存'],
    export: ['EPUB 내보내기', 'Export EPUB', 'EPUBを書き出す'], saved: ['프로젝트 저장됨', 'Project saved', 'プロジェクト保存済み'],
    recovered: ['복구 기록 저장됨', 'Recovery saved', '復元データ保存済み'], unsaved: ['저장되지 않은 변경', 'Unsaved changes', '未保存の変更'],
    working: ['처리 중…', 'Working…', '処理中…'], error: ['작업을 완료하지 못했습니다.', 'Could not complete this operation.', '操作を完了できませんでした。'],
    cancel: ['취소', 'Cancel', 'キャンセル'], close: ['닫기', 'Close', '閉じる'], remove: ['삭제', 'Delete', '削除'],
    write: ['원고', 'Write', '原稿'], design: ['책 편집', 'Design', '本の編集'], preview: ['미리보기', 'Preview', 'プレビュー'], source: ['소스', 'Source', 'ソース'],
    previewViewer: ['북매니저 뷰어', 'BookManager viewer', 'BookManagerビューアー'],
    viewerPreviewHint: ['현재 편집 내용을 북매니저 뷰어에서 미리봅니다. 다시 누르면 최신 내용으로 열립니다.', 'Preview current edits in the BookManager viewer. Click again to open the latest version.', '現在の編集内容をBookManagerビューアーでプレビューします。もう一度押すと最新の内容で開きます。'],
    viewerPreviewPreparing: ['북매니저 뷰어 미리보기 준비 중…', 'Preparing BookManager viewer preview…', 'BookManagerビューアーのプレビューを準備中…'],
    viewerPreviewOpened: ['현재 편집 내용을 북매니저 뷰어로 열었습니다.', 'Current edits opened in the BookManager viewer.', '現在の編集内容をBookManagerビューアーで開きました。'],
    VIEWER_UNAVAILABLE: ['북매니저 뷰어를 사용할 수 없습니다. 앱을 다시 실행해 주세요.', 'The BookManager viewer is unavailable. Please restart the app.', 'BookManagerビューアーを利用できません。アプリを再起動してください。'],
    VIEWER_OPEN_FAILED: ['북매니저 뷰어를 열지 못했습니다. 다시 시도해 주세요.', 'Could not open the BookManager viewer. Please try again.', 'BookManagerビューアーを開けませんでした。もう一度お試しください。'],
    chapters: ['책 구성', 'Book', '本の構成'], assets: ['자료', 'Assets', '素材'], outline: ['요소', 'Outline', '要素'],
    chapter: ['장', 'Chapter', '章'], chapterTitle: ['장 제목', 'Chapter title', '章のタイトル'], addChapter: ['장 추가', 'Add chapter', '章を追加'],
    duplicate: ['장 복제', 'Duplicate chapter', '章を複製'], moveUp: ['위로 이동', 'Move up', '上へ移動'], moveDown: ['아래로 이동', 'Move down', '下へ移動'],
    deleteChapter: ['이 장을 삭제할까요? 책 구성 되돌리기로 복원할 수 있습니다.', 'Delete this chapter? You can restore it with Undo book changes.', 'この章を削除しますか？構成の変更を元に戻して復元できます。'],
    undoBook: ['책 구성 되돌리기', 'Undo book changes', '構成の変更を元に戻す'], redoBook: ['책 구성 다시 실행', 'Redo book changes', '構成の変更をやり直す'],
    undo: ['실행 취소', 'Undo', '元に戻す'], redo: ['다시 실행', 'Redo', 'やり直す'],
    properties: ['속성', 'Properties', '属性'], styles: ['스타일', 'Styles', 'スタイル'], book: ['책 정보', 'Book details', '書籍情報'],
    inspector: ['책 설정', 'Book settings', '書籍設定'], chapterAndElement: ['장·요소', 'Chapter & element', '章・要素'],
    bookDefaults: ['책 기본 서식', 'Book defaults', '書籍の基本書式'], currentChapterSettings: ['현재 장 설정', 'Current chapter settings', '現在の章の設定'],
    bookDefaultsHint: ['책 전체의 기본 모양입니다. 툴바에서 지정한 글자·문단 서식과 공통·장별 CSS에 따라 일부 모양이 달라질 수 있습니다.', 'Base appearance for the whole book. Text and paragraph formatting and common or chapter CSS can override these defaults.', '書籍全体の基本表示です。文字・段落の書式や共通・章別CSSによって一部の表示が変わる場合があります。'],
    commonCssScopeHint: ['책 전체에 적용할 CSS와 프리셋을 관리합니다.', 'Manage CSS and presets that apply throughout the book.', '書籍全体に適用するCSSとプリセットを管理します。'],
    textFormattingLocation: ['글자·문단 서식은 상단 툴바에서 편집합니다. 이미지·오디오·표를 선택하면 이곳에 상세 설정이 표시됩니다.', 'Edit text and paragraph formatting in the top toolbar. Select an image, audio or table to see its details here.', '文字・段落の書式は上部ツールバーで編集します。画像・音声・表を選ぶと詳細設定がここに表示されます。'],
    elementEditingLocation: ['요소의 상세 설정은 원고·책 편집에서 요소를 선택하면 표시됩니다.', 'Select an element in Write or Design to edit its details.', '原稿・デザインで要素を選択すると詳細設定が表示されます。'],
    focusTextFormatting: ['글자 서식으로 이동', 'Go to text formatting', '文字書式へ移動'],
    defaultFont: ['글꼴: 기본', 'Font: default', 'フォント: 基本'], defaultFontSize: ['크기: 기본', 'Size: default', 'サイズ: 基本'],
    selectionFontHint: ['선택한 글자에 적용합니다. 기본을 선택하면 글꼴·크기 지정을 해제하고 문단과 책의 서식을 따릅니다.', 'Applies to selected text. Default removes the font or size override and follows the paragraph and book formatting.', '選択した文字に適用します。基本を選ぶとフォント・サイズの指定を解除し、段落と書籍の書式に従います。'],
    toggleStructure: ['구성 패널 접기·펼치기', 'Toggle structure panel', '構成パネルを開閉'],
    toggleInspector: ['속성 패널 접기·펼치기', 'Toggle inspector panel', '属性パネルを開閉'],
    paragraph: ['본문', 'Paragraph', '本文'], heading: ['제목', 'Heading', '見出し'], heading1: ['제목 1', 'Heading 1', '見出し1'], heading2: ['제목 2', 'Heading 2', '見出し2'], heading3: ['제목 3', 'Heading 3', '見出し3'],
    heading4: ['제목 4', 'Heading 4', '見出し4'], heading5: ['제목 5', 'Heading 5', '見出し5'], heading6: ['제목 6', 'Heading 6', '見出し6'],
    paragraphFormat: ['문단 형식', 'Paragraph format', '段落の形式'], textStyles: ['텍스트 스타일', 'Text styles', 'テキストスタイル'],
    paragraphFormats: ['문단 형식 관리', 'Manage paragraph formats', '段落形式を管理'],
    customParagraphFormats: ['사용자 정의 문단 형식', 'Custom paragraph formats', 'ユーザー定義の段落形式'],
    paragraphFormatCreate: ['현재 문단에서 형식 만들기', 'Create format from paragraph', '現在の段落から形式を作成'],
    paragraphFormatNew: ['새 문단 형식', 'New paragraph format', '新しい段落形式'],
    paragraphFormatName: ['형식 이름', 'Format name', '形式名'], paragraphFormatBase: ['기본 문단 종류', 'Base paragraph type', '基本の段落種類'],
    paragraphFormatSearch: ['문단 형식 검색', 'Search paragraph formats', '段落形式を検索'],
    paragraphFormatList: ['저장한 문단 형식', 'Saved paragraph formats', '保存した段落形式'],
    paragraphFormatDetails: ['문단 형식 설정', 'Paragraph format settings', '段落形式の設定'],
    paragraphFormatEmpty: ['저장한 문단 형식이 없습니다.', 'No saved paragraph formats.', '保存した段落形式はありません。'],
    paragraphFormatsHint: ['이 컴퓨터에 문단 형식을 저장해 다른 책에서도 사용합니다. 수정한 형식을 본문에 반영하려면 다시 적용하세요.', 'Save paragraph formats on this computer for use across books. Reapply an edited format to update a paragraph.', 'このコンピューターに段落形式を保存し、他の本でも使えます。変更した形式は段落に再適用してください。'],
    paragraphFormatApplyHint: ['선택한 문단에 적용합니다. 글자별 강조와 링크는 유지됩니다.', 'Apply to selected paragraphs, preserving inline emphasis and links.', '選択した段落に適用し、文字の強調とリンクを保持します。'],
    paragraphFormatDeleteConfirm: ['이 문단 형식을 목록에서 삭제할까요? 본문에 적용된 서식은 유지됩니다.', 'Delete this format from the library? Formatting already applied to text is preserved.', 'この形式を一覧から削除しますか？本文に適用済みの書式は保持されます。'],
    paragraphFormatSaved: ['문단 형식을 저장했습니다.', 'Paragraph format saved.', '段落形式を保存しました。'],
    paragraphFormatSaveFirst: ['이름과 문단 설정을 저장한 뒤 적용하세요.', 'Save the name and paragraph settings before applying.', '名前と段落設定を保存してから適用してください。'],
    paragraphFormatDeleted: ['문단 형식을 삭제했습니다.', 'Paragraph format deleted.', '段落形式を削除しました。'],
    paragraphFormatUnavailable: ['이 위치에는 해당 문단 형식을 적용할 수 없습니다.', 'This paragraph format cannot be applied here.', 'この位置にはこの段落形式を適用できません。'],
    paragraphFormatSample: ['문단 형식 미리보기', 'Paragraph format preview', '段落形式のプレビュー'],
    paragraphFormatSampleText: ['‘기본 설정 따르기’는 이 형식에서 값을 따로 지정하지 않는 옵션입니다. 숫자 입력을 비워도 책의 기본 설정을 따릅니다.', 'Follow defaults leaves the value unspecified in this format. Empty number fields also use the book’s defaults.', '「基本設定に従う」は、この形式で値を個別に指定しない設定です。数値欄が空の場合も本の基本設定に従います。'],
    formatInherit: ['기본 설정 따르기', 'Follow defaults', '基本設定に従う'], formatEnabled: ['사용', 'On', '使用'], formatDisabled: ['해제', 'Off', '解除'],
    formatClearValue: ['지정 해제', 'Clear override', '個別指定を解除'],
    formatColorHint: ['지정 해제하면 책의 기본 글자색을 따릅니다.', 'Clear the override to use the book’s default text color.', '個別指定を解除すると、本の基本の文字色に従います。'],
    formatBackgroundHint: ['지정 해제하면 이 형식에서 배경색을 따로 칠하지 않습니다.', 'Clear the override to leave the background unspecified in this format.', '個別指定を解除すると、この形式では背景色を個別に設定しません。'],
    formatAlignmentHint: ['기본 설정 따르기를 선택하면 책의 기본 정렬을 사용합니다.', 'Follow defaults uses the book’s default alignment.', '「基本設定に従う」を選ぶと、本の基本の配置を使用します。'],
    formatFont_serif: ['명조 계열', 'Serif', '明朝体'], 'formatFont_sans-serif': ['고딕 계열', 'Sans serif', 'ゴシック体'], formatFont_monospace: ['고정폭', 'Monospace', '等幅'],
    formatFontSize: ['글자 크기 (px)', 'Font size (px)', '文字サイズ (px)'], formatFirstLine: ['첫 줄 들여쓰기·내어쓰기 (em)', 'First line indent / hanging (em)', '字下げ・ぶら下げ (em)'],
    formatSpaceBefore: ['문단 앞 간격 (em)', 'Space before (em)', '段落前の間隔 (em)'], formatSpaceAfter: ['문단 뒤 간격 (em)', 'Space after (em)', '段落後の間隔 (em)'],
    PARAGRAPH_FORMAT_INVALID: ['형식 이름과 설정값을 확인하세요. 색상은 #RRGGBB 형식입니다.', 'Check the name and settings. Colors must use #RRGGBB.', '形式名と設定値を確認してください。色は#RRGGBB形式です。'],
    PARAGRAPH_FORMAT_LIBRARY_INVALID: ['문단 형식 파일을 읽을 수 없습니다. 기존 파일은 보존됩니다.', 'Cannot read the paragraph format library. The existing file is preserved.', '段落形式のファイルを読み込めません。既存のファイルは保持されます。'],
    PARAGRAPH_FORMAT_CONFLICT: ['다른 창에서 문단 형식을 변경했습니다. 새로고침한 뒤 다시 편집하세요.', 'Paragraph formats changed in another window. Reload before editing.', '他のウィンドウで段落形式が変更されました。再読み込みして編集してください。'],
    PARAGRAPH_FORMAT_MISSING: ['문단 형식을 찾을 수 없습니다. 목록을 새로고침하세요.', 'Paragraph format not found. Reload the list.', '段落形式が見つかりません。一覧を再読み込みしてください。'],
    PARAGRAPH_FORMAT_NAME_EXISTS: ['같은 이름의 문단 형식이 있습니다.', 'A paragraph format with this name already exists.', '同じ名前の段落形式があります。'],
    PARAGRAPH_FORMAT_LIMIT: ['문단 형식은 최대 100개까지 저장할 수 있습니다.', 'Save up to 100 paragraph formats.', '段落形式は最大100件まで保存できます。'],
    blockStyles: ['문단 스타일', 'Block styles', '段落スタイル'], inlineStyles: ['글자 스타일', 'Inline styles', '文字スタイル'],
    clearBlockStyle: ['문단 스타일 해제', 'Clear block style', '段落スタイルを解除'], clearInlineStyle: ['글자 스타일 해제', 'Clear inline style', '文字スタイルを解除'],
    style_lead: ['리드 문단', 'Lead paragraph', 'リード段落'], style_subtitle: ['부제', 'Subtitle', 'サブタイトル'], style_note: ['안내 상자', 'Information box', '案内ボックス'], style_warning: ['주의 상자', 'Warning box', '注意ボックス'],
    style_quotation: ['인용 강조', 'Pull quote', '引用の強調'], style_signature: ['서명', 'Signature', '署名'], style_emphasis: ['강조 글자', 'Strong emphasis', '強調文字'], style_muted: ['보조 글자', 'Muted text', '補助文字'], style_keyboard: ['키보드 입력', 'Keyboard input', 'キー入力'], style_small: ['작은 글자', 'Small text', '小さい文字'],
    textBackground: ['텍스트 배경색', 'Text background color', '文字の背景色'], clearTextBackground: ['텍스트 배경색 제거', 'Remove text background', '文字の背景色を解除'],
    highlight: ['하이라이트', 'Highlight', 'ハイライト'], clearHighlight: ['하이라이트 제거', 'Remove highlight', 'ハイライトを解除'],
    yellowMarker: ['노란 형광펜', 'Yellow marker', '黄色マーカー'], greenMarker: ['초록 형광펜', 'Green marker', '緑色マーカー'], pinkMarker: ['분홍 형광펜', 'Pink marker', 'ピンクマーカー'], blueMarker: ['파란 형광펜', 'Blue marker', '青色マーカー'], redPen: ['빨간 펜', 'Red pen', '赤色ペン'], greenPen: ['초록 펜', 'Green pen', '緑色ペン'],
    superscript: ['상첨자', 'Superscript', '上付き文字'], subscript: ['하첨자', 'Subscript', '下付き文字'],
    media: ['미디어 삽입', 'Insert media', 'メディアを挿入'], editMedia: ['미디어 수정', 'Edit media', 'メディアを編集'], mediaTools: ['미디어 도구', 'Media tools', 'メディアツール'],
    mediaUrl: ['미디어 URL', 'Media URL', 'メディアURL'], mediaTitle: ['미디어 제목', 'Media title', 'メディアのタイトル'],
    mediaHint: ['YouTube·Vimeo 주소를 입력하세요. 본문에 주소만 붙여넣어도 미디어로 삽입됩니다.', 'Enter a YouTube or Vimeo URL. Pasting a URL into the document also inserts media.', 'YouTube・VimeoのURLを入力します。本文にURLを貼り付けても挿入できます。'],
    mediaExportHint: ['편집기에서 재생할 수 있습니다. EPUB·미리보기에는 제목과 원본 링크가 표시되며, 영상은 인터넷에 연결해 브라우저에서 봅니다.', 'Play in the editor. EPUB and reading previews show the title and original link; open it in a browser with an internet connection.', 'エディターで再生できます。EPUB・読書プレビューにはタイトルと元のリンクを表示し、動画はインターネットに接続したブラウザーで開きます。'],
    invalidMedia: ['지원하는 YouTube 또는 Vimeo 영상 주소를 입력하세요.', 'Enter a supported YouTube or Vimeo video URL.', '対応するYouTubeまたはVimeo動画URLを入力してください。'],
    playMedia: ['미디어 재생', 'Play media', 'メディアを再生'], stopMedia: ['재생 닫기', 'Close player', 'プレーヤーを閉じる'], openMedia: ['브라우저에서 열기', 'Open in browser', 'ブラウザーで開く'],
    specialCharacters: ['특수문자', 'Special characters', '特殊文字'], emoji: ['이모지', 'Emoji', '絵文字'],
    charactersHint: ['문자를 누르면 커서 위치에 삽입됩니다. 창을 닫지 않고 여러 문자를 연속해서 넣을 수 있습니다.', 'Click to insert at the cursor. Insert multiple characters without closing this window.', '文字を押すとカーソル位置に挿入します。ウィンドウを閉じずに連続して挿入できます。'],
    imeCharacters: ['자음 + 한자', 'Korean consonant + Hanja', 'ハングル子音 + 漢字'], hanjaKey: ['한자', 'Hanja', '漢字'],
    imeMath: ['수학 기호', 'Math symbols', '数学記号'],
    imeCharactersHint: ['윈도우의 자음+한자 특수문자도 사용할 수 있습니다. 분류에서 자음을 고르거나 ㅁ, ㅇ처럼 검색하세요.', 'Includes Windows consonant + Hanja symbols. Choose a consonant category or search for ㅁ, ㅇ, and more.', 'Windowsの子音+漢字キーの特殊文字も使えます。分類から子音を選ぶか、ㅁ・ㅇなどで検索してください。'],
    imeCharacterSearch: ['문자·이름·자음 검색 (예: ㅁ, ㎡)', 'Search character, name or consonant (e.g. ㅁ, ㎡)', '文字・名前・子音を検索（例: ㅁ、㎡）'],
    characterSearch: ['문자·이름 검색', 'Search character or name', '文字・名前を検索'], characterCategory: ['문자 분류', 'Category', '分類'], characterInserted: ['삽입됨', 'Inserted', '挿入済み'], characterCount: ['개', 'items', '件'],
    chars_all: ['전체', 'All', 'すべて'], chars_recent: ['최근 사용', 'Recently used', '最近使用'], chars_punctuation: ['문장 부호', 'Punctuation', '句読点'], chars_brackets: ['괄호', 'Brackets', '括弧'], chars_math: ['수학·그리스 문자', 'Math & Greek', '数学・ギリシャ文字'], chars_arrows: ['화살표', 'Arrows', '矢印'], chars_currency: ['통화·저작권', 'Currency & copyright', '通貨・著作権'], chars_symbols: ['기호', 'Symbols', '記号'], chars_letters: ['라틴 문자', 'Latin letters', 'ラテン文字'],
    chars_units: ['단위·통화', 'Units & currency', '単位・通貨'], chars_boxDrawing: ['선·테두리', 'Box drawing', '線・罫線'], chars_enclosedHangul: ['원·괄호 한글', 'Enclosed Hangul', '丸・括弧付きハングル'], chars_enclosedAlphanumeric: ['원·괄호 영문·숫자', 'Enclosed letters & numbers', '丸・括弧付き英数字'],
    chars_numbers: ['전각·로마 숫자', 'Fullwidth & Roman numerals', '全角・ローマ数字'], chars_fractions: ['분수·위아래 첨자', 'Fractions & super/subscripts', '分数・上付き・下付き文字'], chars_hangul: ['한글 자모', 'Hangul letters', 'ハングル字母'], chars_oldHangul: ['옛한글', 'Old Hangul', '古ハングル'], chars_fullwidthLatin: ['전각 영문', 'Fullwidth Latin', '全角英字'], chars_greek: ['그리스 문자', 'Greek letters', 'ギリシャ文字'], chars_hiragana: ['히라가나', 'Hiragana', 'ひらがな'], chars_katakana: ['가타카나', 'Katakana', 'カタカナ'], chars_cyrillic: ['키릴 문자', 'Cyrillic letters', 'キリル文字'],
    chars_faces: ['표정', 'Faces', '表情'], chars_people: ['사람·손짓', 'People & gestures', '人・ジェスチャー'], chars_nature: ['동물·자연', 'Animals & nature', '動物・自然'], chars_food: ['음식', 'Food', '食べ物'], chars_travel: ['여행·날씨', 'Travel & weather', '旅行・天気'], chars_objects: ['사물', 'Objects', '物'], chars_hearts: ['하트', 'Hearts', 'ハート'],
    chars_activities: ['활동·스포츠', 'Activities & sports', '活動・スポーツ'], chars_flags: ['국기·깃발', 'Flags', '国旗・旗'],
    emojiCatalogHint: ['기본 {base}개 · 피부색 조합 포함 {total}개. 한국어·영어로 검색하거나 분류를 골라보세요.', '{base} base emoji · {total} including skin tones. Search in Korean or English, or choose a category.', '基本{base}件・肌の色の組み合わせを含めて{total}件。韓国語・英語で検索するか、分類を選んでください。'],
    skinToneAll: ['모든 피부색 (혼합 포함)', 'All skin tones (including mixed)', 'すべての肌の色（組み合わせを含む）'],
    skinTone: ['피부색', 'Skin tone', '肌の色'], skinTone0: ['기본', 'Default', '標準'], skinTone1: ['밝은 피부색', 'Light', '明るい肌'], skinTone2: ['약간 밝은 피부색', 'Medium light', 'やや明るい肌'], skinTone3: ['중간 피부색', 'Medium', '中間の肌'], skinTone4: ['약간 어두운 피부색', 'Medium dark', 'やや暗い肌'], skinTone5: ['어두운 피부색', 'Dark', '暗い肌'],
    bold: ['굵게', 'Bold', '太字'], italic: ['기울임', 'Italic', '斜体'], underline: ['밑줄', 'Underline', '下線'], strike: ['취소선', 'Strikethrough', '取り消し線'],
    bulletList: ['글머리 목록', 'Bullet list', '箇条書き'], orderedList: ['번호 목록', 'Numbered list', '番号付きリスト'],
    blockquote: ['인용', 'Quote', '引用'], horizontalRule: ['구분선', 'Divider', '区切り線'], codeBlock: ['코드', 'Code', 'コード'],
    left: ['왼쪽', 'Left', '左'], center: ['가운데', 'Center', '中央'], right: ['오른쪽', 'Right', '右'], justify: ['양쪽', 'Justify', '両端'],
    image: ['이미지', 'Image', '画像'], addImage: ['이미지 가져오기', 'Add image', '画像を追加'],
    font: ['글꼴', 'Font', 'フォント'], addFont: ['폰트 가져오기', 'Add font', 'フォントを追加'],
    assetHint: ['이미지·오디오를 본문 원하는 위치로 드래그하세요. 클릭하면 현재 커서 위치에 삽입됩니다.', 'Drag images or audio to a position in the chapter, or click to insert at the cursor.', '画像・音声を本文の好きな位置にドラッグしてください。クリックするとカーソル位置に挿入します。'],
    assetDragHint: ['본문으로 드래그하여 삽입', 'Drag into the chapter to insert', '本文にドラッグして挿入'],
    dropIntoAssets: ['파일을 놓아 자료에 등록', 'Drop files to add to Assets', 'ファイルをドロップして素材に追加'],
    dropIntoBody: ['놓은 위치에 이미지·오디오 삽입', 'Drop to insert images or audio here', 'この位置に画像・音声を挿入'],
    assetsImported: ['개 자료를 등록했습니다.', 'asset(s) added.', '件の素材を追加しました。'],
    assetsRejected: ['추가하지 못한 파일', 'Files that could not be added', '追加できなかったファイル'],
    file: ['파일', 'File', 'ファイル'],
    INVALID_ASSET_PATH: ['파일 경로를 확인할 수 없습니다. 파일 가져오기를 이용하세요.', 'The file path is unavailable. Use the import button.', 'ファイルのパスを取得できません。取り込みボタンを使用してください。'],
    INVALID_ASSET_BATCH: ['한 번에 1~100개의 파일을 추가할 수 있습니다.', 'Add 1–100 files at a time.', '一度に1〜100件のファイルを追加できます。'],
    ASSET_FILE_REQUIRED: ['폴더 대신 개별 파일을 놓아주세요.', 'Drop individual files instead of folders.', 'フォルダーではなくファイルをドロップしてください。'],
    TOO_MANY_ASSETS: ['자료는 최대 1,000개까지 등록할 수 있습니다.', 'A project can contain up to 1,000 assets.', '素材は1,000件まで追加できます。'],
    ENOENT: ['파일을 찾을 수 없습니다.', 'File not found.', 'ファイルが見つかりません。'],
    EACCES: ['파일을 읽을 권한이 없습니다.', 'The file cannot be read due to permissions.', 'ファイルを読み取る権限がありません。'],
    noAssets: ['이미지·폰트·오디오를 모아두세요.', 'Collect images, fonts and audio here.', '画像・フォント・音声をここに集めましょう。'],
    table: ['표', 'Table', '表'], addTable: ['표 삽입', 'Insert table', '表を挿入'], columns: ['2단 배치', 'Two columns', '2段組み'], column: ['열', 'Column', '列'],
    rowAfter: ['행 추가', 'Add row', '行を追加'], columnAfter: ['열 추가', 'Add column', '列を追加'], deleteRow: ['행 삭제', 'Delete row', '行を削除'], deleteColumn: ['열 삭제', 'Delete column', '列を削除'], mergeCells: ['셀 병합', 'Merge cells', 'セルを結合'], splitCell: ['셀 분할', 'Split cell', 'セルを分割'], deleteTable: ['표 삭제', 'Delete table', '表を削除'],
    link: ['링크', 'Link', 'リンク'], unlink: ['링크 제거', 'Remove link', 'リンクを削除'], linkTarget: ['링크 주소 또는 장', 'Link URL or chapter', 'URLまたは章'], apply: ['적용', 'Apply', '適用'],
    external: ['외부 주소', 'External URL', '外部URL'], internal: ['책 안의 장', 'Chapter in this book', 'この本の章'],
    selection: ['선택한 요소', 'Selection', '選択した要素'], format: ['글자와 문단', 'Text and paragraph', '文字と段落'],
    fontSize: ['글자 크기', 'Font size', '文字サイズ'], color: ['글자색', 'Text color', '文字色'], alignment: ['정렬', 'Alignment', '配置'],
    textColorHint: ['색상 칸을 더블클릭하거나 색상을 고른 뒤 적용하세요. 선택한 글자 또는 이후 입력할 글자에 적용됩니다.', 'Double-click a color swatch, or choose a color and apply it to the selection or the text you type next.', '色枠をダブルクリックするか、色を選んで適用すると、選択した文字または次に入力する文字に反映されます。'],
    defaultTextColor: ['기본 글자색으로 되돌리기', 'Reset to default text color', '既定の文字色に戻す'],
    basicColors: ['기본 색상', 'Basic colors', '基本の色'],
    customColors: ['사용자 지정 색상', 'Custom colors', 'ユーザー設定の色'],
    customColorSlot: ['사용자 색상', 'Custom color', 'ユーザー色'],
    emptyColorSlot: ['빈 색상 칸', 'Empty color slot', '空きの色枠'],
    chooseTextColor: ['색상 선택기', 'Color picker', 'カラーピッカー'],
    customColorsHint: ['최대 10개를 저장해 다른 책에서도 사용합니다. 색상 칸을 선택하면 덮어쓰기·삭제할 수 있습니다.', 'Save up to 10 colors for use across books. Select a slot to replace or delete it.', '最大10色を保存して他の本でも使えます。色枠を選ぶと上書き・削除できます。'],
    saveCustomColor: ['사용자 색상에 저장', 'Save custom color', 'ユーザー色に保存'],
    replaceCustomColor: ['선택한 색상 덮어쓰기', 'Replace selected color', '選択した色を上書き'],
    deleteCustomColor: ['저장 색상 삭제', 'Delete saved color', '保存した色を削除'],
    colorSaved: ['사용자 색상을 저장했습니다.', 'Custom color saved.', 'ユーザー色を保存しました。'],
    colorAlreadySaved: ['이미 저장된 색상입니다. 해당 색상 칸을 선택했습니다.', 'This color is already saved. Its slot is selected.', '保存済みの色です。その色枠を選択しました。'],
    colorDeleted: ['저장한 색상을 삭제했습니다. 본문 색상은 유지됩니다.', 'Saved color deleted. Document colors are unchanged.', '保存色を削除しました。本文の色は変わりません。'],
    COLOR_INVALID: ['3자리 또는 6자리 HEX 색상을 입력하세요. 예: #369, #336699', 'Enter a 3- or 6-digit HEX color, e.g. #369 or #336699.', '3桁または6桁のHEX色を入力してください。例: #369、#336699'],
    COLOR_LIMIT: ['색상 10개가 모두 등록되었습니다. 덮어쓸 색상 칸을 선택하세요.', 'All 10 slots are full. Select a color to replace.', '10色すべて登録済みです。上書きする色枠を選んでください。'],
    COLOR_STORAGE_FAILED: ['사용자 색상을 저장하지 못했습니다. 본문에는 적용할 수 있습니다.', 'Could not save custom colors. You can still apply the color to the document.', 'ユーザー色を保存できませんでした。本文への適用は可能です。'],
    width: ['너비', 'Width', '幅'], alt: ['대체 텍스트', 'Alternative text', '代替テキスト'], caption: ['이미지 설명', 'Caption', 'キャプション'], decorative: ['장식 이미지', 'Decorative image', '装飾画像'],
    reset: ['직접 서식 지우기', 'Clear formatting', '書式をクリア'],
    literary: ['문학', 'Literary', '文学'], modern: ['모던', 'Modern', 'モダン'], quiet: ['여백', 'Quiet', '余白'],
    styleHint: ['책 전체의 본문과 제목에 적용됩니다.', 'Applies to text and headings throughout the book.', '本全体の本文と見出しに適用します。'],
    serif: ['명조 계열', 'Serif', '明朝体'], sans: ['고딕 계열', 'Sans serif', 'ゴシック体'], mono: ['고정폭', 'Monospace', '等幅'],
    lineHeight: ['줄 간격', 'Line height', '行間'], paragraphGap: ['문단 간격', 'Paragraph spacing', '段落間隔'], indent: ['첫 줄 들여쓰기', 'First-line indent', '字下げ'],
    accent: ['제목·강조색', 'Heading color', '見出しの色'], background: ['배경색', 'Background', '背景色'], headingScale: ['제목 배율', 'Heading scale', '見出し倍率'],
    title: ['책 제목', 'Title', '書名'], author: ['저자', 'Author', '著者'], language: ['언어', 'Language', '言語'], publisher: ['출판사', 'Publisher', '出版社'],
    date: ['발행일', 'Publication date', '発行日'], description: ['책 소개', 'Description', '本の紹介'], rights: ['권리', 'Rights', '権利'], isbn: ['ISBN (선택)', 'ISBN (optional)', 'ISBN（任意）'],
    cover: ['표지', 'Cover', '表紙'], coverDesign: ['타이포그래피 표지', 'Typography cover', '文字を使った表紙'], coverImage: ['이미지 표지', 'Image cover', '画像の表紙'], noCover: ['표지 없음', 'No cover', '表紙なし'], subtitle: ['표지 부제', 'Cover subtitle', '表紙の副題'],
    toc: ['목차', 'Contents', '目次'], inToc: ['목차에 포함', 'Include in contents', '目次に含める'], tocTitle: ['목차 표시 이름', 'Contents label', '目次の表示名'],
    search: ['찾기·바꾸기', 'Find and replace', '検索と置換'], find: ['찾을 내용', 'Find', '検索する文字列'], replacement: ['바꿀 내용', 'Replace with', '置換する文字列'], next: ['다음 찾기', 'Find next', '次を検索'], replace: ['바꾸기', 'Replace', '置換'], replaceAll: ['현재 장 모두 바꾸기', 'Replace all in chapter', '現在の章をすべて置換'], noMatches: ['검색 결과가 없습니다.', 'No matches found.', '見つかりませんでした。'],
    inspect: ['검사', 'Check', '検査'], checked: ['기본 검사를 통과했습니다.', 'Basic checks passed.', '基本検査に合格しました。'],
    checkHint: ['기본 구조·참조 검사입니다. EPUBCheck는 실행하지 않았습니다.', 'Structure and reference checks. EPUBCheck has not been run.', '基本構造と参照の検査です。EPUBCheckは未実行です。'],
    warning: ['확인', 'Review', '確認'], failure: ['오류', 'Error', 'エラー'],
    sourceHint: ['생성되는 XHTML을 확인하는 화면입니다. 본문은 원고·책 편집에서 수정하세요.', 'Generated XHTML. Edit content in Write or Design.', '生成されるXHTMLです。本文は原稿・本の編集で変更できます。'],
    readingHint: ['독서 앱 설정에 따라 글꼴과 줄바꿈이 달라질 수 있습니다.', 'Fonts and line breaks can vary between reading apps.', '閲覧アプリの設定によりフォントや改行が変わる場合があります。'],
    narrow: ['휴대폰', 'Phone', 'スマートフォン'], medium: ['태블릿', 'Tablet', 'タブレット'], wide: ['넓게', 'Wide', 'ワイド'],
    chars: ['자', 'characters', '文字'], savedToast: ['프로젝트를 저장했습니다.', 'Project saved.', 'プロジェクトを保存しました。'], exportedToast: ['EPUB을 내보냈습니다.', 'EPUB exported.', 'EPUBを書き出しました。'], openResult: ['뷰어로 열기', 'Open in reader', 'ビューアーで開く'],
    leave: ['작업 목록', 'Projects', 'プロジェクト一覧'], unsupportedDrop: ['책을 만들거나 프로젝트를 연 뒤 이미지·오디오·폰트 파일을 놓아주세요.', 'Create or open a project before dropping image, audio or font files.', '本を作成するかプロジェクトを開いてから画像・音声・フォントをドロップしてください。'],
    browserOnly: ['저장·열기·내보내기는 BookManager 앱에서 사용할 수 있습니다.', 'Saving, opening and exporting require the BookManager app.', '保存・読み込み・書き出しはBookManagerアプリで利用できます。'],
    INVALID_PROJECT: ['프로젝트 형식이 올바르지 않습니다.', 'Invalid project format.', 'プロジェクト形式が正しくありません。'],
    PROJECT_VERSION: ['지원하지 않는 프로젝트 버전입니다.', 'Unsupported project version.', '対応していないプロジェクトバージョンです。'],
    INVALID_DOCUMENT: ['지원하지 않는 본문 구조가 있습니다.', 'Unsupported document structure.', '対応していない文書構造があります。'],
    INVALID_ASSET: ['지원하지 않거나 손상된 이미지·폰트·오디오입니다.', 'Unsupported or damaged image, font or audio.', '未対応または破損した画像・フォント・音声です。'],
    ASSET_TOO_LARGE: ['이미지·폰트·오디오는 파일당 20MB까지 지원합니다.', 'Each image, font or audio can be up to 20 MB.', '画像・フォント・音声は1ファイル20MBまでです。'],
    PROJECT_TOO_LARGE: ['프로젝트 용량 제한을 초과했습니다.', 'The project exceeds the size limit.', 'プロジェクトの容量制限を超えています。'],
    EXTERNAL_CHANGE: ['파일이 외부에서 변경되었습니다. 다른 이름으로 저장하세요.', 'The file changed outside the editor. Use Save as.', 'ファイルが外部で変更されました。名前を付けて保存してください。'],
    INVALID_TARGET: ['올바른 파일 확장자로 저장하세요.', 'Use the correct file extension.', '正しい拡張子で保存してください。'],
    ASSET_MISSING: ['프로젝트 자산 파일을 찾을 수 없습니다.', 'A project asset is missing.', 'プロジェクトの素材ファイルが見つかりません。'],
    SESSION_CLOSED: ['프로젝트를 다시 열어주세요.', 'Please reopen the project.', 'プロジェクトを開き直してください。'],
    PROJECT_BUSY: ['다른 창에서 열린 프로젝트입니다.', 'This project is open in another window.', '別のウィンドウで開かれているプロジェクトです。'],
    INVALID_LINK: ['https://, http://, mailto: 또는 책 안의 장을 선택하세요.', 'Use https://, http://, mailto: or a chapter in this book.', 'https://、http://、mailto:または本の章を選んでください。'],
    VALIDATION_FAILED: ['검사에 표시된 오류를 먼저 수정하세요.', 'Resolve the check errors before exporting.', '書き出す前に検査エラーを修正してください。'],
    TITLE_REQUIRED: ['책 제목을 입력하세요.', 'Enter a book title.', '書名を入力してください。'], LANGUAGE_REQUIRED: ['언어 코드를 확인하세요.', 'Check the language code.', '言語コードを確認してください。'],
    IDENTIFIER_REQUIRED: ['출판물 식별자가 없습니다.', 'Publication identifier is missing.', '出版物識別子がありません。'],
    AUTHOR_MISSING: ['저자를 입력하지 않았습니다.', 'Author is empty.', '著者が未入力です。'], COVER_MISSING: ['표지가 없습니다.', 'No cover is set.', '表紙がありません。'],
    TOC_EMPTY: ['목차에 한 개 이상의 장을 포함하세요.', 'Include at least one chapter in the contents.', '目次に1つ以上の章を含めてください。'],
    COVER_ASSET_MISSING: ['표지 이미지를 선택하세요.', 'Select a cover image.', '表紙画像を選択してください。'],
    FONT_MISSING: ['사용한 폰트가 없습니다.', 'A selected font is missing.', '指定したフォントがありません。'],
    CHAPTER_TITLE_REQUIRED: ['장 제목을 입력하세요.', 'Enter a chapter title.', '章のタイトルを入力してください。'],
    CHAPTER_EMPTY: ['본문이 비어 있습니다.', 'This chapter is empty.', '本文が空です。'], DUPLICATE_ID: ['중복된 요소 ID가 있습니다.', 'Duplicate element ID.', '要素IDが重複しています。'],
    IMAGE_MISSING: ['본문 이미지가 없습니다.', 'An image is missing.', '本文の画像がありません。'], ALT_MISSING: ['이미지 대체 텍스트를 입력하세요.', 'Add alternative text to this image.', '画像の代替テキストを入力してください。'],
    BROKEN_LINK: ['내부 링크의 목적지를 찾을 수 없습니다.', 'An internal link target is missing.', '内部リンクの移動先が見つかりません。'],
};

export function editorText(key) {
    return messages[key]?.[{ ko: 0, en: 1, ja: 2 }[getCurrentLanguage()] ?? 0] || messages.error[{ ko: 0, en: 1, ja: 2 }[getCurrentLanguage()] ?? 0];
}
