import { getCurrentLanguage } from '../../../utils/i18n';

const messages = {
    title: ['TTS 읽기 설정', 'TTS reading settings', 'TTS読み上げ設定'],
    intro: ['책의 표시 문장은 유지하고 낭독할 내용을 설정합니다. 이 설정은 북매니저 뷰어에서 적용됩니다.', 'Keep the displayed text and adjust what is read aloud. These settings apply in the BookManager viewer.', '表示する文章を保ちながら読み上げる内容を設定します。設定はBookManagerビューアで適用されます。'],
    selected: ['선택 영역', 'Selected text', '選択範囲'],
    chapter: ['현재 장 본문', 'Current chapter body', '現在の章の本文'],
    scope: ['미리보기 범위', 'Preview scope', 'プレビュー範囲'],
    source: ['원문', 'Original text', '原文'],
    spoken: ['실제 낭독할 내용', 'Text to be read aloud', '実際に読み上げる内容'],
    emptyPreview: ['읽을 내용이 없습니다.', 'There is no text to read.', '読み上げる内容がありません。'],
    previewLimit: ['화면에는 처음 {count}자까지 표시합니다.', 'Showing the first {count} characters.', '先頭{count}文字を表示しています。'],
    selectionMode: ['선택 영역 읽기 방식', 'How to read the selection', '選択範囲の読み方'],
    noSelection: ['본문을 선택하고 이 창을 열면 해당 부분의 읽기 방식을 지정할 수 있습니다.', 'Select text before opening this dialog to set how that part is read.', '本文を選択してからこの画面を開くと、その部分の読み方を設定できます。'],
    selectionRestricted: ['읽기 방식은 한 문단 안의 텍스트에 지정할 수 있습니다. 여러 문단, 각주 또는 코드가 포함된 선택은 미리보기만 제공합니다.', 'Reading instructions require text within one paragraph. Selections containing multiple paragraphs, footnotes or code can only be previewed.', '読み方は1つの段落内のテキストに設定できます。複数の段落、脚注、コードを含む選択はプレビューのみ可能です。'],
    selectionExpanded: ['기존 읽기 설정을 나누지 않도록 해당 설정의 전체 범위를 선택했습니다.', 'The selection was expanded to include the complete existing reading instruction.', '既存の読み方を分割しないよう、その設定の範囲全体を選択しました。'],
    selectionMixed: ['선택 영역에 여러 읽기 설정이 있습니다. 방식을 선택하면 전체 선택 영역에 적용합니다.', 'The selection has mixed reading instructions. Choose a mode to apply it to the whole selection.', '選択範囲に複数の読み方があります。方式を選ぶと選択範囲全体に適用されます。'],
    auto: ['자동', 'Automatic', '自動'],
    read: ['원문대로 읽기', 'Read original text', '原文どおりに読む'],
    replace: ['대체 문장 읽기', 'Read replacement', '代替文を読む'],
    skip: ['읽지 않기', 'Skip', '読み飛ばす'],
    autoHint: ['선택 영역의 별도 설정을 해제합니다. 발음 사전과 기본 괄호·기호 정리를 적용합니다.', 'Remove the selection’s instruction and use the dictionary and default bracket and symbol cleanup.', '選択範囲の個別設定を解除し、発音辞書と標準の括弧・記号の整理を適用します。'],
    readHint: ['발음 사전과 괄호·기호 정리를 적용하지 않고 원문을 음성에 전달합니다.', 'Send the original text to the voice without dictionary substitutions or bracket and symbol cleanup.', '発音辞書や括弧・記号の整理を適用せず、原文を音声に渡します。'],
    replaceHint: ['선택 영역 대신 입력한 문장을 한 번 읽습니다.', 'Read the entered text once in place of the selection.', '選択範囲の代わりに入力した文を1回読みます。'],
    skipHint: ['선택 영역은 화면에 남겨두고 낭독에서 생략합니다.', 'Keep the selection visible and omit it from reading.', '選択範囲の表示は維持し、読み上げでは省略します。'],
    replacement: ['대체할 낭독 문장', 'Replacement reading text', '代わりに読み上げる文'],
    replacementPlaceholder: ['예: 현재 체력은 백입니다.', 'For example: Current health is one hundred.', '例：現在の体力は百です。'],
    dictionary: ['이 책의 발음 사전', 'Pronunciation dictionary for this book', 'この本の発音辞書'],
    dictionaryHint: ['일치하는 원문을 낭독할 때만 바꿉니다. 대소문자를 구분하며 긴 항목부터 적용합니다. 선택 영역의 읽기 설정이 사전보다 우선합니다.', 'Replace matching text only when reading. Matching is case-sensitive and longer entries take priority. Selection instructions override the dictionary.', '一致する原文を読み上げるときだけ置き換えます。大文字・小文字を区別し、長い項目を優先します。選択範囲の設定が辞書より優先されます。'],
    dictionaryEmptyState: ['등록한 발음이 없습니다. 자주 나오는 이름이나 약어를 추가하세요.', 'No entries yet. Add recurring names or abbreviations.', '登録した発音がありません。よく出る名前や略語を追加してください。'],
    dictionarySource: ['원문 단어·문구', 'Original word or phrase', '原文の単語・語句'],
    dictionaryReplacement: ['읽을 발음', 'Read as', '読み方'],
    add: ['발음 추가', 'Add pronunciation', '発音を追加'],
    remove: ['발음 삭제', 'Remove pronunciation', '発音を削除'],
    systemPreview: ['시스템 음성으로 미리 듣기', 'Preview with system voice', 'システム音声で試聴'],
    systemHint: ['이 미리 듣기는 시스템 음성을 사용합니다. 다른 TTS 음성은 설정 적용 후 북매니저 뷰어에서 확인하세요.', 'This preview uses the system voice. After applying, use the BookManager viewer to check other TTS voices.', 'この試聴ではシステム音声を使用します。他のTTS音声は設定を適用後、BookManagerビューアで確認してください。'],
    speechLimit: ['미리 듣기는 처음 {count}자까지 재생합니다.', 'Audio preview reads the first {count} characters.', '試聴では先頭{count}文字まで再生します。'],
    unsupported: ['이 환경에서는 시스템 음성 미리 듣기를 사용할 수 없습니다. 북매니저 뷰어에서 확인하세요.', 'System voice preview is unavailable here. Check in the BookManager viewer.', 'この環境ではシステム音声の試聴を利用できません。BookManagerビューアで確認してください。'],
    speechError: ['시스템 음성을 재생하지 못했습니다. 음성 설정을 확인하거나 북매니저 뷰어에서 확인하세요.', 'System voice playback failed. Check your voice settings or use the BookManager viewer.', 'システム音声を再生できませんでした。音声設定を確認するか、BookManagerビューアを利用してください。'],
    stop: ['미리 듣기 정지', 'Stop preview', '試聴を停止'],
    playing: ['시스템 음성으로 읽는 중', 'Reading with system voice', 'システム音声で読み上げ中'],
    viewer: ['북매니저 뷰어에서 확인', 'Check in BookManager viewer', 'BookManagerビューアで確認'],
    applyFirst: ['변경한 설정을 적용한 뒤 뷰어에서 확인할 수 있습니다.', 'Apply your changes before checking them in the viewer.', '変更した設定を適用してからビューアで確認できます。'],
    dictionaryLimit: ['발음 사전은 최대 500개까지 등록할 수 있습니다.', 'The dictionary can contain up to 500 entries.', '発音辞書には最大500件まで登録できます。'],
    dictionaryEmpty: ['발음 사전의 원문과 읽을 발음을 모두 입력하거나 빈 항목을 삭제하세요.', 'Fill in both fields for each dictionary entry or remove the empty entry.', '辞書の原文と読み方を両方入力するか、空の項目を削除してください。'],
    dictionaryDuplicate: ['발음 사전에 같은 원문이 중복되어 있습니다. 하나만 남겨주세요.', 'The dictionary contains duplicate original text. Keep only one entry.', '辞書に同じ原文が重複しています。1件だけ残してください。'],
    dictionaryLength: ['사전의 원문은 200자, 읽을 발음은 2,000자까지 입력할 수 있습니다.', 'Dictionary sources allow 200 characters and readings allow 2,000.', '辞書の原文は200文字、読み方は2,000文字まで入力できます。'],
    replacementEmpty: ['대체할 낭독 문장을 입력하세요. 생략하려면 읽지 않기를 선택하세요.', 'Enter replacement text. To omit this part, choose Skip.', '代わりに読む文を入力してください。省略する場合は「読み飛ばす」を選んでください。'],
    replacementLength: ['대체할 낭독 문장은 2,000자까지 입력할 수 있습니다.', 'Replacement reading text can contain up to 2,000 characters.', '代わりに読む文は2,000文字まで入力できます。'],
    invalidText: ['지원하지 않는 제어 문자가 있습니다. 입력한 문장을 확인하세요.', 'The text contains unsupported control characters. Check your input.', '未対応の制御文字が含まれています。入力した文を確認してください。'],
    error: ['읽기 설정을 적용하지 못했습니다. 내용을 확인하고 다시 시도하세요.', 'Could not apply reading settings. Check the entries and try again.', '読み上げ設定を適用できませんでした。内容を確認して再試行してください。'],
};

export function ttsText(key) {
    return (messages[key] || messages.error)[{ ko: 0, en: 1, ja: 2 }[getCurrentLanguage()] ?? 0];
}
