import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { getSchema } from '@tiptap/core';
import StarterKit from '@tiptap/starter-kit';
import { EditorState } from '@tiptap/pm/state';
import { ParagraphIndent } from '../src/features/fileTools/epubEditor/paragraphIndent.js';
import { importTextChapters } from '../src/features/fileTools/epubEditor/chapterOperations.js';
import { EpubEditorService } from './epubEditor/service.js';
import { textContent, validateProject } from './epubEditor/model.js';
import { listZipEntries, readZipEntry } from './core/zipArchive.js';

const hash = value => createHash('sha256').update(value).digest('hex');
const bookText = project => project.chapters.map(chapter => textContent(chapter.content)).join('\n');

test('20 MiB TXT with over 200,000 nodes survives worker import, recovery, save, reopen and EPUB export', async t => {
    const root = await fs.mkdtemp(path.join(os.tmpdir(), 'bookmanager-large-txt-'));
    const service = new EpubEditorService(path.join(root, 'work'));
    t.after(async () => { await service.dispose(); await fs.rm(root, { recursive: true, force: true }); });
    const line = `${'가나다라마바사아자차카타파하'.repeat(4)} <>& 끝\n\n`;
    const source = `${line.repeat(Math.ceil(20 * 1024 * 1024 / Buffer.byteLength(line)))}마지막 본문`;
    const expectedHash = hash(source);
    const filePath = path.join(root, '큰 원고.txt');
    await fs.writeFile(filePath, source);
    const session = await service.create(1, 'blank', 'ko');
    const started = performance.now();
    const read = await service.readText(1, session.sessionId, { filePath, operationId: 'large-read' });
    assert.equal(read.error, undefined);
    assert.ok(read.paragraphs > 200000);
    assert.equal(read.preview.length, 4000);
    assert.equal(read.characters, source.length);
    const schema = getSchema([StarterKit, ParagraphIndent]);
    const state = EditorState.create({ schema, doc: schema.nodeFromJSON(session.project.chapters[0].content) });
    const result = importTextChapters(session.project.chapters, session.project.chapters[0].id, state, read.document, read.title, 'chapter', 1);
    const project = { ...session.project, revision: 1, chapters: result.chapters };
    assert.equal(project.chapters.length, read.chapterCount);
    assert.ok(project.chapters.every(chapter => chapter.content.content.length <= 1000));
    assert.ok(Buffer.byteLength(JSON.stringify(project)) > 16 * 1024 * 1024);
    validateProject(project);
    assert.equal(hash(bookText(project)), expectedHash);
    const importedAt = performance.now();
    await service.recovery(1, session.sessionId, project);
    await service.close(1, session.sessionId);
    const restored = await service.restore(1, session.sessionId);
    assert.equal(hash(bookText(restored.project)), expectedHash);
    const savedPath = path.join(root, 'large.bmepub');
    await service.write(1, restored.sessionId, restored.project, savedPath, 'save', 'large-save');
    await service.close(1, restored.sessionId);
    const reopened = await service.open(1, savedPath, 'large-open');
    assert.equal(hash(bookText(reopened.project)), expectedHash);
    const epubPath = path.join(root, 'large.epub');
    await service.write(1, reopened.sessionId, reopened.project, epubPath, 'export', 'large-export');
    const bytes = await fs.readFile(epubPath);
    const entries = listZipEntries(bytes);
    const chapters = reopened.project.chapters.map(chapter => readZipEntry(bytes, entries.find(entry => entry.name === `EPUB/text/${chapter.id}.xhtml`)).toString());
    assert.equal(chapters.length, read.chapterCount);
    assert.ok(chapters[0].includes('&lt;&gt;&amp; 끝'));
    assert.ok(chapters.at(-1).includes('마지막 본문'));
    assert.equal(chapters.reduce((count, xhtml) => count + (xhtml.match(/<p[ >]/g) || []).length, 0), read.paragraphs);
    t.diagnostic(`source=${Buffer.byteLength(source)} bytes, paragraphs=${read.paragraphs}, chapters=${read.chapterCount}, import=${Math.round(importedAt - started)}ms, complete=${Math.round(performance.now() - started)}ms`);
});
