import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.join(root, '..');
const viewerWindowSource = readFileSync(path.join(root, 'viewerWindow.js'), 'utf8');
const viewerSessionSource = readFileSync(path.join(root, 'viewerSessions.js'), 'utf8');
const viewerPreloadSource = readFileSync(path.join(root, 'viewerPreload.cjs'), 'utf8');
const preloadSource = readFileSync(path.join(root, 'preload.cjs'), 'utf8');
const ipcHandlersSource = readFileSync(path.join(root, 'ipcHandlers.js'), 'utf8');
const mainSource = readFileSync(path.join(root, 'main.js'), 'utf8');
const folderTabSource = readFileSync(path.join(projectRoot, 'src', 'tabs', 'FolderTab.jsx'), 'utf8');
const appEntrySource = readFileSync(path.join(projectRoot, 'src', 'main.jsx'), 'utf8');
const viewerAppSource = readFileSync(path.join(projectRoot, 'src', 'ViewerApp.jsx'), 'utf8');
const viewerStyleSource = readFileSync(path.join(projectRoot, 'src', 'styles', 'viewer.css'), 'utf8');
const indexSource = readFileSync(path.join(projectRoot, 'index.html'), 'utf8');
const i18nSource = readFileSync(path.join(projectRoot, 'src', 'utils', 'i18n.js'), 'utf8');
const packageSource = readFileSync(path.join(projectRoot, 'package.json'), 'utf8');

test('내부 뷰어는 모달이 아니라 단일 BrowserWindow를 재사용한다', () => {
    assert.match(viewerWindowSource, /let viewerWindow = null/);
    assert.match(viewerWindowSource, /if \(viewerWindow && !viewerWindow\.isDestroyed\(\)\) return viewerWindow/);
    assert.match(viewerWindowSource, /viewerWindow = new BrowserWindow/);
    assert.match(viewerWindowSource, /title:\s*'BookManagerViewer'/);
    assert.match(viewerWindowSource, /setTitle\(`BookManagerViewer - \$\{path\.basename\(session\.filePath\)\}`\)/);
    assert.match(viewerWindowSource, /ipcMain\.handle\('viewer:open'/);
    assert.match(viewerWindowSource, /webContents\.send\('viewer:load-session'/);
    assert.match(viewerWindowSource, /isLoadingMainFrame/);
    assert.match(viewerWindowSource, /plugins:\s*true/);
    assert.match(viewerWindowSource, /protocol\.handle\('bookmanager-comic'/);
    assert.match(viewerWindowSource, /protocol\.handle\('bookmanager-document'/);
    assert.match(mainSource, /setupViewerWindowManager/);
    assert.match(mainSource, /viewerWindow\.close\(\)/);
    assert.doesNotMatch(viewerWindowSource, /modal:\s*true/);
});

test('메인 앱은 포맷별 외부 뷰어를 우선 사용하고 기본 뷰어 fallback은 사용하지 않는다', () => {
    assert.match(preloadSource, /openInternalViewer:\s*\(filePath\) => ipcRenderer\.invoke\('viewer:open', filePath\)/);
    assert.match(folderTabSource, /const explicitViewerPath = typeSpecificViewerPath\(config,\s*target\)/);
    assert.match(folderTabSource, /openWithViewer\?\.\(explicitViewerPath,\s*target\)/);
    assert.match(folderTabSource, /openInternalViewer\?\.\(target\)/);
    assert.match(folderTabSource, /if \(internalResult\?\.success\) return/);
    assert.doesNotMatch(folderTabSource, /const defaultViewerPath = configuredViewerPath\(config\?\.viewer_path\)/);
    assert.doesNotMatch(folderTabSource, /openWithViewer\?\.\(defaultViewerPath,\s*target\)/);
});

test('뷰어 창은 같은 React 번들의 전용 viewer 모드로 로드된다', () => {
    assert.match(viewerWindowSource, /\?viewer=1/);
    assert.match(viewerWindowSource, /loadFile\(distIndexPath,\s*\{\s*query:\s*\{\s*viewer:\s*'1'\s*\}\s*\}\)/);
    assert.match(appEntrySource, /get\('viewer'\) === '1'/);
    assert.match(appEntrySource, /import\('\.\/ViewerApp\.jsx'\)/);
    assert.match(appEntrySource, /renderRoot\(App\)/);
    assert.doesNotMatch(appEntrySource, /import ViewerApp from/);
    assert.match(indexSource, /frame-src[^;]*data:/);
    assert.match(indexSource, /frame-src[^;]*bookmanager-document:/);
    assert.match(indexSource, /img-src[^;]*bookmanager-comic:/);
    assert.match(indexSource, /img-src[^;]*bookmanager-document:/);
    assert.match(indexSource, /font-src[^;]*bookmanager-document:/);
});

test('뷰어 창은 F12와 Ctrl/Cmd+Shift+I로 개발자 도구를 토글한다', () => {
    assert.match(viewerWindowSource, /before-input-event/);
    assert.match(viewerWindowSource, /key === 'f12'/);
    assert.match(viewerWindowSource, /process\.platform === 'darwin' \? input\.meta : input\.control/);
    assert.match(viewerWindowSource, /primaryModifier && input\.shift && key === 'i'/);
    assert.match(viewerWindowSource, /isDevToolsOpened\(\)/);
    assert.match(viewerWindowSource, /openDevTools\(\{\s*mode:\s*'detach'\s*\}\)/);
    assert.match(viewerWindowSource, /closeDevTools\(\)/);
});

test('뷰어 창 위치와 크기는 config에 저장하고 다음 실행에 복원한다', () => {
    assert.match(viewerWindowSource, /resolveViewerWindowState/);
    assert.match(viewerWindowSource, /viewer_width/);
    assert.match(viewerWindowSource, /viewer_height/);
    assert.match(viewerWindowSource, /viewer_x/);
    assert.match(viewerWindowSource, /viewer_y/);
    assert.match(viewerWindowSource, /viewer_is_maximized/);
    assert.match(viewerWindowSource, /screen\.getPrimaryDisplay\(\)/);
    assert.match(viewerWindowSource, /screen\.getAllDisplays\(\)/);
    assert.match(viewerWindowSource, /configManager\?\.getConfig\?\.\(\)/);
    assert.match(viewerWindowSource, /\.\.\.windowState\.bounds/);
    assert.match(viewerWindowSource, /minWidth: windowState\.minWidth/);
    assert.match(viewerWindowSource, /minHeight: windowState\.minHeight/);
    assert.match(viewerWindowSource, /if \(windowState\.isMaximized\)/);
    assert.match(viewerWindowSource, /serializeViewerWindowState/);
    assert.match(viewerWindowSource, /configManager\.updateConfig\(serializeViewerWindowState\(viewerWindow\)\)/);
    assert.match(viewerWindowSource, /viewerWindow\.on\('resize', scheduleViewerWindowStateSave\)/);
    assert.match(viewerWindowSource, /viewerWindow\.on\('move', scheduleViewerWindowStateSave\)/);
    assert.match(viewerWindowSource, /viewerWindow\.on\('close', saveViewerWindowState\)/);
    assert.match(mainSource, /configManager,/);
});

test('뷰어는 Enter와 본문 더블클릭으로 창 전체화면을 토글한다', () => {
    assert.match(viewerWindowSource, /ipcMain\.handle\('viewer:toggleFullscreen'/);
    assert.match(viewerWindowSource, /BrowserWindow\.fromWebContents\(event\.sender\)/);
    assert.match(viewerWindowSource, /const nextFullscreen = !targetWindow\.isFullScreen\(\)/);
    assert.match(viewerWindowSource, /targetWindow\.setFullScreen\(nextFullscreen\)/);
    assert.match(viewerWindowSource, /ipcMain\.handle\('viewer:getFullscreenState'/);
    assert.match(viewerWindowSource, /viewer:fullscreen-change/);
    assert.match(viewerPreloadSource, /toggleFullscreen:\s*\(\) => ipcRenderer\.invoke\('viewer:toggleFullscreen'\)/);
    assert.match(viewerPreloadSource, /getFullscreenState:\s*\(\) => ipcRenderer\.invoke\('viewer:getFullscreenState'\)/);
    assert.match(viewerPreloadSource, /onFullscreenChange/);
    assert.match(viewerAppSource, /const toggleFullscreen = useCallback/);
    assert.match(viewerAppSource, /window\.viewerAPI\?\.toggleFullscreen\?\.\(\)/);
    assert.match(viewerAppSource, /const \[isFullscreen, setIsFullscreen\] = useState\(false\)/);
    assert.match(viewerAppSource, /active=\{isFullscreen\}/);
    assert.match(viewerAppSource, /const isViewerInteractiveTarget = useCallback/);
    assert.match(viewerAppSource, /'input', 'select', 'textarea', 'button', 'a'/);
    assert.match(viewerAppSource, /const restoreViewerFocus = useCallback/);
    assert.match(viewerAppSource, /scrollRef\.current\?\.focus\?\.\(\{\s*preventScroll:\s*true\s*\}\)/);
    assert.match(viewerAppSource, /onMouseDown=\{event => \{\s*if \(event\.button === 0\) event\.preventDefault\(\);/);
    assert.match(viewerAppSource, /className="viewer-slide-toggle"[\s\S]*?onClick=\{runToolbarAction\(\(\) => setSlideNavOpen\(current => !current\)\)\}/);
    assert.match(viewerAppSource, /onClose=\{runToolbarAction\(\(\) => setNavigationPanelOpen\(false\)\)\}/);
    assert.match(viewerAppSource, /onClose=\{runToolbarAction\(\(\) => setSettingsOpen\(false\)\)\}/);
    assert.match(viewerAppSource, /const isViewerShortcutBlockedTarget = useCallback/);
    assert.match(viewerAppSource, /if \(shortcutsBlockedByOverlay \|\| isViewerShortcutBlockedTarget\(event\.target\)\) return/);
    assert.match(viewerAppSource, /event\.key === 'F11'/);
    assert.match(viewerAppSource, /event\.key === 'Enter' && !event\.repeat/);
    assert.match(viewerAppSource, /onDoubleClick=\{handleContentDoubleClick\}/);
    assert.match(viewerAppSource, /tabIndex=\{-1\}/);
    assert.match(viewerAppSource, /\.viewer-toolbar, \.viewer-slide-nav/);
});

test('뷰어 preload는 세션과 포맷별 읽기 API만 노출한다', () => {
    assert.match(viewerPreloadSource, /contextBridge\.exposeInMainWorld\('viewerAPI'/);
    assert.match(viewerPreloadSource, /listComicPages/);
    assert.match(viewerPreloadSource, /getComicPage/);
    assert.match(viewerPreloadSource, /getDocumentData/);
    assert.match(viewerPreloadSource, /getText/);
    assert.match(viewerPreloadSource, /getEpubText/);
    assert.match(viewerPreloadSource, /getConfig:\s*\(\) => ipcRenderer\.invoke\('viewer:getConfig'\)/);
    assert.match(viewerPreloadSource, /openExternal:\s*url => ipcRenderer\.invoke\('viewer:openExternal', url\)/);
    assert.match(viewerPreloadSource, /onConfigChange/);
    assert.match(viewerPreloadSource, /openAdjacent/);
    assert.match(viewerPreloadSource, /toggleFullscreen/);
    assert.match(viewerPreloadSource, /getFullscreenState/);
    assert.match(viewerPreloadSource, /onFullscreenChange/);
    assert.doesNotMatch(viewerPreloadSource, /deleteFiles|renameFile|saveConfig/);
});

test('뷰어 공통 UI 문구는 다국어 키를 통해 표시한다', () => {
    assert.match(viewerAppSource, /function viewerText/);
    assert.match(viewerAppSource, /import \{ getCurrentLanguage, setLanguage, translate \} from '\.\/utils\/i18n'/);
    assert.match(viewerWindowSource, /ipcMain\.handle\('viewer:getConfig'/);
    assert.match(viewerWindowSource, /const language = config\.language \|\| config\.lang \|\| 'ko'/);
    assert.match(viewerWindowSource, /hasTtsOpenAiKey/);
    assert.match(viewerWindowSource, /hasTtsGoogleKey/);
    assert.match(viewerAppSource, /const \[viewerLanguage, setViewerLanguage\] = useState\(getCurrentLanguage\(\)\)/);
    assert.match(viewerAppSource, /window\.viewerAPI\?\.getConfig\?\.\(\)/);
    assert.match(viewerAppSource, /window\.viewerAPI\?\.onConfigChange\?\./);
    assert.match(viewerAppSource, /setLanguage\(config\?\.language \|\| config\?\.lang \|\| 'ko'\)/);
    assert.match(viewerAppSource, /lang-\$\{viewerLanguage\}/);
    assert.match(viewerAppSource, /lang=\{viewerLanguage\}/);
    assert.match(ipcHandlersSource, /viewer:config-change/);
    assert.match(ipcHandlersSource, /BrowserWindow\.getAllWindows\(\)\.forEach/);
    assert.match(viewerAppSource, /viewerText\(selected\.labelKey, selected\.label\)/);
    assert.match(viewerAppSource, /viewerText\(option\.labelKey, option\.label\)/);
    assert.match(viewerAppSource, /viewer\.fit\.width/);
    assert.match(viewerAppSource, /viewer\.read_mode\.single/);
    assert.match(viewerAppSource, /viewer\.background_color\.white/);
    assert.match(viewerAppSource, /viewer\.zoom\.title/);
    assert.match(viewerAppSource, /viewer\.bookmark\.add/);
    assert.match(viewerAppSource, /viewer\.context\.add_highlight/);
    assert.match(viewerAppSource, /viewer\.toolbar\.help/);
    assert.match(viewerAppSource, /viewer\.help\.title/);
    assert.match(viewerAppSource, /viewer\.help\.context_open/);
    assert.match(viewerAppSource, /viewer\.toast\.next_book_hint/);
    assert.match(i18nSource, /fit:\s*\{[\s\S]*?width: '가로 맞춤'[\s\S]*?actual: '원본 크기'/);
    assert.match(i18nSource, /fit:\s*\{[\s\S]*?width: 'Fit width'[\s\S]*?actual: 'Actual size'/);
    assert.match(i18nSource, /fit:\s*\{[\s\S]*?width: '幅に合わせる'[\s\S]*?actual: '原寸'/);
    assert.match(i18nSource, /read_mode:\s*\{[\s\S]*?single: '한장보기모드'[\s\S]*?scroll: '스크롤모드'/);
    assert.match(i18nSource, /zoom:\s*\{[\s\S]*?title: '확대\/축소'/);
    assert.match(i18nSource, /shortcut_zoom: '확대\/축소 배율을 조절합니다\. Ctrl\+마우스휠/);
    assert.match(i18nSource, /shortcut_zoom: 'Adjust the zoom ratio\. You can also use Ctrl\+mouse wheel/);
    assert.match(i18nSource, /shortcut_zoom: 'ズーム倍率を調整します。Ctrl\+マウスホイール/);
    assert.match(i18nSource, /bookmark:\s*\{[\s\S]*?add: '책갈피 추가 \(B\)'/);
    assert.match(i18nSource, /context:\s*\{[\s\S]*?add_highlight: '하이라이트 추가'/);
    assert.match(i18nSource, /toast:\s*\{[\s\S]*?next_book_hint: '마지막 페이지입니다\./);
    assert.match(i18nSource, /toast:\s*\{[\s\S]*?next_book_hint: 'This is the last page\./);
    assert.match(i18nSource, /toast:\s*\{[\s\S]*?next_book_hint: '最後のページです。/);
    assert.match(i18nSource, /help:\s*\{[\s\S]*?title: '뷰어 사용법'[\s\S]*?tab_shortcuts: '단축키'/);
    assert.match(i18nSource, /context_open: '텍스트를 드래그하면 선택이 끝난 지점에 플로팅 툴바가 나옵니다\./);
    assert.doesNotMatch(i18nSource, /context_select_title/);
    assert.doesNotMatch(i18nSource, /context_right_click_title/);
    assert.match(i18nSource, /help:\s*\{[\s\S]*?title: 'Viewer Help'[\s\S]*?tab_shortcuts: 'Shortcuts'/);
    assert.match(i18nSource, /help:\s*\{[\s\S]*?title: 'ビューアの使い方'[\s\S]*?tab_shortcuts: 'ショートカット'/);
});

test('EPUB CSS는 안전한 스타일 객체로만 뷰어에 전달된다', () => {
    assert.match(viewerSessionSource, /function sanitizeEpubCssDeclarationBlock/);
    assert.match(viewerSessionSource, /function sanitizeEpubCssForViewer/);
    assert.match(viewerSessionSource, /function sanitizeEpubCssSelectorForViewer/);
    assert.match(viewerSessionSource, /viewer-reader-scope/);
    assert.match(viewerSessionSource, /EPUB_CSS_UNSAFE_VALUE_PATTERN/);
    assert.match(viewerSessionSource, /EPUB_CSS_SELECTOR_UNSAFE_PATTERN/);
    assert.match(viewerSessionSource, /EPUB_VIEWER_CONTROLLED_CSS_PROPERTIES/);
    assert.match(viewerSessionSource, /'background'/);
    assert.match(viewerSessionSource, /'line-height'/);
    assert.match(viewerSessionSource, /'writing-mode'/);
    assert.match(viewerSessionSource, /'word-break'/);
    assert.doesNotMatch(viewerSessionSource, /'margin',\s*[\r\n]+\s*'margin-bottom'/);
    assert.doesNotMatch(viewerSessionSource, /'padding',\s*[\r\n]+\s*'padding-bottom'/);
    assert.doesNotMatch(viewerSessionSource, /'text-align',\s*[\r\n]+\s*'text-align-last'/);
    assert.match(viewerSessionSource, /\['text-align-last', 'textAlignLast'\]/);
    assert.match(viewerSessionSource, /function sanitizeCssFontSizeValue/);
    assert.match(viewerSessionSource, /function sanitizeCssFontValue/);
    assert.match(viewerSessionSource, /case 'font':[\s\S]*?return sanitizeCssFontValue/);
    assert.match(viewerSessionSource, /case 'font-size':[\s\S]*?return sanitizeCssFontSizeValue/);
    assert.doesNotMatch(viewerSessionSource, /EPUB_FONT_SCALE_OFFSET/);
    assert.doesNotMatch(viewerSessionSource, /EPUB_FONT_CUSTOM_PROPERTY_OFFSET/);
    assert.doesNotMatch(viewerSessionSource, /--viewer-epub-font-scale/);
    assert.match(viewerSessionSource, /EPUB_VIEWER_CONTROLLED_CSS_PROPERTIES\.has\(property\)/);
    assert.match(viewerSessionSource, /readEpubCssRulesForHtml/);
    assert.match(viewerSessionSource, /stylesheetTexts/);
    assert.match(viewerSessionSource, /epubFontFaceStylesheet/);
    assert.match(viewerSessionSource, /stylesheet: \[fontStylesheet, \.\.\.Array\.from\(stylesheetTexts\)\]\.filter\(Boolean\)\.join\('\\n'\)/);
    assert.match(viewerSessionSource, /epubStyleForElement/);
    assert.match(viewerSessionSource, /parseSafeEpubHtmlNodes/);
    assert.match(viewerSessionSource, /EPUB_ALLOWED_HTML_TAGS/);
    assert.match(viewerSessionSource, /parseEpubInternalHref/);
    assert.match(viewerSessionSource, /targetEntryName/);
    assert.match(viewerSessionSource, /sanitizeEpubExternalHref/);
    assert.match(viewerSessionSource, /externalHref/);
    assert.match(viewerSessionSource, /epubAnchorsFromNodes/);
    assert.match(viewerSessionSource, /safeEpubHtmlAttributes/);
    assert.match(viewerSessionSource, /colSpan/);
    assert.match(viewerSessionSource, /rowSpan/);
    assert.match(viewerSessionSource, /findImageEntryForHref/);
    assert.match(viewerSessionSource, /decodeEpubUrl/);
    assert.match(viewerSessionSource, /removeHiddenDisplayForEpubImages/);
    assert.match(viewerSessionSource, /FONT_EXTENSIONS/);
    assert.match(viewerSessionSource, /fontMime/);
    assert.match(viewerSessionSource, /readEpubFontFacesFromStylesheets/);
    assert.match(viewerAppSource, /function renderEpubHtmlNode/);
    assert.match(viewerAppSource, /const \[epubStylesheet, setEpubStylesheet\] = useState\(''\)/);
    assert.match(viewerAppSource, /setEpubStylesheet\(typeof result\.stylesheet === 'string' \? result\.stylesheet : ''\)/);
    assert.match(viewerAppSource, /<style>\{epubStylesheet\}<\/style>/);
    assert.match(viewerAppSource, /fontOptionsFromGroups/);
    assert.match(viewerAppSource, /const \[fontGroups, setFontGroups\] = useState/);
    assert.match(viewerAppSource, /result\.fonts/);
    assert.match(viewerAppSource, /viewer\.settings\.font_group_epub/);
    assert.match(viewerAppSource, /const epubPageIndexByTarget = useMemo/);
    assert.match(viewerAppSource, /const goEpubInternalTarget = useCallback/);
    assert.match(viewerAppSource, /const openExternalLink = useCallback/);
    assert.match(viewerAppSource, /window\.viewerAPI\.openExternal\(safeUrl\)/);
    assert.match(viewerAppSource, /data-epub-anchor/);
    assert.match(viewerAppSource, /viewer-reader-html-link/);
    assert.match(viewerAppSource, /\.\.\.\(node\.attributes \|\| \{\}\)/);
    assert.match(viewerAppSource, /viewer-text-page viewer-reader-scope/);
    assert.match(viewerAppSource, /READER_ALLOWED_HTML_TAGS/);
    assert.match(viewerAppSource, /function readerPaginationMetrics/);
    assert.match(viewerAppSource, /function estimateReaderMediaLineCost/);
    assert.match(viewerAppSource, /function splitReaderTextForRemainingPage/);
    assert.match(viewerAppSource, /function splitReaderLineForPage/);
    assert.match(viewerAppSource, /widowLineTolerance/);
    assert.match(viewerAppSource, /overflowTolerance/);
    assert.match(viewerAppSource, /READER_MIXED_IMAGE_HEIGHT_RATIO = 0\.62/);
    assert.match(viewerAppSource, /READER_MIXED_IMAGE_LINE_RATIO = 0\.58/);
    assert.match(viewerAppSource, /READER_INLINE_IMAGE_LINE_RATIO = 0\.18/);
    assert.match(viewerAppSource, /mediaLineCost/);
    assert.match(viewerAppSource, /mixedImageMaxHeight/);
    assert.match(viewerAppSource, /function readerCssLengthToPixels/);
    assert.match(viewerAppSource, /function readerImageNodesFromBlock/);
    assert.match(viewerAppSource, /function cloneReaderNodeWithImagesOnly/);
    assert.match(viewerAppSource, /function readerImageOnlyNodesFromBlock/);
    assert.match(viewerAppSource, /function estimateReaderInlineImageLineCost/);
    assert.match(viewerAppSource, /function estimateReaderImageNodeLineCost/);
    assert.match(viewerAppSource, /const naturalWidth = Math\.max\(0, Number\(node\.naturalWidth\)/);
    assert.match(viewerAppSource, /const widthConstrainedHeight = naturalWidth > 0 && naturalHeight > 0/);
    assert.match(viewerAppSource, /lineAdvance: Math\.max\(10, Number\(settings\.lineAdvance\) \|\| 18\)/);
    assert.match(viewerAppSource, /pageWidth: Math\.max\(160, Number\(settings\.pageWidth\) \|\| 560\)/);
    assert.match(viewerAppSource, /fontSize: Math\.max\(10, Number\(settings\.fontSize\) \|\| 16\)/);
    assert.match(viewerAppSource, /currentPageBlocks/);
    assert.match(viewerAppSource, /addPackedBlock/);
    assert.match(viewerAppSource, /addSplittableTextBlock/);
    assert.match(viewerAppSource, /src: block\.src/);
    assert.match(viewerAppSource, /alt: block\.alt/);
    assert.match(viewerAppSource, /currentPageBlocks\.some\(pageBlock => pageBlock\.hasImage\)/);
    assert.match(viewerAppSource, /if \(currentPageBlocks\.length === 0 && lineCost > metrics\.lineBudget\)/);
    assert.match(viewerAppSource, /currentPageBlocks\.length > 0 && lineCost > remainingLines && remainingLines >= 1/);
    assert.match(viewerAppSource, /overflowTolerance: metrics\.widowLineTolerance/);
    assert.match(viewerAppSource, /lineCost: estimateReaderMediaLineCost\(metrics, block\)/);
    assert.match(viewerAppSource, /lineCost: estimateReaderMediaLineCost\(metrics, block\)/);
    assert.match(viewerAppSource, /const imageOnlyNodes = readerImageOnlyNodesFromBlock\(block\)/);
    assert.match(viewerAppSource, /addSplittableTextBlock\(textOnlyBlock, text, false\)/);
    assert.match(viewerAppSource, /lineCost: mediaLineCost/);
    assert.match(viewerAppSource, /estimateReaderInlineImageLineCost\(block, metrics\) \+ estimateReaderBlockLineCost\(text, metrics\)/);
    assert.match(viewerAppSource, /String\(block\?\.tagName \|\| ''\)\.toLowerCase\(\) === 'hr'/);
    assert.match(viewerSessionSource, /if \(node\.tagName === 'img'\) return ''/);
    assert.match(viewerSessionSource, /function imageDimensionsFromBuffer/);
    assert.match(viewerSessionSource, /async function readEpubImageDimensionMap/);
    assert.match(viewerSessionSource, /naturalWidth: imageDimensions\?\.width/);
    assert.match(viewerSessionSource, /naturalHeight: imageDimensions\?\.height/);
    assert.match(viewerAppSource, /standaloneImage/);
    assert.match(viewerAppSource, /mediaOnly/);
    assert.match(viewerAppSource, /const READER_TITLE_ONLY_TAGS = new Set\(\['h1', 'h2', 'h3', 'h4', 'h5', 'h6'\]\)/);
    assert.match(viewerAppSource, /function isReaderStandaloneImagePage/);
    assert.match(viewerAppSource, /mediaBlocks\.length !== 1/);
    assert.match(viewerAppSource, /function readerBlockPreventsImageExpansion/);
    assert.match(viewerAppSource, /readerStylePreventsImageExpansion\(block\.style\)/);
    assert.match(viewerAppSource, /readerSizeValuePreventsImageExpansion\(style\[propertyName\], propertyName\)/);
    assert.match(viewerAppSource, /if \(readerBlockPreventsImageExpansion\(mediaBlocks\[0\]\)\) return false/);
    assert.match(viewerAppSource, /isReaderStandaloneImagePage\(currentPageBlocks\)/);
    assert.match(viewerAppSource, /function ImageLightbox/);
    assert.match(viewerAppSource, /const \[imageLightbox, setImageLightbox\] = useState\(null\)/);
    assert.match(viewerAppSource, /const openImageLightbox = useCallback/);
    assert.match(viewerAppSource, /imagePreviewAllowed = Boolean\(session\?\.type === 'epub' && block\.hasImage && !readerBlockPreventsImageExpansion\(block\)\)/);
    assert.match(viewerAppSource, /imagePreviewAllowed && 'has-previewable-image'/);
    assert.match(viewerAppSource, /previewable && 'is-previewable'/);
    assert.match(viewerAppSource, /const previewLabel = viewerText\('viewer\.common\.image_preview', '이미지 크게 보기'\)/);
    assert.match(viewerAppSource, /title=\{previewable \? previewLabel : undefined\}/);
    assert.match(viewerAppSource, /<ImageLightbox image=\{imageLightbox\} onClose=\{\(\) => setImageLightbox\(null\)\} \/>/);
    assert.match(viewerAppSource, /block\.hasImage && 'has-block-image'/);
    assert.match(viewerAppSource, /block\.mediaOnly && 'is-media-only-block'/);
    assert.match(viewerAppSource, /item\.hasImage \? 'has-reader-image'/);
    assert.match(viewerAppSource, /item\.standaloneImage \? 'has-epub-image'/);
    assert.match(viewerAppSource, /style=\{block\.style \|\| undefined\}/);
    assert.match(viewerAppSource, /className="viewer-reader-page-body"/);
    assert.doesNotMatch(viewerStyleSource, /--viewer-epub-font-scale/);
    assert.doesNotMatch(viewerStyleSource, /viewer-text-page\.has-reader-image:not\(\.has-epub-image\)/);
    assert.doesNotMatch(viewerStyleSource, /\.viewer-text-page\.has-reader-image:not\(\.has-epub-image\) \.viewer-reader-html-block\.has-block-image\.is-media-only-block[\s\S]*?height:\s*var\(--viewer-reader-mixed-image-max-height/);
    assert.match(viewerStyleSource, /\.viewer-reader-page-body\s*\{[\s\S]*?overflow:\s*visible/);
    assert.match(viewerStyleSource, /\.viewer-text-page\.has-epub-image \.viewer-reader-page-body[\s\S]*?display:\s*flex/);
    assert.match(viewerStyleSource, /\.viewer-text-page\.has-epub-image \.viewer-reader-html-block[\s\S]*?width:\s*100% !important;[\s\S]*?height:\s*auto !important/);
    assert.match(viewerStyleSource, /\.viewer-text-page\.has-epub-image \.viewer-reader-html-block \.viewer-reader-html-node:not\(\.viewer-reader-html-image\)/);
    assert.match(viewerStyleSource, /\.viewer-reader-html-node\[data-epub-anchor\]:empty/);
    assert.match(viewerStyleSource, /\.viewer-text-page\.has-epub-image \.viewer-reader-html-block \.viewer-reader-html-node\[data-epub-anchor\]:empty[\s\S]*?flex:\s*0 0 0 !important/);
    assert.match(viewerStyleSource, /\.viewer-reader-html-block\.has-previewable-image::after/);
    assert.match(viewerStyleSource, /\.viewer-reader-html-image\.is-previewable/);
    assert.match(viewerStyleSource, /\.viewer-reader-html-link/);
    assert.match(viewerStyleSource, /\.viewer-reader-html-rule[\s\S]*?border-top:\s*1px solid currentColor/);
    assert.match(viewerStyleSource, /\.viewer-dropdown-group/);
    assert.match(viewerStyleSource, /\.viewer-image-lightbox-backdrop[\s\S]*?backdrop-filter:\s*blur\(5px\)/);
    assert.match(viewerStyleSource, /\.viewer-image-lightbox img[\s\S]*?object-fit:\s*contain/);
    assert.doesNotMatch(viewerAppSource, /dangerouslySetInnerHTML/);
});

test('뷰어 툴바는 기능별 아이콘 그룹과 줌 팝업을 사용한다', () => {
    assert.match(viewerAppSource, /function ViewerDropdown/);
    assert.doesNotMatch(viewerAppSource, /<select/);
    assert.match(viewerAppSource, /icon="bookmark"/);
    assert.match(viewerAppSource, /icon="anglesLeft"/);
    assert.match(viewerAppSource, /icon="anglesRight"/);
    assert.match(viewerAppSource, /icon="angleLeft"/);
    assert.match(viewerAppSource, /icon="angleRight"/);
    assert.match(viewerAppSource, /fit_width_or_height\.svg/);
    assert.match(viewerAppSource, /\{ id: 'width', label: '가로 맞춤', labelKey: 'viewer\.fit\.width', key: '7'/);
    assert.match(viewerAppSource, /\{ id: 'height', label: '높이 맞춤', labelKey: 'viewer\.fit\.height', key: '8'/);
    assert.match(viewerAppSource, /function fitScaleForViewMode/);
    assert.match(viewerAppSource, /function scaledPageSizeForViewMode/);
    assert.match(viewerAppSource, /viewMode === 'height'[\s\S]*?\? heightScale/);
    assert.match(viewerStyleSource, /\.viewer-comic-image\.view-height/);
    assert.match(viewerAppSource, /const \[pageSizes, setPageSizes\] = useState\(\{\}\)/);
    assert.match(viewerAppSource, /const getComicImageStyle = \(page, pageSlots = 1(?:, renderZoom = zoom)?\) =>/);
    assert.match(viewerAppSource, /baseWidth:\s*size\.width/);
    assert.match(viewerAppSource, /baseHeight:\s*size\.height/);
    assert.match(viewerAppSource, /naturalWidth[\s\S]*?naturalHeight/);
    assert.match(viewerStyleSource, /\.viewer-comic-image\.view-width\s*\{[^}]*max-width:\s*none[^}]*max-height:\s*none/);
    assert.match(viewerAppSource, /show_full_size\.svg/);
    assert.match(viewerAppSource, /fit_to_page\.svg/);
    assert.match(viewerAppSource, /plus_minus\.svg/);
    assert.match(viewerAppSource, /read_mode_one_page\.svg/);
    assert.match(viewerAppSource, /read_mode_double_page\.svg/);
    assert.match(viewerAppSource, /read_mode_scroll\.svg/);
    assert.match(viewerAppSource, /left_read\.svg/);
    assert.match(viewerAppSource, /help\.svg/);
    assert.match(viewerAppSource, /readingDirection === 'rtl' \? \[next, current\] : \[current, next\]/);
    assert.match(viewerAppSource, /active=\{readingDirection === 'rtl'\}/);
    assert.doesNotMatch(viewerAppSource, /active=\{readingDirection === 'ltr'\}/);
    assert.match(viewerAppSource, /slide_navigation\.svg/);
    assert.match(viewerStyleSource, /\.viewer-toolbar[\s\S]*?z-index:\s*60/);
    assert.match(viewerStyleSource, /\.viewer-tool-group\s*\{[^}]*overflow:\s*visible/);
    assert.match(viewerStyleSource, /\.viewer-tool-cluster/);
    assert.match(viewerStyleSource, /\.viewer-tool-button\.is-active[\s\S]*?background:\s*#3498db/);
    assert.match(viewerAppSource, /const supportsBackgroundSettings = session\?\.type === 'comic' \|\| session\?\.type === 'pdf' \|\| session\?\.type === 'epub' \|\| session\?\.type === 'text'/);
    assert.match(viewerAppSource, /const supportsSettingsButton = supportsBackgroundSettings \|\| isReaderDocument/);
    assert.match(viewerAppSource, /const settingsButtonTitle = supportsBackgroundSettings[\s\S]*?viewerText\('viewer\.settings\.viewer', '뷰어 설정'\)[\s\S]*?viewerText\('viewer\.settings\.reading', '읽기 설정'\)/);
    assert.match(viewerAppSource, /const DEFAULT_VIEWER_BACKGROUND/);
    assert.match(viewerAppSource, /const VIEWER_BACKGROUND_COLORS/);
    assert.match(viewerAppSource, /\{ id: 'white', label: '화이트', labelKey: 'viewer\.background_color\.white', color: '#f7f7f7' \}/);
    assert.match(viewerAppSource, /className="viewer-theme-swatches"/);
    assert.match(viewerAppSource, /style=\{\{ '--viewer-theme-bg': item\.bg, '--viewer-theme-fg': item\.fg \}\}/);
    assert.match(viewerAppSource, /function normalizeViewerBackgroundSettings/);
    assert.match(viewerAppSource, /function paintAmbientCanvasFromSource/);
    assert.match(viewerAppSource, /const edgeX = clamp\(Math\.round\(sourceWidth \* 0\.04\)/);
    assert.match(viewerAppSource, /context\.drawImage\(source, 0, 0, sourceWidth, edgeY/);
    assert.match(viewerAppSource, /context\.drawImage\(source, sourceWidth - edgeX, 0, edgeX, sourceHeight/);
    assert.match(viewerAppSource, /function immersiveGradientForPage/);
    assert.match(viewerAppSource, /function viewerPrefsKey/);
    assert.match(viewerAppSource, /bookmanager-viewer-prefs:\$\{type\}/);
    assert.match(viewerAppSource, /const \[viewerBackground, setViewerBackground\] = useState\(normalizeViewerBackgroundSettings\(\)\)/);
    assert.match(viewerAppSource, /const fileState = \{/);
    assert.match(viewerAppSource, /const viewerPrefs = \{/);
    assert.match(viewerAppSource, /saveJson\(storageKey\(session, 'state'\), fileState\)/);
    assert.match(viewerAppSource, /saveJson\(viewerPrefsKey\(session\), viewerPrefs\)/);
    assert.match(viewerAppSource, /const persistScrollState = useCallback/);
    assert.match(viewerAppSource, /saveJson\(storageKey\(session, 'state'\), \{\s*\.\.\.currentState,\s*pageIndex:/);
    assert.match(viewerAppSource, /scrollPercent: clamp\(Number\(nextScrollPercent\) \|\| 0, 0, 100\)/);
    assert.match(viewerAppSource, /const restoreSavedScrollPosition = useCallback/);
    assert.match(viewerAppSource, /const restoreToken = scrollRestoreTokenRef\.current \+ 1/);
    assert.match(viewerAppSource, /if \(maxScrollTop <= 0 && attempt < 24\)/);
    assert.match(viewerAppSource, /node\.scrollTop = \(maxScrollTop \* targetPercent\) \/ 100/);
    assert.match(viewerAppSource, /const savedFileState = readJson\(storageKey\(nextSession, 'state'\), \{\}\)/);
    assert.match(viewerAppSource, /const savedViewerPrefs = readJson\(viewerPrefsKey\(nextSession\), \{\}\)/);
    assert.match(viewerAppSource, /const savedPrefs = \{ \.\.\.savedFileState, \.\.\.savedViewerPrefs \}/);
    assert.match(viewerAppSource, /const savedPageIndex = Math\.max\(0, Number\(savedFileState\.pageIndex\) \|\| 0\)/);
    assert.match(viewerAppSource, /restoreSavedScrollPosition\(nextSession, savedFileState\.scrollPercent\)/);
    assert.match(viewerAppSource, /persistScrollState\(percent, nextVisiblePageIndex\)/);
    assert.match(viewerAppSource, /setViewerBackground\(normalizeViewerBackgroundSettings\(savedPrefs\.viewerBackground \|\| \{\}\)\)/);
    assert.match(viewerAppSource, /className="viewer-ambient-backdrop has-gradient"/);
    assert.match(viewerAppSource, /className=\{`viewer-comic-page-frame view-\$\{viewMode\}`\}/);
    assert.doesNotMatch(viewerAppSource, /function cssImageUrl/);
    assert.doesNotMatch(viewerAppSource, /ambientBackdropImage/);
    assert.doesNotMatch(viewerAppSource, /ambientEnabled=\{flowMode !== 'scroll'\}/);
    assert.match(viewerAppSource, /<span className="viewer-ambient-clip" aria-hidden="true">[\s\S]*?<canvas ref=\{ambientCanvasRef\} className="viewer-ambient-canvas" \/>[\s\S]*?<\/span>/);
    assert.match(viewerAppSource, /<canvas ref=\{ambientCanvasRef\} className="viewer-ambient-canvas" aria-hidden="true" \/>/);
    assert.match(viewerAppSource, /paintAmbientCanvasFromSource\(ambientCanvasRef\.current, canvas\)/);
    assert.match(viewerAppSource, /paintAmbientCanvasFromSource\(ambientCanvasRef\.current, image\)/);
    assert.match(viewerAppSource, /const \[toolbarHeight, setToolbarHeight\] = useState\(42\)/);
    assert.match(viewerAppSource, /<header[\s\S]*?ref=\{toolbarRef\}[\s\S]*?className="viewer-toolbar"[\s\S]*?>/);
    assert.match(viewerAppSource, /'--viewer-toolbar-height': `\$\{toolbarHeight\}px`/);
    assert.match(viewerAppSource, /active=\{settingsOpen\}/);
    assert.match(viewerAppSource, /onClick=\{\(\) => setSettingsOpen\(current => !current\)\}/);
    assert.match(viewerAppSource, /function ViewerHelpModal/);
    assert.match(viewerAppSource, /const \[helpOpen, setHelpOpen\] = useState\(false\)/);
    assert.match(viewerAppSource, /<ViewerHelpModal open=\{helpOpen\} onClose=\{\(\) => setHelpOpen\(false\)\} \/>/);
    assert.match(viewerAppSource, /viewer\.toolbar\.fullscreen[\s\S]*?viewer\.toolbar\.help_group[\s\S]*?viewer\.toolbar\.settings_group/);
    assert.match(viewerAppSource, /viewer\.help\.tab_shortcuts[\s\S]*?viewer\.help\.tab_toolbar[\s\S]*?viewer\.help\.tab_settings[\s\S]*?viewer\.help\.tab_navigation[\s\S]*?viewer\.help\.tab_context/);
    assert.match(viewerAppSource, /className="viewer-help-close"/);
    assert.match(viewerStyleSource, /\.viewer-help-close\s*\{[\s\S]*?border-radius:\s*999px/);
    assert.match(viewerStyleSource, /\.viewer-help-close:hover\s*\{[\s\S]*?transform:\s*translateY\(-1px\)/);
    assert.match(viewerAppSource, /viewer\.help\.shortcut_page_group/);
    assert.match(viewerAppSource, /viewer\.help\.shortcut_swipe/);
    assert.match(viewerAppSource, /`\$\{viewerShortcutLabel\(\['Mod'\]\)\}\+\$\{viewerText\('viewer\.help\.shortcut_wheel_key'/);
    assert.match(viewerAppSource, /viewer\.help\.shortcut_zoom_left_wheel/);
    assert.match(viewerAppSource, /viewer\.help\.shortcut_zoom_right_wheel/);
    assert.match(viewerAppSource, /viewer\.help\.shortcut_fit_group/);
    assert.match(viewerAppSource, /viewer\.help\.shortcut_navigation_group/);
    assert.match(viewerAppSource, /viewer\.help\.shortcut_double_click_key/);
    assert.match(viewerAppSource, /viewer\.help\.shortcut_fullscreen_group/);
    assert.match(viewerAppSource, /keys: \['← \/ →', '↑ \/ ↓', 'PageUp \/ PageDown'\]/);
    assert.match(viewerAppSource, /keys: \['0', '7', '8', '9'\]/);
    assert.match(viewerAppSource, /keys: \[viewerShortcutLabel\(\['Mod', 'F'\]\), 'L'\]/);
    assert.match(viewerAppSource, /viewer-help-shortcut-keys/);
    assert.match(viewerAppSource, /viewer\.help\.shortcut_home_end/);
    assert.match(viewerAppSource, /viewer\.help\.shortcut_escape/);
    assert.match(viewerStyleSource, /\.viewer-help-modal/);
    assert.match(viewerStyleSource, /\.viewer-help-tabs/);
    assert.match(viewerStyleSource, /\.viewer-help-list/);
    assert.match(viewerStyleSource, /\.viewer-help-row/);
    assert.match(viewerStyleSource, /\.viewer-help-shortcut-keys\s*\{[\s\S]*?flex-wrap:\s*wrap/);
    assert.match(viewerStyleSource, /\.viewer-help-row-title kbd\s*\{[\s\S]*?white-space:\s*normal/);
    assert.match(viewerStyleSource, /\.viewer-help-row-title kbd\s*\{[\s\S]*?overflow-wrap:\s*anywhere/);
    assert.match(viewerStyleSource, /\.viewer-ambient-backdrop/);
    assert.match(viewerStyleSource, /\.viewer-ambient-backdrop::before[\s\S]*?var\(--viewer-ambient-turn-texture-color, rgba\(0, 0, 0, 0\)\)/);
    assert.match(viewerStyleSource, /\.viewer-ambient-backdrop::before[\s\S]*?var\(--viewer-ambient-next-gradient, none\)/);
    assert.match(viewerStyleSource, /\.viewer-ambient-backdrop::before[\s\S]*?opacity:\s*var\(--viewer-ambient-turn-progress, 0\)/);
    assert.match(viewerAppSource, /backgroundImage: immersiveGradientForPage\(pageIndex\)/);
    assert.match(viewerAppSource, /'--viewer-ambient-next-gradient': 'none'/);
    assert.match(viewerAppSource, /'--viewer-ambient-turn-progress': 0/);
    assert.match(viewerAppSource, /'--viewer-ambient-turn-texture-color': 'rgba\(0, 0, 0, 0\)'/);
    assert.doesNotMatch(viewerStyleSource, /\.viewer-ambient-backdrop\.has-image/);
    assert.match(viewerStyleSource, /\.viewer-ambient-clip\s*\{[\s\S]*?overflow:\s*visible/);
    assert.match(viewerStyleSource, /\.viewer-ambient-canvas\s*\{[\s\S]*?filter:\s*blur\(74px\) saturate\(1\.45\) contrast\(1\.05\)/);
    assert.match(viewerStyleSource, /\.viewer-app\.is-background-immersive \.viewer-ambient-canvas\s*\{[\s\S]*?opacity:\s*0\.78/);
    assert.match(viewerStyleSource, /\.viewer-comic-scroll\s*\{[\s\S]*?isolation:\s*isolate/);
    assert.match(viewerStyleSource, /\.viewer-comic-scroll \.viewer-comic-page-frame\s*\{[\s\S]*?overflow:\s*visible/);
    assert.match(viewerStyleSource, /\.viewer-comic-scroll \.viewer-ambient-clip\s*\{[\s\S]*?z-index:\s*0/);
    assert.match(viewerStyleSource, /\.viewer-comic-scroll \.viewer-comic-image\s*\{[\s\S]*?z-index:\s*2/);
    assert.doesNotMatch(viewerStyleSource, /\.viewer-app\.is-background-immersive \.viewer-comic-scroll \.viewer-ambient-clip/);
    assert.match(viewerStyleSource, /\.viewer-settings-panel\s*\{[\s\S]*?top:\s*var\(--viewer-toolbar-height, 42px\)/);
    assert.match(viewerStyleSource, /\.viewer-settings-panel\s*\{[\s\S]*?height:\s*calc\(100vh - var\(--viewer-toolbar-height, 42px\)\)/);
    assert.match(viewerStyleSource, /\.viewer-settings-panel\s*\{[\s\S]*?overflow:\s*auto/);
    assert.match(viewerStyleSource, /\.viewer-settings-header\s*\{[\s\S]*?position:\s*sticky/);
    assert.match(viewerStyleSource, /\.viewer-settings-header button\s*\{[\s\S]*?border-radius:\s*999px/);
    assert.match(viewerStyleSource, /\.viewer-settings-header button:hover\s*\{[\s\S]*?background:\s*#3498db/);
    assert.match(viewerStyleSource, /\.viewer-app\.is-background-immersive \.viewer-content/);
    assert.match(viewerStyleSource, /background:\s*var\(--viewer-content-bg, #111111\)/);
    assert.match(viewerAppSource, /const isPageMode = flowMode !== 'scroll'/);
    assert.match(viewerAppSource, /viewer-content \$\{isPageMode \? 'is-page-mode' : ''\}/);
    assert.match(viewerAppSource, /const resetPageModeScroll = useCallback/);
    assert.match(viewerAppSource, /node\.scrollTop = 0/);
    assert.match(viewerAppSource, /node\.scrollLeft = 0/);
    assert.match(viewerAppSource, /event\.stopPropagation\(\)/);
    assert.match(viewerStyleSource, /\.viewer-content\.is-page-mode\s*\{[\s\S]*?scrollbar-width:\s*none/);
    assert.match(viewerStyleSource, /\.viewer-content\.is-page-mode\s*\{[\s\S]*?overflow:\s*hidden/);
    assert.match(viewerStyleSource, /\.viewer-content\.is-page-mode::-webkit-scrollbar\s*\{[\s\S]*?display:\s*none/);
    assert.match(viewerAppSource, /event\.key === '8'[\s\S]*?setViewMode\('height'\)/);
    assert.match(viewerAppSource, /event\.key === '7'[\s\S]*?setViewMode\('width'\)/);
    assert.match(viewerStyleSource, /\.viewer-background-mode/);
    assert.match(viewerStyleSource, /\.viewer-background-swatches/);
    assert.match(viewerStyleSource, /\.viewer-theme-swatches/);
    assert.match(viewerStyleSource, /\.viewer-theme-swatches button::before/);
    assert.match(viewerAppSource, /function ReaderRangeSetting/);
    assert.match(viewerAppSource, /label=\{viewerText\('viewer\.settings\.font_scale', '글자 배율'\)\}[\s\S]*?min=\{READER_FONT_SCALE_MIN\}[\s\S]*?max=\{READER_FONT_SCALE_MAX\}/);
    assert.match(viewerAppSource, /label=\{viewerText\('viewer\.settings\.line_height', '줄간격'\)\}[\s\S]*?min=\{0\}[\s\S]*?max=\{200\}/);
    assert.match(viewerAppSource, /label=\{viewerText\('viewer\.settings\.letter_spacing', '글씨 간격'\)\}[\s\S]*?min=\{0\}[\s\S]*?max=\{20\}/);
    assert.match(viewerAppSource, /label=\{viewerText\('viewer\.settings\.padding_y', '상\/하 여백'\)\}[\s\S]*?min=\{0\}[\s\S]*?max=\{80\}/);
    assert.match(viewerAppSource, /label=\{viewerText\('viewer\.settings\.padding_x', '좌\/우 여백'\)\}[\s\S]*?min=\{0\}[\s\S]*?max=\{80\}/);
    assert.match(viewerAppSource, /label=\{viewerText\('viewer\.settings\.paragraph_spacing', '문단 간격'\)\}[\s\S]*?min=\{0\}[\s\S]*?max=\{120\}/);
    assert.doesNotMatch(viewerAppSource, /paragraphSpacingMode/);
    assert.doesNotMatch(viewerStyleSource, /is-paragraph-spacing-/);
    assert.match(viewerStyleSource, /\.viewer-text-page\.is-epub-reader \.viewer-reader-html-p\s*\{[\s\S]*?margin-top:\s*var\(--viewer-reader-paragraph-spacing, 28px\) !important;[\s\S]*?margin-bottom:\s*0 !important/);
    assert.match(viewerStyleSource, /\.viewer-text-page:not\(\.is-epub-reader\) \.viewer-reader-html-block p/);
    assert.match(viewerAppSource, /const READER_SINGLE_PAGE_MAX_WIDTH = 900/);
    assert.match(viewerAppSource, /const READER_SPREAD_PAGE_MAX_WIDTH = 680/);
    assert.match(viewerAppSource, /const READER_STAGE_PADDING = 14/);
    assert.match(viewerAppSource, /const pageFrameWidth = Math\.min\(maxPageWidth/);
    assert.match(viewerAppSource, /READER_PAGE_BOTTOM_GUARD = 28/);
    assert.match(viewerAppSource, /READER_PAGE_FIT_SCALE_MIN = 0\.58/);
    assert.match(viewerAppSource, /READER_PAGE_FIT_SCALE_DEFAULT = 1\.16/);
    assert.match(viewerAppSource, /READER_PAGE_FIT_SCALE_MAX = 1\.42/);
    assert.match(viewerAppSource, /READER_PAGE_FIT_SCALE_STEP = 0\.88/);
    assert.match(viewerAppSource, /READER_PAGE_FIT_SCALE_RECOVERY_STEP = 1\.08/);
    assert.match(viewerAppSource, /READER_RENDER_OVERFLOW_TOLERANCE = 3/);
    assert.match(viewerAppSource, /READER_RENDER_UNDERFILL_THRESHOLD = 0\.82/);
    assert.match(viewerAppSource, /function readerPageNodeHasRenderedOverflow/);
    assert.match(viewerAppSource, /function readerPageNodeRenderUsage/);
    assert.match(viewerAppSource, /function visibleRenderedEpubPages/);
    assert.match(viewerAppSource, /function readerMeasureBlocksFromPages/);
    assert.match(viewerAppSource, /function buildMeasuredReaderPages/);
    assert.match(viewerAppSource, /const \[measuredEpubPagination, setMeasuredEpubPagination\] = useState\(null\)/);
    assert.match(viewerAppSource, /const readerMeasureRef = useRef\(null\)/);
    assert.match(viewerAppSource, /const \[readerPageFitScale, setReaderPageFitScale\] = useState\(READER_PAGE_FIT_SCALE_DEFAULT\)/);
    assert.match(viewerAppSource, /footerSpace - READER_PAGE_BOTTOM_GUARD/);
    assert.match(viewerAppSource, /const hasWidowLineTolerance = Object\.prototype\.hasOwnProperty\.call\(settings, 'widowLineTolerance'\)/);
    assert.match(viewerAppSource, /widowLineTolerance: hasWidowLineTolerance[\s\S]*?\? Math\.max\(0, Math\.floor\(Number\(settings\.widowLineTolerance\) \|\| 0\)\)/);
    assert.match(viewerAppSource, /const pageSafetyRatio = viewMode === 'height' \? 0\.94 : 0\.96/);
    assert.match(viewerAppSource, /const renderFitScale = session\?\.type === 'epub' \? readerPageFitScale : 1/);
    assert.match(viewerAppSource, /safeLinesPerPage = Math\.max\(6, Math\.floor\(linesPerPage \* pageSafetyRatio \* renderFitScale\)\)/);
    assert.match(viewerAppSource, /const maxCharRatio = \(viewMode === 'height' \? 0\.9 : 0\.94\) \* renderFitScale/);
    assert.match(viewerAppSource, /const estimatedEpubPages = useMemo/);
    assert.match(viewerAppSource, /const epubMeasurementBlocks = useMemo/);
    assert.match(viewerAppSource, /const epubMeasurementReady = measuredEpubPagination\?\.key === epubMeasurementKey/);
    assert.match(viewerAppSource, /const epubPages = epubMeasurementReady \? measuredEpubPagination\.pages : estimatedEpubPages/);
    assert.match(viewerAppSource, /buildMeasuredReaderPages\(epubMeasurementBlocks, measurements, \{ pageContentHeight \}\)/);
    assert.match(viewerAppSource, /data-reader-measure-block-index/);
    assert.match(viewerStyleSource, /\.viewer-reader-measure-stage\s*\{[\s\S]*?visibility:\s*hidden/);
    assert.match(viewerAppSource, /useLayoutEffect\(\(\) => \{[\s\S]*?visibleRenderedEpubPages\(scrollRef\.current\)/);
    assert.match(viewerAppSource, /\}, \[\s*epubPages,\s*epubMeasurementReady,\s*flowMode,\s*readerPageFitScale,\s*readerSettings\.textDirection,\s*session\?\.type,\s*\]\);/);
    assert.match(viewerAppSource, /readerPageNodeRenderUsage\(pageNode, readerSettings\.textDirection\)/);
    assert.match(viewerAppSource, /const hasRecoverableUnderfill = !hasOverflow && readerPageFitScale < READER_PAGE_FIT_SCALE_MAX/);
    assert.match(viewerAppSource, /entry\.usage\.fillRatio >= READER_RENDER_UNDERFILL_THRESHOLD/);
    assert.match(viewerAppSource, /Math\.max\(READER_PAGE_FIT_SCALE_MIN, Number\(\(current \* READER_PAGE_FIT_SCALE_STEP\)\.toFixed\(3\)\)\)/);
    assert.match(viewerAppSource, /Math\.min\(READER_PAGE_FIT_SCALE_MAX, Number\(\(current \* READER_PAGE_FIT_SCALE_RECOVERY_STEP\)\.toFixed\(3\)\)\)/);
    assert.doesNotMatch(viewerStyleSource, /\.viewer-text-page\.is-epub-reader:not\(\.has-epub-image\) \.viewer-reader-page-body[\s\S]*?overflow:\s*auto/);
    assert.match(viewerAppSource, /const widowLineTolerance = 0/);
    assert.match(viewerAppSource, /paragraphLineCost: paragraphSpacing \/ Math\.max\(10, lineAdvance\)/);
    assert.match(viewerAppSource, /titleLines: readerSettings\.showHeader \? \(viewMode === 'height' \? 2 : 1\) : 0/);
    assert.match(viewerAppSource, /usedLines \+= paragraphLineCost/);
    assert.match(viewerAppSource, /function ReaderSegmentedSetting/);
    assert.match(viewerAppSource, /className="viewer-segmented-buttons"/);
    assert.match(viewerAppSource, /role="radiogroup"/);
    assert.match(viewerStyleSource, /\.viewer-segmented-buttons/);
    assert.match(viewerStyleSource, /\.viewer-range-setting/);
    assert.match(viewerAppSource, /TEXT_ALIGN_OPTIONS/);
    assert.match(viewerAppSource, /TEXT_DIRECTION_OPTIONS/);
    assert.match(viewerAppSource, /label=\{viewerText\('viewer\.settings\.hide_header', '머릿글 숨기기'\)\}/);
    assert.match(viewerAppSource, /label=\{viewerText\('viewer\.settings\.hide_footer', '바닥글 숨기기'\)\}/);
    assert.match(viewerAppSource, /const pageIndexRef = useRef\(0\)/);
    assert.match(viewerAppSource, /const setPageIndexSynced = useCallback/);
    assert.match(viewerAppSource, /pageIndexRef\.current = normalizedIndex/);
    assert.match(viewerAppSource, /const getStepSizeForIndex = useCallback/);
    assert.match(viewerAppSource, /const currentIndex = clamp\(pageIndexRef\.current/);
    assert.match(viewerAppSource, /pageIndexRef\.current = nextIndex/);
    assert.match(viewerAppSource, /const \[pageTurn, setPageTurn\] = useState\(EMPTY_PAGE_TURN\)/);
    assert.match(viewerAppSource, /import \{ ReactFlipBook \} from '@vuvandinh203\/react-flipbook'/);
    assert.match(packageSource, /"@vuvandinh203\/react-flipbook": "\^1\.0\.2"/);
    assert.match(viewerAppSource, /const BOOK_PAGE_TURN_DURATION = 720/);
    assert.match(viewerAppSource, /function buildFlipBookGroups/);
    assert.match(viewerAppSource, /function flipBookLeafSourcesForGroup/);
    assert.match(viewerAppSource, /function buildFlipBookPageModel/);
    assert.match(viewerAppSource, /function ViewerFlipBook/);
    assert.match(viewerAppSource, /readingDirection === 'rtl'\s*\? \[...groups\]\.reverse\(\)\s*:\s*groups/);
    assert.match(viewerAppSource, /return readingDirection === 'rtl' \? \[pair\[1\], pair\[0\]\] : pair/);
    assert.match(viewerAppSource, /return readingDirection === 'rtl' \? \[single, null\] : \[null, single\]/);
    assert.match(viewerAppSource, /return readingDirection === 'rtl' \? \[null, single\] : \[single, null\]/);
    assert.match(viewerAppSource, /pageToBookIndex\.set\(pageIndex, firstBookIndex\)/);
    assert.match(viewerAppSource, /bookToPageIndex\.set\(bookIndex, groupStartIndex\)/);
    assert.match(viewerAppSource, /currentPage=\{currentBookIndex\}/);
    assert.match(viewerAppSource, /startPage=\{currentBookIndex\}/);
    assert.match(viewerAppSource, /flippingTime=\{BOOK_PAGE_TURN_DURATION\}/);
    assert.match(viewerAppSource, /usePortrait=\{!spread\}/);
    assert.match(viewerAppSource, /autoSize=\{false\}/);
    assert.match(viewerAppSource, /useMouseEvents=\{false\}/);
    assert.match(viewerAppSource, /enableKeyboardNav=\{false\}/);
    assert.match(viewerAppSource, /showPageCorners=\{false\}/);
    assert.match(viewerAppSource, /disableFlipByClick/);
    assert.match(viewerAppSource, /onPageChange=\{handlePageChange\}/);
    assert.match(viewerAppSource, /maxShadowOpacity=\{0\.52\}/);
    assert.match(viewerAppSource, /className=\{viewerClassName\([\s\S]*?'viewer-flipbook-page'/);
    assert.match(viewerAppSource, /className=\{viewerClassName\('viewer-flipbook-page-inner', `is-\$\{entry\.side\}-page`\)\}/);
    assert.match(viewerAppSource, /entry\.blank\s*\? <div className="viewer-flipbook-blank-page" \/>/);
    assert.match(viewerAppSource, /showCover=\{false\}/);
    assert.match(viewerAppSource, /if \(readerSettings\.pageEffect === 'page'\) \{[\s\S]*?return false;/);
    assert.match(viewerAppSource, /loadComicPageRef\.current\(targetIndex\);[\s\S]*?loadComicPageRef\.current\(targetIndex \+ 1\);[\s\S]*?return false;/);
    assert.match(viewerAppSource, /const handleFlipBookPageIndexChange = useCallback/);
    assert.match(viewerAppSource, /const getFlipBookPageSize = useCallback/);
    assert.match(viewerAppSource, /<ViewerFlipBook[\s\S]*?pageClassName="is-comic"[\s\S]*?readingDirection=\{readingDirection\}/);
    assert.match(viewerAppSource, /<ViewerFlipBook[\s\S]*?pageClassName="is-reader"/);
    assert.match(viewerAppSource, /<ViewerFlipBook[\s\S]*?pageClassName="is-pdf"/);
    assert.match(viewerAppSource, /visibleRenderedEpubPages[\s\S]*?closest\?\.\('\.viewer-flipbook-stage'\)/);
    assert.doesNotMatch(viewerAppSource, /const pageTurnRef = useRef\(EMPTY_PAGE_TURN\)/);
    assert.doesNotMatch(viewerAppSource, /const pageTurnFrameRef = useRef\(0\)/);
    assert.doesNotMatch(viewerAppSource, /const pageTurnPrepareRef = useRef\(0\)/);
    assert.doesNotMatch(viewerAppSource, /const pageTurnDragRef = useRef\(null\)/);
    assert.doesNotMatch(viewerAppSource, /function ReactFlipBookTurnLayer/);
    assert.doesNotMatch(viewerAppSource, /function ReactFlipBookTurnSurface/);
    assert.doesNotMatch(viewerAppSource, /function normalizeReactFlipBookPages/);
    assert.doesNotMatch(viewerAppSource, /function pageBufferSnapshotToDataUrl/);
    assert.doesNotMatch(viewerAppSource, /PAGE_BUFFER_MAX_TEXTURE_SIZE/);
    assert.doesNotMatch(viewerAppSource, /function capturePageBuffer/);
    assert.doesNotMatch(viewerAppSource, /className="viewer-react-flipbook-snapshot"/);
    assert.doesNotMatch(viewerAppSource, /SNAPSHOT_PAGE_TURN_DURATION/);
    assert.doesNotMatch(viewerAppSource, /function easeSnapshotTurnProgress/);
    assert.doesNotMatch(viewerAppSource, /const startSnapshotPageTurn = useCallback/);
    assert.doesNotMatch(viewerAppSource, /const animatePageTurnToProgress = useCallback/);
    assert.doesNotMatch(viewerAppSource, /const beginSnapshotPageTurnDrag = useCallback/);
    assert.doesNotMatch(viewerAppSource, /const updateSnapshotPageTurnDrag = useCallback/);
    assert.doesNotMatch(viewerAppSource, /const endSnapshotPageTurnDrag = useCallback/);
    assert.doesNotMatch(viewerAppSource, /preloadComicTurnImageSizes/);
    assert.doesNotMatch(viewerAppSource, /PAGE_TURN_VERTEX_SHADER/);
    assert.doesNotMatch(viewerAppSource, /PAGE_TURN_FRAGMENT_SHADER/);
    assert.doesNotMatch(viewerAppSource, /function createPageTurnRenderer/);
    assert.doesNotMatch(viewerAppSource, /function drawPageTurnRenderer/);
    assert.match(viewerAppSource, /triggerTimedPageEffect\('pdf', targetIndex, currentIndex, onComplete, getPageEffectDirection\(targetIndex, currentIndex\)\)/);
    assert.match(viewerAppSource, /const showComicSettings = sessionType === 'comic'/);
    assert.match(viewerAppSource, /showComicSettings && \([\s\S]*?viewer\.settings\.page_effect/);
    assert.match(viewerAppSource, /showPdfSettings && \([\s\S]*?viewer\.settings\.page_effect/);
    assert.match(viewerAppSource, /const loadComicPageRef = useRef\(null\)/);
    assert.match(viewerAppSource, /const rememberComicPageImageSize = useCallback/);
    assert.match(viewerAppSource, /function getPageEffectDirection\(targetIndex, currentIndex\)/);
    assert.match(viewerAppSource, /function invertPageEffectDirection\(direction\)/);
    assert.match(viewerAppSource, /function getReadingAdjustedPageEffectDirection\(direction, readingDirection\)/);
    assert.match(viewerAppSource, /readingDirection === 'rtl' \? invertPageEffectDirection\(direction\) : direction/);
    assert.match(viewerAppSource, /readerSettings\.pageEffect === 'none'/);
    assert.match(viewerAppSource, /active: true/);
    assert.match(viewerAppSource, /fromIndex/);
    assert.match(viewerAppSource, /toIndex/);
    assert.match(viewerAppSource, /const pageEffectDirection = getPageEffectDirection\(targetIndex, currentIndex\)/);
    assert.match(viewerAppSource, /const visualEffectDirection = getReadingAdjustedPageEffectDirection\(pageEffectDirection, readingDirection\)/);
    assert.match(viewerAppSource, /triggerTimedPageEffect\('comic', targetIndex, currentIndex, onComplete, visualEffectDirection\)/);
    assert.match(viewerAppSource, /triggerComicPageEffect\(targetIndex, currentIndex/);
    assert.match(viewerAppSource, /if \(targetIndex === currentIndex\) return false/);
    assert.match(viewerAppSource, /triggerComicPageEffect\(nextIndex, currentIndex/);
    assert.match(viewerAppSource, /triggerPdfPageEffect\(targetIndex, currentIndex, commitPdfPage\)/);
    assert.match(viewerAppSource, /const displayStartIndex = pageIndex/);
    assert.match(viewerAppSource, /const basePageIndexes = spread\s*\?\s*\[displayStartIndex, displayStartIndex \+ 1\]\s*:\s*\[displayStartIndex\]/);
    assert.match(viewerAppSource, /pageClassName="is-reader"/);
    assert.match(viewerAppSource, /pageClassName="is-comic"/);
    assert.match(viewerAppSource, /pageClassName="is-pdf"/);
    assert.doesNotMatch(viewerAppSource, /viewer-webgl-turn-slot/);
    assert.match(viewerStyleSource, /\.viewer-comic-stage\.effect-slide\.effect-next \.viewer-comic-page-frame/);
    assert.match(viewerStyleSource, /\.viewer-pdf-stage\.effect-slide\.effect-next \.viewer-pdf-page/);
    assert.match(viewerStyleSource, /\.viewer-reader-stage\.effect-slide\.effect-next \.viewer-text-page/);
    assert.match(viewerStyleSource, /@keyframes viewer-reader-slide-next/);
    assert.match(viewerStyleSource, /\.viewer-flipbook-stage\s*\{[\s\S]*?perspective:\s*2400px/);
    assert.match(viewerStyleSource, /\.viewer-flipbook\s*\{[\s\S]*?pointer-events:\s*auto/);
    assert.match(viewerStyleSource, /\.viewer-flipbook-page\s*\{[\s\S]*?overflow:\s*hidden/);
    assert.match(viewerStyleSource, /\.viewer-flipbook-page-inner\s*\{[\s\S]*?display:\s*flex;[\s\S]*?overflow:\s*hidden/);
    assert.match(viewerStyleSource, /\.viewer-flipbook-page-inner\.is-left-page\s*\{[\s\S]*?justify-content:\s*flex-end/);
    assert.match(viewerStyleSource, /\.viewer-flipbook-page-inner\.is-right-page\s*\{[\s\S]*?justify-content:\s*flex-start/);
    assert.match(viewerStyleSource, /\.viewer-flipbook-page\.is-blank\s*\{[\s\S]*?opacity:\s*0 !important;[\s\S]*?pointer-events:\s*none/);
    assert.match(viewerStyleSource, /\.viewer-flipbook-blank-page/);
    assert.match(viewerStyleSource, /\.viewer-comic-stage\.is-spread:not\(\.viewer-flipbook-stage\) \.viewer-comic-image\s*\{[\s\S]*?max-width:\s*48%/);
    assert.match(viewerStyleSource, /\.viewer-flipbook-stage\.viewer-comic-stage\.is-spread \.viewer-comic-image\s*\{[\s\S]*?max-width:\s*100%;[\s\S]*?max-height:\s*100%/);
    assert.match(viewerStyleSource, /\.viewer-flipbook-page \.viewer-comic-page-frame\s*\{[\s\S]*?overflow:\s*hidden/);
    assert.match(viewerStyleSource, /\.viewer-flipbook-page \.viewer-ambient-clip\s*\{[\s\S]*?overflow:\s*hidden/);
    assert.match(viewerStyleSource, /\.viewer-flipbook-page\.is-left-page \.viewer-comic-image\s*\{[\s\S]*?object-position:\s*right center/);
    assert.match(viewerStyleSource, /\.viewer-flipbook-page\.is-right-page \.viewer-comic-image\s*\{[\s\S]*?object-position:\s*left center/);
    assert.doesNotMatch(viewerStyleSource, /has-page-effect\.effect-page > [\s\S]*?visibility:\s*hidden/);
    assert.doesNotMatch(viewerStyleSource, /\.viewer-react-flipbook/);
    assert.doesNotMatch(viewerStyleSource, /\.viewer-page-buffer/);
    assert.doesNotMatch(viewerStyleSource, /\.viewer-reader-flipbook-turn/);
    assert.doesNotMatch(viewerStyleSource, /\.viewer-comic-flipbook-turn/);
    assert.doesNotMatch(viewerStyleSource, /\.viewer-pdf-flipbook-turn/);
    assert.doesNotMatch(viewerAppSource, /import \{ PageFlip \}/);
    assert.doesNotMatch(viewerAppSource, /WebGLPageTurn/);
    assert.doesNotMatch(viewerAppSource, /getContext\('webgl'/);
    assert.doesNotMatch(viewerStyleSource, /viewer-webgl-turn/);
    assert.doesNotMatch(viewerAppSource, /function PageFlipTurnBook/);
    assert.doesNotMatch(viewerAppSource, /function ComicPageTurnCard/);
    assert.doesNotMatch(viewerAppSource, /clonePageFlipCanvasContent/);
    assert.doesNotMatch(viewerAppSource, /function SnapshotPageTurnLayer/);
    assert.doesNotMatch(viewerAppSource, /readerPageTurn|comicPageEffect|pdfPageEffect/);
    assert.doesNotMatch(viewerStyleSource, /\.viewer-page-flip/);
    assert.doesNotMatch(viewerStyleSource, /\.viewer-snapshot-turn-/);
    assert.doesNotMatch(viewerStyleSource, /\.viewer-comic-turn-/);
    assert.doesNotMatch(viewerStyleSource, /\.viewer-reader-turn-/);
    assert.doesNotMatch(viewerStyleSource, /\.viewer-pdf-turn-/);
    assert.doesNotMatch(viewerStyleSource, /rotateY\(/);
    assert.doesNotMatch(viewerStyleSource, /@keyframes viewer-comic-page-next/);
    assert.doesNotMatch(viewerStyleSource, /@keyframes viewer-reader-page-next/);
    assert.doesNotMatch(viewerStyleSource, /@keyframes viewer-pdf-page-next/);
    assert.doesNotMatch(viewerStyleSource, /filter:\s*brightness/);
    assert.doesNotMatch(viewerStyleSource, /will-change:\s*filter/);
    assert.match(viewerAppSource, /'--viewer-reader-letter-spacing'/);
    assert.match(viewerAppSource, /'--viewer-reader-padding-y'/);
    assert.match(viewerAppSource, /'--viewer-reader-paragraph-spacing'/);
    assert.match(viewerStyleSource, /viewer-pdf-stage\s*\{[\s\S]*?background:\s*transparent/);
    assert.match(viewerAppSource, /full_screen\.svg/);
    assert.match(viewerAppSource, /viewer\.toolbar\.file_navigation[\s\S]*?viewer\.toolbar\.page_navigation[\s\S]*?viewer\.toolbar\.fit_group[\s\S]*?viewer\.toolbar\.zoom_group[\s\S]*?viewer\.toolbar\.read_mode_group[\s\S]*?viewer\.toolbar\.reading_direction_group[\s\S]*?viewer\.toolbar\.slide_nav_group[\s\S]*?viewer\.toolbar\.cover_group[\s\S]*?viewer\.toolbar\.bookmark_group[\s\S]*?viewer\.toolbar\.fullscreen[\s\S]*?viewer\.toolbar\.help_group[\s\S]*?viewer\.toolbar\.settings_group/);
    assert.match(viewerAppSource, /viewer\.toolbar\.file_navigation[\s\S]*?viewer\.toolbar\.previous_file[\s\S]*?viewer\.toolbar\.next_file/);
    assert.match(viewerAppSource, /viewer\.toolbar\.page_navigation[\s\S]*?viewer\.toolbar\.previous_page[\s\S]*?viewer\.toolbar\.next_page/);
    assert.doesNotMatch(viewerAppSource, /aria-label="파일 및 페이지 이동"/);
    assert.doesNotMatch(viewerAppSource, /aria-label="보기 및 설정"/);
    assert.doesNotMatch(viewerAppSource, /aria-label="만화책 옵션"/);
    assert.match(viewerStyleSource, /\.viewer-tool-icon-image/);
    assert.match(viewerStyleSource, /\.viewer-dropdown-menu[\s\S]*?z-index:\s*80/);
    assert.match(viewerStyleSource, /\.viewer-bookmark-menu[\s\S]*?z-index:\s*80/);
    assert.doesNotMatch(viewerStyleSource, /\.viewer-tool-group\s*\{[^}]*overflow-x:\s*auto/);
    assert.doesNotMatch(viewerAppSource, />이전파일<\/ToolbarButton>/);
    assert.doesNotMatch(viewerAppSource, />이전장<\/ToolbarButton>/);
    assert.doesNotMatch(viewerAppSource, />다음장<\/ToolbarButton>/);
    assert.doesNotMatch(viewerAppSource, />다음파일<\/ToolbarButton>/);
    assert.match(viewerAppSource, /const supportsFlowControls = session\?\.type === 'comic' \|\| session\?\.type === 'pdf'/);
    assert.match(viewerAppSource, /const supportsViewControls = session\?\.type === 'comic' \|\| session\?\.type === 'pdf' \|\| session\?\.type === 'epub'/);
    assert.match(viewerAppSource, /session\?\.type === 'epub' && viewMode === 'width'/);
    assert.match(viewerStyleSource, /\.viewer-reader-stage\.is-width \.viewer-text-page/);
    assert.match(viewerAppSource, /const supportsZoomControls = session\?\.type === 'comic' \|\| session\?\.type === 'pdf' \|\| isReaderDocument/);
    assert.match(viewerAppSource, /const readerFontScale = \(Number\(readerSettings\.fontScale\) \|\| 100\) \/ 100/);
    assert.match(viewerAppSource, /const readerFontSize = READER_BASE_FONT_SIZE \* readerFontScale \* \(\(Number\(zoom\) \|\| 100\) \/ 100\)/);
    assert.match(viewerAppSource, /'--viewer-reader-size': `\$\{readerFontSize\}px`/);
    assert.match(viewerAppSource, /const ZOOM_MIN = 10/);
    assert.match(viewerAppSource, /const ZOOM_MAX = 500/);
    assert.match(viewerAppSource, /const ZOOM_STEP = 10/);
    assert.match(viewerAppSource, /function ZoomControl/);
    assert.match(viewerAppSource, /const adjustZoom = useCallback/);
    assert.match(viewerAppSource, /const setZoomValue = useCallback/);
    assert.match(viewerAppSource, /clamp\(\(Number\(current\) \|\| 100\) \+ delta, ZOOM_MIN, ZOOM_MAX\)/);
    assert.match(viewerAppSource, /const handleZoomWheel = useCallback/);
    assert.match(viewerAppSource, /onWheel=\{handleZoomWheel\}/);
    assert.match(viewerAppSource, /className="viewer-zoom-button"/);
    assert.match(viewerAppSource, /\{`\$\{zoom\}%`\}/);
    assert.match(viewerAppSource, /const WHEEL_ZOOM_BUTTON_MASK = 1 \| 2/);
    assert.match(viewerAppSource, /const wheelButtonStateRef = useRef\(0\)/);
    assert.match(viewerAppSource, /const suppressContextMenuRef = useRef\(false\)/);
    assert.match(viewerAppSource, /const scrollZoomAnchorSequenceRef = useRef\(0\)/);
    assert.match(viewerAppSource, /function zoomAnchorSelectorForTarget\(target\)/);
    assert.match(viewerAppSource, /target\?\.closest\?\.\('\[data-page-index\], \[data-pdf-page-index\], \[data-reader-page-index\], \[data-reader-index\]'\)/);
    assert.match(viewerAppSource, /const createScrollZoomAnchor = useCallback/);
    assert.doesNotMatch(viewerAppSource, /if \(flowMode !== 'scroll'\) return null/);
    assert.match(viewerAppSource, /const offsetX = clamp\(event\.clientX - rect\.left, 0, Math\.max\(0, node\.clientWidth\)\)/);
    assert.match(viewerAppSource, /const targetSelector = zoomAnchorSelectorForTarget\(event\.target\)/);
    assert.match(viewerAppSource, /selector: targetSelector/);
    assert.match(viewerAppSource, /ratioX: clamp\(\(event\.clientX - targetRect\.left\) \/ Math\.max\(1, targetRect\.width\), 0, 1\)/);
    assert.match(viewerAppSource, /ratioX: \(node\.scrollLeft \+ offsetX\) \/ Math\.max\(1, node\.scrollWidth\)/);
    assert.match(viewerAppSource, /ratioY: \(node\.scrollTop \+ offsetY\) \/ Math\.max\(1, node\.scrollHeight\)/);
    assert.match(viewerAppSource, /const restoreScrollZoomAnchor = useCallback/);
    assert.match(viewerAppSource, /const targetNode = anchor\.target\?\.selector \? node\.querySelector\?\.\(anchor\.target\.selector\) : null/);
    assert.match(viewerAppSource, /node\.scrollLeft \+ targetRect\.left - viewportRect\.left \+ \(anchor\.target\.ratioX \* targetRect\.width\) - anchor\.offsetX/);
    assert.match(viewerAppSource, /node\.scrollLeft = clamp\(\(anchor\.ratioX \* nextScrollWidth\) - anchor\.offsetX, 0, maxScrollLeft\)/);
    assert.match(viewerAppSource, /node\.scrollTop = clamp\(\(anchor\.ratioY \* nextScrollHeight\) - anchor\.offsetY, 0, maxScrollTop\)/);
    assert.match(viewerAppSource, /if \(attempt < 8\) window\.requestAnimationFrame\(\(\) => applyAnchor\(attempt \+ 1\)\)/);
    assert.match(viewerAppSource, /const adjustZoomAtPoint = useCallback/);
    assert.match(viewerAppSource, /function isShortcutModifierEvent\(event = \{\}\)/);
    assert.match(viewerAppSource, /return event\.ctrlKey \|\| event\.metaKey/);
    assert.match(viewerAppSource, /const zoomByWheelCombination = isShortcutModifierEvent\(event\) \|\| Boolean\(activeWheelButtons & WHEEL_ZOOM_BUTTON_MASK\)/);
    assert.match(viewerAppSource, /adjustZoomAtPoint\(wheelDelta < 0 \? ZOOM_STEP : -ZOOM_STEP, event\)/);
    assert.match(viewerAppSource, /if \(activeWheelButtons & 2\) suppressContextMenuRef\.current = true/);
    assert.match(viewerAppSource, /if \(suppressContextMenuRef\.current\)/);
    assert.match(viewerStyleSource, /\.viewer-zoom-menu/);
    assert.match(viewerStyleSource, /\.viewer-zoom-range/);
    assert.match(viewerStyleSource, /\.viewer-tool-button\.viewer-zoom-button\.has-text/);
    assert.match(viewerStyleSource, /font-variant-numeric:\s*tabular-nums/);
    assert.doesNotMatch(viewerAppSource, /<ToolbarButton[^>]+icon="(?:chevronLeft|chevronRight|angleUp|angleDown)"/);
    assert.doesNotMatch(viewerAppSource, /title="닫기 \(Esc\)"/);
});

test('하단 페이지 네비게이션은 모든 뷰어 형식에서 사용할 수 있다', () => {
    assert.match(viewerAppSource, /function PdfThumbnailCanvas/);
    assert.match(viewerAppSource, /function ComicSlideThumb/);
    assert.match(viewerAppSource, /function ReaderSlideThumb/);
    assert.match(viewerAppSource, /const goPageIndex = useCallback/);
    assert.match(viewerAppSource, /const goSlideNavPage = useCallback[\s\S]*?goPageIndex\(resolveSpreadNavigationIndex\(resolvedPageIndex\)\)/);
    assert.match(viewerAppSource, /const handleSlideNavWheel = useCallback/);
    assert.match(viewerAppSource, /event\.currentTarget\.scrollBy\(\{ left: wheelDelta, behavior: 'auto' \}\)/);
    assert.match(viewerAppSource, /const slideNavAvailable = Boolean\(session && pageCount > 0 && \(session\.type !== 'pdf' \|\| pdfDocument\)\)/);
    assert.match(viewerAppSource, /const renderSlideThumbs = \(\) =>/);
    assert.match(viewerAppSource, /onWheel=\{handleSlideNavWheel\}/);
    assert.match(viewerAppSource, /slideNavOpen: 'slideNavOpen' in patch \? patch\.slideNavOpen : slideNavOpen/);
    assert.match(viewerAppSource, /setSlideNavOpen\(savedPrefs\.slideNavOpen !== false\)/);
    assert.match(viewerAppSource, /\[flowMode, pageCount, pageIndex, readerSettings, readingDirection, scrollPercent, session, slideNavOpen, spreadCoverFirst, viewMode, viewerBackground, zoom\]/);
    assert.match(viewerAppSource, /session\?\.type === 'comic'/);
    assert.match(viewerAppSource, /session\?\.type === 'epub' \|\| session\?\.type === 'text'/);
    assert.match(viewerAppSource, /onClick=\{runToolbarAction\(\(\) => goSlideNavPage\(index\)\)\}/);
    assert.match(viewerAppSource, /loadComicPage\(index, \{ force: true \}\)/);
    assert.match(viewerStyleSource, /viewer-slide-thumb\.is-comic/);
    assert.match(viewerStyleSource, /viewer-slide-thumb\.is-reader/);
    assert.match(viewerStyleSource, /viewer-slide-thumb-reader-preview/);
});

test('Ctrl/Cmd+F는 목차 및 검색 패널을 열고 검색 입력에 포커스한다', () => {
    assert.match(viewerAppSource, /const navigationSearchInputRef = useRef\(null\)/);
    assert.match(viewerAppSource, /function ViewerNavigationPanel/);
    assert.match(viewerAppSource, /searchInputRef/);
    assert.match(viewerAppSource, /ref=\{searchInputRef\}/);
    assert.match(viewerAppSource, /const openNavigationSearch = useCallback/);
    assert.match(viewerAppSource, /setNavigationPanelOpen\(true\)/);
    assert.match(viewerAppSource, /setNavigationTab\('search'\)/);
    assert.match(viewerAppSource, /navigationSearchInputRef\.current\?\.focus\?\.\(\)/);
    assert.match(viewerAppSource, /navigationSearchInputRef\.current\?\.select\?\.\(\)/);
    assert.match(viewerAppSource, /event\.key\.toLowerCase\(\) === 'f'/);
    assert.match(viewerAppSource, /isShortcutModifierEvent\(event\) && !event\.altKey && event\.key\.toLowerCase\(\) === 'f'/);
    assert.match(viewerAppSource, /openNavigationSearch\(\)/);
    assert.match(viewerAppSource, /const openNavigationToc = useCallback/);
    assert.match(viewerAppSource, /setNavigationTab\('toc'\)/);
    assert.match(viewerAppSource, /event\.key\.toLowerCase\(\) === 'l'/);
    assert.match(viewerAppSource, /openNavigationToc\(\)/);
    assert.match(viewerAppSource, /const activeTocId = useMemo/);
    assert.match(viewerAppSource, /aria-current=\{activeTocId === item\.id \? 'page' : undefined\}/);
    assert.match(viewerStyleSource, /\.viewer-navigation-list-item\.is-active/);
    assert.match(viewerAppSource, /const resolveSpreadNavigationIndex = useCallback/);
    assert.match(viewerAppSource, /session\?\.type === 'comic' \? getStepSizeForIndex\(startIndex\) : 2/);
    assert.match(viewerAppSource, /goPageIndex\(resolveSpreadNavigationIndex\(resolvedPageIndex\)\)/);
    assert.match(viewerAppSource, /const goHighlight = useCallback/);
    assert.match(viewerAppSource, /goNavigationPage\(highlight\.pageIndex\)/);
});

test('확대된 이미지와 PDF 캔버스는 드래그로 스크롤 이동할 수 있다', () => {
    assert.match(viewerAppSource, /const dragPanRef = useRef/);
    assert.match(viewerAppSource, /function dragPanOverflowStateForTarget\(node, panTarget\)/);
    assert.match(viewerAppSource, /const targetRect = panTarget\.getBoundingClientRect\?\.\(\)/);
    assert.match(viewerAppSource, /const viewportRect = node\.getBoundingClientRect\?\.\(\)/);
    assert.match(viewerAppSource, /canPanX: targetRect\.width > viewportRect\.width \+ 1 && node\.scrollWidth > node\.clientWidth \+ 1/);
    assert.match(viewerAppSource, /canPanY: targetRect\.height > viewportRect\.height \+ 1 && node\.scrollHeight > node\.clientHeight \+ 1/);
    assert.match(viewerAppSource, /const getDragPanTarget = useCallback/);
    assert.match(viewerAppSource, /const isDragPanTarget = useCallback/);
    assert.match(viewerAppSource, /closest\?\.\('\.viewer-comic-image, \.viewer-pdf-canvas-wrap'\)/);
    assert.match(viewerAppSource, /const handleDragPanPointerDown = useCallback/);
    assert.match(viewerAppSource, /const panTarget = getDragPanTarget\(event\.target\)/);
    assert.match(viewerAppSource, /dragPanOverflowStateForTarget\(node, panTarget\)/);
    assert.match(viewerAppSource, /node\.setPointerCapture\?\.\(event\.pointerId\)/);
    assert.match(viewerAppSource, /node\.scrollLeft = state\.scrollLeft - \(event\.clientX - state\.startX\)/);
    assert.match(viewerAppSource, /node\.scrollTop = state\.scrollTop - \(event\.clientY - state\.startY\)/);
    assert.match(viewerAppSource, /const handleContentPointerDown = useCallback/);
    assert.match(viewerAppSource, /const handleContentPointerMove = useCallback/);
    assert.match(viewerAppSource, /const handleContentPointerUp = useCallback/);
    assert.match(viewerAppSource, /onPointerDown=\{handleContentPointerDown\}/);
    assert.match(viewerAppSource, /onPointerMove=\{handleContentPointerMove\}/);
    assert.match(viewerAppSource, /onPointerUp=\{handleContentPointerUp\}/);
    assert.match(viewerStyleSource, /\.viewer-content\.is-drag-panning/);
    assert.match(viewerStyleSource, /\.viewer-comic-image[\s\S]*?cursor:\s*grab/);
    assert.match(viewerStyleSource, /\.viewer-pdf-canvas-wrap[\s\S]*?cursor:\s*grab/);
});

test('뷰어 본문은 터치 스와이프로 이전장과 다음장으로 이동한다', () => {
    assert.match(viewerAppSource, /const SWIPE_MIN_DISTANCE = 64/);
    assert.match(viewerAppSource, /const SWIPE_AXIS_LOCK_RATIO = 1\.35/);
    assert.match(viewerAppSource, /const swipeGestureRef = useRef\(null\)/);
    assert.match(viewerAppSource, /const handleSwipePointerDown = useCallback/);
    assert.match(viewerAppSource, /event\.pointerType !== 'touch' && event\.pointerType !== 'pen'/);
    assert.match(viewerAppSource, /const handleSwipePointerMove = useCallback/);
    assert.match(viewerAppSource, /const handleSwipePointerUp = useCallback/);
    assert.match(viewerAppSource, /const handleTouchSwipeStart = useCallback/);
    assert.match(viewerAppSource, /event\.touches\.length !== 1/);
    assert.match(viewerAppSource, /source: 'touch'/);
    assert.match(viewerAppSource, /const handleTouchSwipeMove = useCallback/);
    assert.match(viewerAppSource, /const handleTouchSwipeEnd = useCallback/);
    assert.match(viewerAppSource, /const visualDelta = dx < 0 \? 1 : -1/);
    assert.match(viewerAppSource, /const navigationDelta = readingDirection === 'rtl' \? -visualDelta : visualDelta/);
    assert.match(viewerAppSource, /movePage\(navigationDelta\)/);
    assert.match(viewerAppSource, /const handleContentPointerCancel = useCallback/);
    assert.match(viewerAppSource, /onPointerCancel=\{handleContentPointerCancel\}/);
    assert.match(viewerAppSource, /onLostPointerCapture=\{handleContentPointerCancel\}/);
    assert.match(viewerAppSource, /onTouchStart=\{handleTouchSwipeStart\}/);
    assert.match(viewerAppSource, /onTouchMove=\{handleTouchSwipeMove\}/);
    assert.match(viewerAppSource, /onTouchEnd=\{handleTouchSwipeEnd\}/);
    assert.match(viewerAppSource, /onTouchCancel=\{handleTouchSwipeCancel\}/);
    assert.match(viewerStyleSource, /touch-action:\s*pan-y pinch-zoom/);
});

test('두장보기모드는 두 페이지가 있을 때 가운데로 붙여서 배치한다', () => {
    assert.match(viewerAppSource, /has-spread-pair/);
    assert.match(viewerAppSource, /viewer-spread-pair/);
    assert.match(viewerAppSource, /const \[comicSinglePageNames, setComicSinglePageNames\] = useState\(\[\]\)/);
    assert.match(viewerAppSource, /storageKey\(nextSession, 'comic-flow'\)/);
    assert.match(viewerAppSource, /saveJson\(storageKey\(session, 'comic-flow'\), next\)/);
    assert.match(viewerAppSource, /const isComicSinglePage = useCallback/);
    assert.match(viewerAppSource, /isComicSinglePage\(index\) \|\| isComicSinglePage\(index \+ 1\)/);
    assert.match(viewerAppSource, /selectionMenu\?\.kind !== 'comic-flow'/);
    assert.match(viewerAppSource, /viewer\.context\.comic_single_page/);
    assert.match(viewerAppSource, /viewer\.context\.comic_single_page_clear/);
    assert.match(i18nSource, /comic_single_page: '이 페이지를 단독장으로 분리'/);
    assert.match(i18nSource, /context_comic_single_page: '만화책 두장보기에서 순서가 어긋난 페이지를 단독 페이지로 분리/);
    assert.match(viewerAppSource, /const stageGap = flowMode === 'spread' \? 0 : 10/);
    assert.match(viewerAppSource, /const pageFrameWidth = Math\.min\(maxPageWidth,\s*Math\.max\(220,\s*\(stageWidth - stageGap\) \/ pageColumns\)\)/);
    assert.match(viewerAppSource, /const pageSlots = hasSpreadPair \? 2 : 1/);
    assert.match(viewerAppSource, /const horizontalInset = slots > 1 \? 24 : 64/);
    assert.match(viewerAppSource, /const availableWidth = Math\.max\(220,\s*\(\(Number\(containerWidth\) \|\| 900\) - horizontalInset\) \/ slots\)/);
    assert.match(viewerStyleSource, /viewer-spread-pair[\s\S]*?gap:\s*0/);
    assert.match(viewerStyleSource, /viewer-comic-stage\.is-spread\.has-spread-pair[\s\S]*?gap:\s*0/);
    assert.match(viewerStyleSource, /viewer-comic-stage\.is-spread\.has-spread-pair \.viewer-comic-page-frame[\s\S]*?flex:\s*0 1 auto/);
    assert.match(viewerStyleSource, /viewer-comic-stage\.is-spread\.has-spread-pair \.viewer-comic-page-frame:first-child \.viewer-comic-image[\s\S]*?object-position:\s*right center/);
    assert.match(viewerStyleSource, /viewer-comic-stage\.is-spread\.has-spread-pair \.viewer-comic-page-frame:last-child \.viewer-comic-image[\s\S]*?object-position:\s*left center/);
    assert.match(viewerStyleSource, /viewer-reader-stage\.is-spread\.has-spread-pair[\s\S]*?gap:\s*0/);
    assert.match(viewerStyleSource, /viewer-reader-stage\.is-spread\.has-spread-pair \.viewer-spread-pair[\s\S]*?align-items:\s*stretch/);
    assert.match(viewerStyleSource, /viewer-pdf-stage\.is-spread[\s\S]*?gap:\s*0/);
    assert.match(viewerStyleSource, /viewer-pdf-stage\.is-spread\.has-spread-pair \.viewer-pdf-canvas-wrap[\s\S]*?max-width:\s*100%/);
    assert.match(viewerStyleSource, /viewer-pdf-stage\.is-spread\.has-spread-pair \.viewer-pdf-page[\s\S]*?flex:\s*0 1 auto/);
    assert.doesNotMatch(viewerStyleSource, /viewer-pdf-stage\.is-spread\.has-spread-pair \.viewer-pdf-page[\s\S]*?flex:\s*0 0 50%/);
});

test('뷰어 인접권 버튼은 사용 가능할 때만 동작한다', () => {
    assert.match(viewerSessionSource, /adjacent:\s*adjacentBookState\(normalizedPath\)/);
    assert.match(viewerSessionSource, /MAX_VIEWER_SESSIONS/);
    assert.doesNotMatch(viewerSessionSource, /this\.sessions\.clear\(\)/);
    assert.match(viewerSessionSource, /hasPrevious/);
    assert.match(viewerSessionSource, /hasNext/);
    assert.match(viewerAppSource, /const hasPreviousBook = Boolean\(session\?\.adjacent\?\.hasPrevious\)/);
    assert.match(viewerAppSource, /const hasNextBook = Boolean\(session\?\.adjacent\?\.hasNext\)/);
    assert.match(viewerAppSource, /disabled=\{!hasPreviousBook \|\| adjacentLoading\}/);
    assert.match(viewerAppSource, /disabled=\{!hasNextBook \|\| adjacentLoading\}/);
    assert.match(viewerAppSource, /if \(!session \|\| !hasAdjacentBook \|\| adjacentLoadingRef\.current\) return/);
    assert.match(viewerAppSource, /adjacentLoadingRef/);
    assert.match(viewerAppSource, /await loadSession\(result\.session\)/);
    assert.doesNotMatch(viewerWindowSource, /openAdjacentViewer[\s\S]*sendSession\(session\)/);
    assert.match(viewerAppSource, /message === 'No adjacent book\.'/);
    assert.match(viewerAppSource, /const \[viewerToast, setViewerToast\] = useState\(null\)/);
    assert.match(viewerAppSource, /const isForwardBoundaryIndex = useCallback/);
    assert.match(viewerAppSource, /if \(delta > 0 && pageCount > 0 && flowMode !== 'scroll' && isForwardBoundaryIndex\(currentIndex\)\)/);
    assert.match(viewerAppSource, /moveAdjacentBook\(1\);\s*return;/);
    assert.match(viewerAppSource, /const nextPageDisabled = pageCount <= 0 \|\| \(atForwardBoundary && !hasNextBook\)/);
    assert.match(viewerAppSource, /viewer-toast-layer/);
    assert.match(viewerAppSource, /role="status"/);
    assert.match(viewerStyleSource, /\.viewer-toast-layer/);
    assert.match(viewerStyleSource, /\.viewer-toast/);
});

test('뷰어 세션은 만화책, PDF, EPUB, TXT 형식을 분기한다', () => {
    assert.match(viewerSessionSource, /COMIC_EXTENSIONS = new Set\(\['\.zip', '\.cbz', '\.rar', '\.cbr', '\.7z', '\.cb7'\]\)/);
    assert.match(viewerSessionSource, /PDF_EXTENSIONS = new Set\(\['\.pdf'\]\)/);
    assert.match(viewerSessionSource, /EPUB_EXTENSIONS = new Set\(\['\.epub'\]\)/);
    assert.match(viewerSessionSource, /TEXT_EXTENSIONS = new Set/);
    assert.match(viewerSessionSource, /listComicPages/);
    assert.match(viewerSessionSource, /pageUrl:\s*comicPageProtocolUrl/);
    assert.match(mainSource, /scheme:\s*'bookmanager-comic'/);
    assert.match(viewerSessionSource, /documentUrl/);
    assert.match(viewerSessionSource, /bookmanager-document/);
    assert.match(viewerSessionSource, /epubAssetProtocolUrl/);
    assert.match(viewerSessionSource, /getDocumentAssetFromRequest/);
    assert.match(viewerSessionSource, /parseEpubNavTitles/);
    assert.match(viewerSessionSource, /parseEpubNavEntries/);
    assert.match(viewerSessionSource, /parseEpubMetadata/);
    assert.match(viewerSessionSource, /epubReaderBlocksFromHtml/);
    assert.match(viewerSessionSource, /findEpubCoverMetaId/);
    assert.match(viewerSessionSource, /function epubImageBlockFromEntry/);
    assert.match(viewerSessionSource, /function repairEpubFilenameOnlyCoverPage/);
    assert.match(viewerSessionSource, /findEpubImageEntryForFilenameText/);
    assert.match(viewerSessionSource, /repairEpubFilenameOnlyCoverPage\(results, coverEntry, entries, session, imageDimensionByEntryName\)/);
    assert.match(viewerWindowSource, /sessions\.getDocumentAssetFromRequest\(request\.url\)/);
    assert.match(viewerWindowSource, /ipcMain\.handle\('viewer:openExternal'/);
    assert.match(viewerWindowSource, /dialog\.showMessageBox/);
    assert.match(viewerWindowSource, /shell\.openExternal\(safeUrl\)/);
    assert.match(viewerWindowSource, /fs\.createReadStream\(document\.filePath,\s*\{\s*start,\s*end\s*\}\)/);
    assert.match(viewerWindowSource, /Readable\.toWeb/);
    assert.match(viewerWindowSource, /Accept-Ranges': 'bytes'/);
    assert.match(viewerSessionSource, /getEpubText/);
    assert.match(viewerAppSource, /function paginateReaderChapter/);
    assert.match(viewerAppSource, /className=\{viewerClassName\('viewer-epub-image', imagePreviewAllowed && 'is-previewable'\)\}/);
    assert.match(viewerAppSource, /READER_FOOTER_SPACE = 56/);
    assert.match(viewerAppSource, /className="viewer-reader-page-number"/);
    assert.match(viewerStyleSource, /\.viewer-reader-page-body > h2[\s\S]*?opacity:\s*0\.6[\s\S]*?text-align:\s*center/);
    assert.match(viewerStyleSource, /\.viewer-epub-image img[\s\S]*?max-height:\s*min\(62vh, calc\(100vh - var\(--viewer-toolbar-height, 42px\) - 170px\)\) !important/);
    assert.match(viewerStyleSource, /\.viewer-text-page\.has-epub-image \.viewer-reader-html-block[\s\S]*?display:\s*flex/);
    assert.match(viewerStyleSource, /\.viewer-text-page\.has-epub-image \.viewer-reader-html-block > \*[\s\S]*?max-height:\s*100% !important/);
    assert.match(viewerStyleSource, /\.viewer-text-page\.has-epub-image \.viewer-epub-image img[\s\S]*?flex:\s*1 1 0/);
    assert.match(viewerStyleSource, /\.viewer-text-page\.has-epub-image \.viewer-reader-html-block img[\s\S]*?height:\s*100% !important/);
    assert.match(viewerStyleSource, /var\(--viewer-reader-footer-space, 56px\)/);
    assert.match(viewerStyleSource, /\.viewer-reader-page-number/);
});

test('PDF 뷰어는 PDF.js로 페이지를 직접 렌더링하고 책갈피 페이지를 추적한다', () => {
    assert.match(viewerAppSource, /import \* as pdfjsLib from 'pdfjs-dist'/);
    assert.match(viewerAppSource, /pdf\.worker\.mjs\?url/);
    assert.match(viewerAppSource, /GlobalWorkerOptions\.workerSrc/);
    assert.match(viewerAppSource, /function PdfPageCanvas/);
    assert.match(viewerAppSource, /function PdfThumbnailCanvas/);
    assert.match(viewerAppSource, /pdfjsLib\.getDocument/);
    assert.match(viewerAppSource, /<canvas ref=\{canvasRef\}/);
    assert.match(viewerAppSource, /viewer-pdf-canvas-wrap is-\$\{status\}/);
    assert.match(viewerAppSource, /viewer-slide-nav/);
    assert.match(viewerAppSource, /viewer-slide-strip/);
    assert.match(viewerAppSource, /viewer-slide-thumb/);
    assert.match(viewerAppSource, /data-pdf-page-index/);
    assert.match(viewerAppSource, /fetch\(result\.documentUrl/);
    assert.match(viewerAppSource, /scrollPdfPageIntoView/);
    assert.match(viewerAppSource, /session\?\.type === 'pdf' && pdfPageCount > 0/);
    assert.match(viewerAppSource, /session\.type === 'comic' \|\| session\.type === 'pdf'/);
    assert.match(indexSource, /worker-src[^;]*'self'[^;]*blob:[^;]*file:/);
    assert.match(indexSource, /connect-src[^;]*bookmanager-document:/);
    assert.match(viewerAppSource, /loadSequenceRef/);
    assert.match(viewerStyleSource, /viewer-pdf-canvas-wrap\.is-loading/);
    assert.match(viewerStyleSource, /viewer-pdf-canvas-wrap:not\(\.is-ready\) \.viewer-pdf-canvas/);
    assert.match(viewerStyleSource, /visibility:\s*hidden/);
    assert.doesNotMatch(viewerStyleSource, /viewer-pdf-canvas-wrap:not\(\.is-ready\) \.viewer-pdf-canvas[\s\S]*?(?:width|height):\s*0\s*!important/);
    assert.match(viewerAppSource, /const \[pageSize,\s*setPageSize\] = useState\(null\)/);
    assert.match(viewerAppSource, /setPageSize\(nextPageSize\)/);
    assert.match(viewerStyleSource, /viewer-pdf-canvas-wrap\.is-ready \.viewer-pdf-canvas[\s\S]*?background:\s*#ffffff/);
    assert.match(viewerStyleSource, /viewer-app\.has-slide-nav-open \.viewer-content/);
    assert.match(viewerStyleSource, /\.viewer-content[\s\S]*?transition:\s*padding-bottom 220ms ease/);
    assert.match(viewerStyleSource, /\.viewer-slide-nav[\s\S]*?transition:[\s\S]*?height 220ms ease/);
    assert.match(viewerStyleSource, /\.viewer-slide-strip[\s\S]*?transform:\s*translateY\(18px\)/);
    assert.match(viewerStyleSource, /\.viewer-slide-nav\.is-open \.viewer-slide-strip[\s\S]*?transform:\s*translateY\(0\)/);
    assert.match(viewerAppSource, /aria-hidden=\{!slideNavOpen\}/);
    assert.match(viewerStyleSource, /viewer-slide-nav\.is-open::before/);
    assert.match(viewerStyleSource, /viewer-slide-nav\.is-open::after/);
    assert.doesNotMatch(viewerStyleSource, /viewer-pdf-page\.is-active\s+\.viewer-pdf-canvas-wrap[\s\S]*?outline/);
    assert.doesNotMatch(viewerAppSource, /<iframe/);
    assert.doesNotMatch(viewerAppSource, /<embed/);
    assert.doesNotMatch(viewerAppSource, /URL\.createObjectURL/);
    assert.doesNotMatch(viewerAppSource, /URL\.revokeObjectURL/);
    assert.doesNotMatch(viewerAppSource, /documentBlobUrlRef/);
    assert.doesNotMatch(viewerAppSource, /setDocumentFrameKey/);
    assert.doesNotMatch(viewerAppSource, /setDocumentUrl\(result\.fileUrl/);
    assert.doesNotMatch(viewerSessionSource, /fileUrl/);
    assert.doesNotMatch(viewerSessionSource, /MAX_DOCUMENT_DATA_URL_BYTES/);
    assert.doesNotMatch(viewerAppSource, /<object className="viewer-document-frame"/);
});

test('만화책 페이지 이미지는 전용 프로토콜 실패 시 IPC data URL로 fallback 한다', () => {
    assert.match(viewerAppSource, /const src = pageData\[page\.name\] \|\| page\?\.pageUrl/);
    assert.match(viewerAppSource, /loadComicPage\(index,\s*\{\s*force:\s*true\s*\}\)/);
    assert.match(viewerAppSource, /const \{\s*naturalWidth,\s*naturalHeight\s*\} = event\.currentTarget/);
    assert.doesNotMatch(viewerAppSource, /event\.currentTarget\.naturalWidth\s*\//);
    assert.match(viewerAppSource, /setPageErrors/);
    assert.match(viewerAppSource, /viewer-comic-placeholder is-error/);
    assert.match(viewerSessionSource, /if \(buffer\) return buffer/);
    assert.match(viewerWindowSource, /new Uint8Array\(page\.buffer\)/);
});
