import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faMicrosoft,
} from '@fortawesome/free-brands-svg-icons';
import {
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAngleUp,
  faAnglesDown,
  faAnglesLeft,
  faAnglesRight,
  faAnglesUp,
  faArrowRotateLeft,
  faBars,
  faBookmark,
  faBookOpen,
  faBoxArchive,
  faBug,
  faBuilding,
  faCalendarDays,
  faCaretDown,
  faCheck,
  faChevronLeft,
  faChevronRight,
  faChild,
  faCircle,
  faCircleCheck,
  faCircleMinus,
  faClock,
  faCloudArrowDown,
  faCopy,
  faCube,
  faDesktop,
  faDownload,
  faEllipsisVertical,
  faEye,
  faEyeSlash,
  faFile,
  faFileCirclePlus,
  faFileZipper,
  faFileSignature,
  faFileLines,
  faFloppyDisk,
  faFolder,
  faFolderMinus,
  faFolderOpen,
  faFolderPlus,
  faGear,
  faGift,
  faGripVertical,
  faHouse,
  faLanguage,
  faLayerGroup,
  faLink,
  faList,
  faMagnifyingGlass,
  faMinus,
  faPowerOff,
  faPlus,
  faRocket,
  faSquareCheck,
  faSquare,
  faTableCells,
  faStopCircle,
  faStar,
  faTag,
  faThumbTack,
  faTowerBroadcast,
  faTrash,
  faUser,
  faUsers,
  faWandMagicSparkles,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';

const ICONS = {
  angleDown: faAngleDown,
  angleLeft: faAngleLeft,
  angleRight: faAngleRight,
  angleUp: faAngleUp,
  anglesDown: faAnglesDown,
  anglesLeft: faAnglesLeft,
  anglesRight: faAnglesRight,
  anglesUp: faAnglesUp,
  'angle-down': faAngleDown,
  'angle-left': faAngleLeft,
  'angle-right': faAngleRight,
  'angle-up': faAngleUp,
  'angles-down': faAnglesDown,
  'angles-left': faAnglesLeft,
  'angles-right': faAnglesRight,
  'angles-up': faAnglesUp,
  folder: faFolder,
  folderOpen: faFolderOpen,
  'folder-open': faFolderOpen,
  folderMinus: faFolderMinus,
  folderPlus: faFolderPlus,
  'folder-plus': faFolderPlus,
  file: faFile,
  fileCirclePlus: faFileCirclePlus,
  'file-circle-plus': faFileCirclePlus,
  fileSignature: faFileSignature,
  minusCircle: faCircleMinus,
  trash: faTrash,
  checkSquare: faSquareCheck,
  square: faSquare,
  stopCircle: faStopCircle,
  powerOff: faPowerOff,
  bug: faBug,
  circle: faCircle,
  circleCheck: faCircleCheck,
  gear: faGear,
  gift: faGift,
  gripVertical: faGripVertical,
  'grip-vertical': faGripVertical,
  search: faMagnifyingGlass,
  plus: faPlus,
  minus: faMinus,
  rocket: faRocket,
  floppy: faFloppyDisk,
  wand: faWandMagicSparkles,
  archive: faBoxArchive,
  eye: faEye,
  eyeSlash: faEyeSlash,
  bookmark: faBookmark,
  bookOpen: faBookOpen,
  desktop: faDesktop,
  fileLines: faFileLines,
  download: faDownload,
  ellipsisVertical: faEllipsisVertical,
  'ellipsis-vertical': faEllipsisVertical,
  arrowRotateLeft: faArrowRotateLeft,
  bars: faBars,
  cloudArrowDown: faCloudArrowDown,
  copy: faCopy,
  cube: faCube,
  house: faHouse,
  star: faStar,
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  xmark: faXmark,
  check: faCheck,
  user: faUser,
  users: faUsers,
  building: faBuilding,
  tag: faTag,
  pin: faThumbTack,
  thumbtack: faThumbTack,
  towerBroadcast: faTowerBroadcast,
  language: faLanguage,
  layers: faLayerGroup,
  'layer-group': faLayerGroup,
  child: faChild,
  calendar: faCalendarDays,
  caretDown: faCaretDown,
  'caret-down': faCaretDown,
  clock: faClock,
  link: faLink,
  list: faList,
  microsoft: faMicrosoft,
  fileZipper: faFileZipper,
  'file-zipper': faFileZipper,
  tableCells: faTableCells,
  'table-cells': faTableCells,
};

export const ICON_NAMES = Object.freeze(Object.keys(ICONS));

function FaIcon({ name, className = '', title, size = 14 }) {
  const icon = ICONS[name];
  if (!icon) return null;

  return (
    <FontAwesomeIcon
      icon={icon}
      className={`fa-icon ${className}`.trim()}
      title={title}
      aria-hidden={title ? undefined : true}
      style={{
        width: `calc(${size}px * var(--font-scale, 1))`,
        height: `calc(${size}px * var(--font-scale, 1))`,
      }}
    />
  );
}

export { FaIcon };
export default FaIcon;
